
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma-related types and utilities in a browser. 
 * Use it to get access to models, enums, and input types.
 * 
 * This file does not contain a `PrismaClient` class, nor several other helpers that are intended as server-side only.
 * See `client.ts` for the standard, server-side entry point.
 *
 * 🟢 You can import this file directly.
 */

import * as Prisma from './internal/prismaNamespaceBrowser'
export { Prisma }
export * as $Enums from './enums'
export * from './enums';
/**
 * Model LocalFile
 * 
 */
export type LocalFile = Prisma.LocalFileModel
/**
 * Model File
 * 
 */
export type File = Prisma.FileModel
/**
 * Model User
 * 
 */
export type User = Prisma.UserModel
/**
 * Model MinecraftVersion
 * 
 */
export type MinecraftVersion = Prisma.MinecraftVersionModel
/**
 * Model MinecraftLoader
 * 
 */
export type MinecraftLoader = Prisma.MinecraftLoaderModel
/**
 * Model ShaderLoader
 * 
 */
export type ShaderLoader = Prisma.ShaderLoaderModel
/**
 * Model ModFile
 * 
 */
export type ModFile = Prisma.ModFileModel
/**
 * Model Mod
 * 
 */
export type Mod = Prisma.ModModel
/**
 * Model ModConflict
 * 
 */
export type ModConflict = Prisma.ModConflictModel
/**
 * Model ModDependency
 * 
 */
export type ModDependency = Prisma.ModDependencyModel
/**
 * Model ShaderFile
 * 
 */
export type ShaderFile = Prisma.ShaderFileModel
/**
 * Model Shader
 * 
 */
export type Shader = Prisma.ShaderModel
/**
 * Model Pack
 * 
 */
export type Pack = Prisma.PackModel
/**
 * Model PackVersion
 * 
 */
export type PackVersion = Prisma.PackVersionModel
/**
 * Model PackMod
 * 
 */
export type PackMod = Prisma.PackModModel
/**
 * Model PackShader
 * 
 */
export type PackShader = Prisma.PackShaderModel
/**
 * Model Comment
 * 
 */
export type Comment = Prisma.CommentModel
