
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const UserStatus = {
  active: 'active',
  inactive: 'inactive',
  banned: 'banned'
} as const

export type UserStatus = (typeof UserStatus)[keyof typeof UserStatus]


export const UserRole = {
  admin: 'admin',
  user: 'user',
  superuser: 'superuser'
} as const

export type UserRole = (typeof UserRole)[keyof typeof UserRole]


export const ModStatus = {
  published: 'published',
  draft: 'draft',
  rejected: 'rejected'
} as const

export type ModStatus = (typeof ModStatus)[keyof typeof ModStatus]


export const ModDependencyRol = {
  required: 'required',
  optional: 'optional',
  incompatible: 'incompatible'
} as const

export type ModDependencyRol = (typeof ModDependencyRol)[keyof typeof ModDependencyRol]


export const PackStatus = {
  published: 'published',
  draft: 'draft',
  rejected: 'rejected'
} as const

export type PackStatus = (typeof PackStatus)[keyof typeof PackStatus]
