
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `MinecraftLoader` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model MinecraftLoader
 * 
 */
export type MinecraftLoaderModel = runtime.Types.Result.DefaultSelection<Prisma.$MinecraftLoaderPayload>

export type AggregateMinecraftLoader = {
  _count: MinecraftLoaderCountAggregateOutputType | null
  _min: MinecraftLoaderMinAggregateOutputType | null
  _max: MinecraftLoaderMaxAggregateOutputType | null
}

export type MinecraftLoaderMinAggregateOutputType = {
  id: string | null
  name: string | null
  iconId: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type MinecraftLoaderMaxAggregateOutputType = {
  id: string | null
  name: string | null
  iconId: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type MinecraftLoaderCountAggregateOutputType = {
  id: number
  name: number
  iconId: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type MinecraftLoaderMinAggregateInputType = {
  id?: true
  name?: true
  iconId?: true
  createdAt?: true
  updatedAt?: true
}

export type MinecraftLoaderMaxAggregateInputType = {
  id?: true
  name?: true
  iconId?: true
  createdAt?: true
  updatedAt?: true
}

export type MinecraftLoaderCountAggregateInputType = {
  id?: true
  name?: true
  iconId?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type MinecraftLoaderAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which MinecraftLoader to aggregate.
   */
  where?: Prisma.MinecraftLoaderWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MinecraftLoaders to fetch.
   */
  orderBy?: Prisma.MinecraftLoaderOrderByWithRelationInput | Prisma.MinecraftLoaderOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.MinecraftLoaderWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MinecraftLoaders from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MinecraftLoaders.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned MinecraftLoaders
  **/
  _count?: true | MinecraftLoaderCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: MinecraftLoaderMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: MinecraftLoaderMaxAggregateInputType
}

export type GetMinecraftLoaderAggregateType<T extends MinecraftLoaderAggregateArgs> = {
      [P in keyof T & keyof AggregateMinecraftLoader]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateMinecraftLoader[P]>
    : Prisma.GetScalarType<T[P], AggregateMinecraftLoader[P]>
}




export type MinecraftLoaderGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.MinecraftLoaderWhereInput
  orderBy?: Prisma.MinecraftLoaderOrderByWithAggregationInput | Prisma.MinecraftLoaderOrderByWithAggregationInput[]
  by: Prisma.MinecraftLoaderScalarFieldEnum[] | Prisma.MinecraftLoaderScalarFieldEnum
  having?: Prisma.MinecraftLoaderScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: MinecraftLoaderCountAggregateInputType | true
  _min?: MinecraftLoaderMinAggregateInputType
  _max?: MinecraftLoaderMaxAggregateInputType
}

export type MinecraftLoaderGroupByOutputType = {
  id: string
  name: string
  iconId: string | null
  createdAt: Date
  updatedAt: Date
  _count: MinecraftLoaderCountAggregateOutputType | null
  _min: MinecraftLoaderMinAggregateOutputType | null
  _max: MinecraftLoaderMaxAggregateOutputType | null
}

export type GetMinecraftLoaderGroupByPayload<T extends MinecraftLoaderGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<MinecraftLoaderGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof MinecraftLoaderGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], MinecraftLoaderGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], MinecraftLoaderGroupByOutputType[P]>
      }
    >
  >



export type MinecraftLoaderWhereInput = {
  AND?: Prisma.MinecraftLoaderWhereInput | Prisma.MinecraftLoaderWhereInput[]
  OR?: Prisma.MinecraftLoaderWhereInput[]
  NOT?: Prisma.MinecraftLoaderWhereInput | Prisma.MinecraftLoaderWhereInput[]
  id?: Prisma.StringFilter<"MinecraftLoader"> | string
  name?: Prisma.StringFilter<"MinecraftLoader"> | string
  iconId?: Prisma.StringNullableFilter<"MinecraftLoader"> | string | null
  createdAt?: Prisma.DateTimeFilter<"MinecraftLoader"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"MinecraftLoader"> | Date | string
  icon?: Prisma.XOR<Prisma.FileNullableScalarRelationFilter, Prisma.FileWhereInput> | null
  modFiles?: Prisma.ModFileListRelationFilter
  shaderFiles?: Prisma.ShaderFileListRelationFilter
  packVersions?: Prisma.PackVersionListRelationFilter
}

export type MinecraftLoaderOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  iconId?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  icon?: Prisma.FileOrderByWithRelationInput
  modFiles?: Prisma.ModFileOrderByRelationAggregateInput
  shaderFiles?: Prisma.ShaderFileOrderByRelationAggregateInput
  packVersions?: Prisma.PackVersionOrderByRelationAggregateInput
}

export type MinecraftLoaderWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  iconId?: string
  AND?: Prisma.MinecraftLoaderWhereInput | Prisma.MinecraftLoaderWhereInput[]
  OR?: Prisma.MinecraftLoaderWhereInput[]
  NOT?: Prisma.MinecraftLoaderWhereInput | Prisma.MinecraftLoaderWhereInput[]
  name?: Prisma.StringFilter<"MinecraftLoader"> | string
  createdAt?: Prisma.DateTimeFilter<"MinecraftLoader"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"MinecraftLoader"> | Date | string
  icon?: Prisma.XOR<Prisma.FileNullableScalarRelationFilter, Prisma.FileWhereInput> | null
  modFiles?: Prisma.ModFileListRelationFilter
  shaderFiles?: Prisma.ShaderFileListRelationFilter
  packVersions?: Prisma.PackVersionListRelationFilter
}, "id" | "iconId">

export type MinecraftLoaderOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  iconId?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.MinecraftLoaderCountOrderByAggregateInput
  _max?: Prisma.MinecraftLoaderMaxOrderByAggregateInput
  _min?: Prisma.MinecraftLoaderMinOrderByAggregateInput
}

export type MinecraftLoaderScalarWhereWithAggregatesInput = {
  AND?: Prisma.MinecraftLoaderScalarWhereWithAggregatesInput | Prisma.MinecraftLoaderScalarWhereWithAggregatesInput[]
  OR?: Prisma.MinecraftLoaderScalarWhereWithAggregatesInput[]
  NOT?: Prisma.MinecraftLoaderScalarWhereWithAggregatesInput | Prisma.MinecraftLoaderScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"MinecraftLoader"> | string
  name?: Prisma.StringWithAggregatesFilter<"MinecraftLoader"> | string
  iconId?: Prisma.StringNullableWithAggregatesFilter<"MinecraftLoader"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"MinecraftLoader"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"MinecraftLoader"> | Date | string
}

export type MinecraftLoaderCreateInput = {
  id?: string
  name: string
  createdAt?: Date | string
  updatedAt?: Date | string
  icon?: Prisma.FileCreateNestedOneWithoutMinecraftLoaderInput
  modFiles?: Prisma.ModFileCreateNestedManyWithoutLoaderInput
  shaderFiles?: Prisma.ShaderFileCreateNestedManyWithoutLoaderInput
  packVersions?: Prisma.PackVersionCreateNestedManyWithoutMinecraftLoaderInput
}

export type MinecraftLoaderUncheckedCreateInput = {
  id?: string
  name: string
  iconId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  modFiles?: Prisma.ModFileUncheckedCreateNestedManyWithoutLoaderInput
  shaderFiles?: Prisma.ShaderFileUncheckedCreateNestedManyWithoutLoaderInput
  packVersions?: Prisma.PackVersionUncheckedCreateNestedManyWithoutMinecraftLoaderInput
}

export type MinecraftLoaderUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  icon?: Prisma.FileUpdateOneWithoutMinecraftLoaderNestedInput
  modFiles?: Prisma.ModFileUpdateManyWithoutLoaderNestedInput
  shaderFiles?: Prisma.ShaderFileUpdateManyWithoutLoaderNestedInput
  packVersions?: Prisma.PackVersionUpdateManyWithoutMinecraftLoaderNestedInput
}

export type MinecraftLoaderUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  iconId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  modFiles?: Prisma.ModFileUncheckedUpdateManyWithoutLoaderNestedInput
  shaderFiles?: Prisma.ShaderFileUncheckedUpdateManyWithoutLoaderNestedInput
  packVersions?: Prisma.PackVersionUncheckedUpdateManyWithoutMinecraftLoaderNestedInput
}

export type MinecraftLoaderCreateManyInput = {
  id?: string
  name: string
  iconId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type MinecraftLoaderUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MinecraftLoaderUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  iconId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MinecraftLoaderNullableScalarRelationFilter = {
  is?: Prisma.MinecraftLoaderWhereInput | null
  isNot?: Prisma.MinecraftLoaderWhereInput | null
}

export type MinecraftLoaderCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  iconId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type MinecraftLoaderMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  iconId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type MinecraftLoaderMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  iconId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type MinecraftLoaderScalarRelationFilter = {
  is?: Prisma.MinecraftLoaderWhereInput
  isNot?: Prisma.MinecraftLoaderWhereInput
}

export type MinecraftLoaderCreateNestedOneWithoutIconInput = {
  create?: Prisma.XOR<Prisma.MinecraftLoaderCreateWithoutIconInput, Prisma.MinecraftLoaderUncheckedCreateWithoutIconInput>
  connectOrCreate?: Prisma.MinecraftLoaderCreateOrConnectWithoutIconInput
  connect?: Prisma.MinecraftLoaderWhereUniqueInput
}

export type MinecraftLoaderUncheckedCreateNestedOneWithoutIconInput = {
  create?: Prisma.XOR<Prisma.MinecraftLoaderCreateWithoutIconInput, Prisma.MinecraftLoaderUncheckedCreateWithoutIconInput>
  connectOrCreate?: Prisma.MinecraftLoaderCreateOrConnectWithoutIconInput
  connect?: Prisma.MinecraftLoaderWhereUniqueInput
}

export type MinecraftLoaderUpdateOneWithoutIconNestedInput = {
  create?: Prisma.XOR<Prisma.MinecraftLoaderCreateWithoutIconInput, Prisma.MinecraftLoaderUncheckedCreateWithoutIconInput>
  connectOrCreate?: Prisma.MinecraftLoaderCreateOrConnectWithoutIconInput
  upsert?: Prisma.MinecraftLoaderUpsertWithoutIconInput
  disconnect?: Prisma.MinecraftLoaderWhereInput | boolean
  delete?: Prisma.MinecraftLoaderWhereInput | boolean
  connect?: Prisma.MinecraftLoaderWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.MinecraftLoaderUpdateToOneWithWhereWithoutIconInput, Prisma.MinecraftLoaderUpdateWithoutIconInput>, Prisma.MinecraftLoaderUncheckedUpdateWithoutIconInput>
}

export type MinecraftLoaderUncheckedUpdateOneWithoutIconNestedInput = {
  create?: Prisma.XOR<Prisma.MinecraftLoaderCreateWithoutIconInput, Prisma.MinecraftLoaderUncheckedCreateWithoutIconInput>
  connectOrCreate?: Prisma.MinecraftLoaderCreateOrConnectWithoutIconInput
  upsert?: Prisma.MinecraftLoaderUpsertWithoutIconInput
  disconnect?: Prisma.MinecraftLoaderWhereInput | boolean
  delete?: Prisma.MinecraftLoaderWhereInput | boolean
  connect?: Prisma.MinecraftLoaderWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.MinecraftLoaderUpdateToOneWithWhereWithoutIconInput, Prisma.MinecraftLoaderUpdateWithoutIconInput>, Prisma.MinecraftLoaderUncheckedUpdateWithoutIconInput>
}

export type MinecraftLoaderCreateNestedOneWithoutModFilesInput = {
  create?: Prisma.XOR<Prisma.MinecraftLoaderCreateWithoutModFilesInput, Prisma.MinecraftLoaderUncheckedCreateWithoutModFilesInput>
  connectOrCreate?: Prisma.MinecraftLoaderCreateOrConnectWithoutModFilesInput
  connect?: Prisma.MinecraftLoaderWhereUniqueInput
}

export type MinecraftLoaderUpdateOneRequiredWithoutModFilesNestedInput = {
  create?: Prisma.XOR<Prisma.MinecraftLoaderCreateWithoutModFilesInput, Prisma.MinecraftLoaderUncheckedCreateWithoutModFilesInput>
  connectOrCreate?: Prisma.MinecraftLoaderCreateOrConnectWithoutModFilesInput
  upsert?: Prisma.MinecraftLoaderUpsertWithoutModFilesInput
  connect?: Prisma.MinecraftLoaderWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.MinecraftLoaderUpdateToOneWithWhereWithoutModFilesInput, Prisma.MinecraftLoaderUpdateWithoutModFilesInput>, Prisma.MinecraftLoaderUncheckedUpdateWithoutModFilesInput>
}

export type MinecraftLoaderCreateNestedOneWithoutShaderFilesInput = {
  create?: Prisma.XOR<Prisma.MinecraftLoaderCreateWithoutShaderFilesInput, Prisma.MinecraftLoaderUncheckedCreateWithoutShaderFilesInput>
  connectOrCreate?: Prisma.MinecraftLoaderCreateOrConnectWithoutShaderFilesInput
  connect?: Prisma.MinecraftLoaderWhereUniqueInput
}

export type MinecraftLoaderUpdateOneRequiredWithoutShaderFilesNestedInput = {
  create?: Prisma.XOR<Prisma.MinecraftLoaderCreateWithoutShaderFilesInput, Prisma.MinecraftLoaderUncheckedCreateWithoutShaderFilesInput>
  connectOrCreate?: Prisma.MinecraftLoaderCreateOrConnectWithoutShaderFilesInput
  upsert?: Prisma.MinecraftLoaderUpsertWithoutShaderFilesInput
  connect?: Prisma.MinecraftLoaderWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.MinecraftLoaderUpdateToOneWithWhereWithoutShaderFilesInput, Prisma.MinecraftLoaderUpdateWithoutShaderFilesInput>, Prisma.MinecraftLoaderUncheckedUpdateWithoutShaderFilesInput>
}

export type MinecraftLoaderCreateNestedOneWithoutPackVersionsInput = {
  create?: Prisma.XOR<Prisma.MinecraftLoaderCreateWithoutPackVersionsInput, Prisma.MinecraftLoaderUncheckedCreateWithoutPackVersionsInput>
  connectOrCreate?: Prisma.MinecraftLoaderCreateOrConnectWithoutPackVersionsInput
  connect?: Prisma.MinecraftLoaderWhereUniqueInput
}

export type MinecraftLoaderUpdateOneRequiredWithoutPackVersionsNestedInput = {
  create?: Prisma.XOR<Prisma.MinecraftLoaderCreateWithoutPackVersionsInput, Prisma.MinecraftLoaderUncheckedCreateWithoutPackVersionsInput>
  connectOrCreate?: Prisma.MinecraftLoaderCreateOrConnectWithoutPackVersionsInput
  upsert?: Prisma.MinecraftLoaderUpsertWithoutPackVersionsInput
  connect?: Prisma.MinecraftLoaderWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.MinecraftLoaderUpdateToOneWithWhereWithoutPackVersionsInput, Prisma.MinecraftLoaderUpdateWithoutPackVersionsInput>, Prisma.MinecraftLoaderUncheckedUpdateWithoutPackVersionsInput>
}

export type MinecraftLoaderCreateWithoutIconInput = {
  id?: string
  name: string
  createdAt?: Date | string
  updatedAt?: Date | string
  modFiles?: Prisma.ModFileCreateNestedManyWithoutLoaderInput
  shaderFiles?: Prisma.ShaderFileCreateNestedManyWithoutLoaderInput
  packVersions?: Prisma.PackVersionCreateNestedManyWithoutMinecraftLoaderInput
}

export type MinecraftLoaderUncheckedCreateWithoutIconInput = {
  id?: string
  name: string
  createdAt?: Date | string
  updatedAt?: Date | string
  modFiles?: Prisma.ModFileUncheckedCreateNestedManyWithoutLoaderInput
  shaderFiles?: Prisma.ShaderFileUncheckedCreateNestedManyWithoutLoaderInput
  packVersions?: Prisma.PackVersionUncheckedCreateNestedManyWithoutMinecraftLoaderInput
}

export type MinecraftLoaderCreateOrConnectWithoutIconInput = {
  where: Prisma.MinecraftLoaderWhereUniqueInput
  create: Prisma.XOR<Prisma.MinecraftLoaderCreateWithoutIconInput, Prisma.MinecraftLoaderUncheckedCreateWithoutIconInput>
}

export type MinecraftLoaderUpsertWithoutIconInput = {
  update: Prisma.XOR<Prisma.MinecraftLoaderUpdateWithoutIconInput, Prisma.MinecraftLoaderUncheckedUpdateWithoutIconInput>
  create: Prisma.XOR<Prisma.MinecraftLoaderCreateWithoutIconInput, Prisma.MinecraftLoaderUncheckedCreateWithoutIconInput>
  where?: Prisma.MinecraftLoaderWhereInput
}

export type MinecraftLoaderUpdateToOneWithWhereWithoutIconInput = {
  where?: Prisma.MinecraftLoaderWhereInput
  data: Prisma.XOR<Prisma.MinecraftLoaderUpdateWithoutIconInput, Prisma.MinecraftLoaderUncheckedUpdateWithoutIconInput>
}

export type MinecraftLoaderUpdateWithoutIconInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  modFiles?: Prisma.ModFileUpdateManyWithoutLoaderNestedInput
  shaderFiles?: Prisma.ShaderFileUpdateManyWithoutLoaderNestedInput
  packVersions?: Prisma.PackVersionUpdateManyWithoutMinecraftLoaderNestedInput
}

export type MinecraftLoaderUncheckedUpdateWithoutIconInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  modFiles?: Prisma.ModFileUncheckedUpdateManyWithoutLoaderNestedInput
  shaderFiles?: Prisma.ShaderFileUncheckedUpdateManyWithoutLoaderNestedInput
  packVersions?: Prisma.PackVersionUncheckedUpdateManyWithoutMinecraftLoaderNestedInput
}

export type MinecraftLoaderCreateWithoutModFilesInput = {
  id?: string
  name: string
  createdAt?: Date | string
  updatedAt?: Date | string
  icon?: Prisma.FileCreateNestedOneWithoutMinecraftLoaderInput
  shaderFiles?: Prisma.ShaderFileCreateNestedManyWithoutLoaderInput
  packVersions?: Prisma.PackVersionCreateNestedManyWithoutMinecraftLoaderInput
}

export type MinecraftLoaderUncheckedCreateWithoutModFilesInput = {
  id?: string
  name: string
  iconId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  shaderFiles?: Prisma.ShaderFileUncheckedCreateNestedManyWithoutLoaderInput
  packVersions?: Prisma.PackVersionUncheckedCreateNestedManyWithoutMinecraftLoaderInput
}

export type MinecraftLoaderCreateOrConnectWithoutModFilesInput = {
  where: Prisma.MinecraftLoaderWhereUniqueInput
  create: Prisma.XOR<Prisma.MinecraftLoaderCreateWithoutModFilesInput, Prisma.MinecraftLoaderUncheckedCreateWithoutModFilesInput>
}

export type MinecraftLoaderUpsertWithoutModFilesInput = {
  update: Prisma.XOR<Prisma.MinecraftLoaderUpdateWithoutModFilesInput, Prisma.MinecraftLoaderUncheckedUpdateWithoutModFilesInput>
  create: Prisma.XOR<Prisma.MinecraftLoaderCreateWithoutModFilesInput, Prisma.MinecraftLoaderUncheckedCreateWithoutModFilesInput>
  where?: Prisma.MinecraftLoaderWhereInput
}

export type MinecraftLoaderUpdateToOneWithWhereWithoutModFilesInput = {
  where?: Prisma.MinecraftLoaderWhereInput
  data: Prisma.XOR<Prisma.MinecraftLoaderUpdateWithoutModFilesInput, Prisma.MinecraftLoaderUncheckedUpdateWithoutModFilesInput>
}

export type MinecraftLoaderUpdateWithoutModFilesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  icon?: Prisma.FileUpdateOneWithoutMinecraftLoaderNestedInput
  shaderFiles?: Prisma.ShaderFileUpdateManyWithoutLoaderNestedInput
  packVersions?: Prisma.PackVersionUpdateManyWithoutMinecraftLoaderNestedInput
}

export type MinecraftLoaderUncheckedUpdateWithoutModFilesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  iconId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  shaderFiles?: Prisma.ShaderFileUncheckedUpdateManyWithoutLoaderNestedInput
  packVersions?: Prisma.PackVersionUncheckedUpdateManyWithoutMinecraftLoaderNestedInput
}

export type MinecraftLoaderCreateWithoutShaderFilesInput = {
  id?: string
  name: string
  createdAt?: Date | string
  updatedAt?: Date | string
  icon?: Prisma.FileCreateNestedOneWithoutMinecraftLoaderInput
  modFiles?: Prisma.ModFileCreateNestedManyWithoutLoaderInput
  packVersions?: Prisma.PackVersionCreateNestedManyWithoutMinecraftLoaderInput
}

export type MinecraftLoaderUncheckedCreateWithoutShaderFilesInput = {
  id?: string
  name: string
  iconId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  modFiles?: Prisma.ModFileUncheckedCreateNestedManyWithoutLoaderInput
  packVersions?: Prisma.PackVersionUncheckedCreateNestedManyWithoutMinecraftLoaderInput
}

export type MinecraftLoaderCreateOrConnectWithoutShaderFilesInput = {
  where: Prisma.MinecraftLoaderWhereUniqueInput
  create: Prisma.XOR<Prisma.MinecraftLoaderCreateWithoutShaderFilesInput, Prisma.MinecraftLoaderUncheckedCreateWithoutShaderFilesInput>
}

export type MinecraftLoaderUpsertWithoutShaderFilesInput = {
  update: Prisma.XOR<Prisma.MinecraftLoaderUpdateWithoutShaderFilesInput, Prisma.MinecraftLoaderUncheckedUpdateWithoutShaderFilesInput>
  create: Prisma.XOR<Prisma.MinecraftLoaderCreateWithoutShaderFilesInput, Prisma.MinecraftLoaderUncheckedCreateWithoutShaderFilesInput>
  where?: Prisma.MinecraftLoaderWhereInput
}

export type MinecraftLoaderUpdateToOneWithWhereWithoutShaderFilesInput = {
  where?: Prisma.MinecraftLoaderWhereInput
  data: Prisma.XOR<Prisma.MinecraftLoaderUpdateWithoutShaderFilesInput, Prisma.MinecraftLoaderUncheckedUpdateWithoutShaderFilesInput>
}

export type MinecraftLoaderUpdateWithoutShaderFilesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  icon?: Prisma.FileUpdateOneWithoutMinecraftLoaderNestedInput
  modFiles?: Prisma.ModFileUpdateManyWithoutLoaderNestedInput
  packVersions?: Prisma.PackVersionUpdateManyWithoutMinecraftLoaderNestedInput
}

export type MinecraftLoaderUncheckedUpdateWithoutShaderFilesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  iconId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  modFiles?: Prisma.ModFileUncheckedUpdateManyWithoutLoaderNestedInput
  packVersions?: Prisma.PackVersionUncheckedUpdateManyWithoutMinecraftLoaderNestedInput
}

export type MinecraftLoaderCreateWithoutPackVersionsInput = {
  id?: string
  name: string
  createdAt?: Date | string
  updatedAt?: Date | string
  icon?: Prisma.FileCreateNestedOneWithoutMinecraftLoaderInput
  modFiles?: Prisma.ModFileCreateNestedManyWithoutLoaderInput
  shaderFiles?: Prisma.ShaderFileCreateNestedManyWithoutLoaderInput
}

export type MinecraftLoaderUncheckedCreateWithoutPackVersionsInput = {
  id?: string
  name: string
  iconId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  modFiles?: Prisma.ModFileUncheckedCreateNestedManyWithoutLoaderInput
  shaderFiles?: Prisma.ShaderFileUncheckedCreateNestedManyWithoutLoaderInput
}

export type MinecraftLoaderCreateOrConnectWithoutPackVersionsInput = {
  where: Prisma.MinecraftLoaderWhereUniqueInput
  create: Prisma.XOR<Prisma.MinecraftLoaderCreateWithoutPackVersionsInput, Prisma.MinecraftLoaderUncheckedCreateWithoutPackVersionsInput>
}

export type MinecraftLoaderUpsertWithoutPackVersionsInput = {
  update: Prisma.XOR<Prisma.MinecraftLoaderUpdateWithoutPackVersionsInput, Prisma.MinecraftLoaderUncheckedUpdateWithoutPackVersionsInput>
  create: Prisma.XOR<Prisma.MinecraftLoaderCreateWithoutPackVersionsInput, Prisma.MinecraftLoaderUncheckedCreateWithoutPackVersionsInput>
  where?: Prisma.MinecraftLoaderWhereInput
}

export type MinecraftLoaderUpdateToOneWithWhereWithoutPackVersionsInput = {
  where?: Prisma.MinecraftLoaderWhereInput
  data: Prisma.XOR<Prisma.MinecraftLoaderUpdateWithoutPackVersionsInput, Prisma.MinecraftLoaderUncheckedUpdateWithoutPackVersionsInput>
}

export type MinecraftLoaderUpdateWithoutPackVersionsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  icon?: Prisma.FileUpdateOneWithoutMinecraftLoaderNestedInput
  modFiles?: Prisma.ModFileUpdateManyWithoutLoaderNestedInput
  shaderFiles?: Prisma.ShaderFileUpdateManyWithoutLoaderNestedInput
}

export type MinecraftLoaderUncheckedUpdateWithoutPackVersionsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  iconId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  modFiles?: Prisma.ModFileUncheckedUpdateManyWithoutLoaderNestedInput
  shaderFiles?: Prisma.ShaderFileUncheckedUpdateManyWithoutLoaderNestedInput
}


/**
 * Count Type MinecraftLoaderCountOutputType
 */

export type MinecraftLoaderCountOutputType = {
  modFiles: number
  shaderFiles: number
  packVersions: number
}

export type MinecraftLoaderCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  modFiles?: boolean | MinecraftLoaderCountOutputTypeCountModFilesArgs
  shaderFiles?: boolean | MinecraftLoaderCountOutputTypeCountShaderFilesArgs
  packVersions?: boolean | MinecraftLoaderCountOutputTypeCountPackVersionsArgs
}

/**
 * MinecraftLoaderCountOutputType without action
 */
export type MinecraftLoaderCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MinecraftLoaderCountOutputType
   */
  select?: Prisma.MinecraftLoaderCountOutputTypeSelect<ExtArgs> | null
}

/**
 * MinecraftLoaderCountOutputType without action
 */
export type MinecraftLoaderCountOutputTypeCountModFilesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ModFileWhereInput
}

/**
 * MinecraftLoaderCountOutputType without action
 */
export type MinecraftLoaderCountOutputTypeCountShaderFilesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ShaderFileWhereInput
}

/**
 * MinecraftLoaderCountOutputType without action
 */
export type MinecraftLoaderCountOutputTypeCountPackVersionsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PackVersionWhereInput
}


export type MinecraftLoaderSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  iconId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  icon?: boolean | Prisma.MinecraftLoader$iconArgs<ExtArgs>
  modFiles?: boolean | Prisma.MinecraftLoader$modFilesArgs<ExtArgs>
  shaderFiles?: boolean | Prisma.MinecraftLoader$shaderFilesArgs<ExtArgs>
  packVersions?: boolean | Prisma.MinecraftLoader$packVersionsArgs<ExtArgs>
  _count?: boolean | Prisma.MinecraftLoaderCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["minecraftLoader"]>

export type MinecraftLoaderSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  iconId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  icon?: boolean | Prisma.MinecraftLoader$iconArgs<ExtArgs>
}, ExtArgs["result"]["minecraftLoader"]>

export type MinecraftLoaderSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  iconId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  icon?: boolean | Prisma.MinecraftLoader$iconArgs<ExtArgs>
}, ExtArgs["result"]["minecraftLoader"]>

export type MinecraftLoaderSelectScalar = {
  id?: boolean
  name?: boolean
  iconId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type MinecraftLoaderOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "iconId" | "createdAt" | "updatedAt", ExtArgs["result"]["minecraftLoader"]>
export type MinecraftLoaderInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  icon?: boolean | Prisma.MinecraftLoader$iconArgs<ExtArgs>
  modFiles?: boolean | Prisma.MinecraftLoader$modFilesArgs<ExtArgs>
  shaderFiles?: boolean | Prisma.MinecraftLoader$shaderFilesArgs<ExtArgs>
  packVersions?: boolean | Prisma.MinecraftLoader$packVersionsArgs<ExtArgs>
  _count?: boolean | Prisma.MinecraftLoaderCountOutputTypeDefaultArgs<ExtArgs>
}
export type MinecraftLoaderIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  icon?: boolean | Prisma.MinecraftLoader$iconArgs<ExtArgs>
}
export type MinecraftLoaderIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  icon?: boolean | Prisma.MinecraftLoader$iconArgs<ExtArgs>
}

export type $MinecraftLoaderPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "MinecraftLoader"
  objects: {
    icon: Prisma.$FilePayload<ExtArgs> | null
    modFiles: Prisma.$ModFilePayload<ExtArgs>[]
    shaderFiles: Prisma.$ShaderFilePayload<ExtArgs>[]
    packVersions: Prisma.$PackVersionPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    name: string
    iconId: string | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["minecraftLoader"]>
  composites: {}
}

export type MinecraftLoaderGetPayload<S extends boolean | null | undefined | MinecraftLoaderDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$MinecraftLoaderPayload, S>

export type MinecraftLoaderCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<MinecraftLoaderFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: MinecraftLoaderCountAggregateInputType | true
  }

export interface MinecraftLoaderDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['MinecraftLoader'], meta: { name: 'MinecraftLoader' } }
  /**
   * Find zero or one MinecraftLoader that matches the filter.
   * @param {MinecraftLoaderFindUniqueArgs} args - Arguments to find a MinecraftLoader
   * @example
   * // Get one MinecraftLoader
   * const minecraftLoader = await prisma.minecraftLoader.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends MinecraftLoaderFindUniqueArgs>(args: Prisma.SelectSubset<T, MinecraftLoaderFindUniqueArgs<ExtArgs>>): Prisma.Prisma__MinecraftLoaderClient<runtime.Types.Result.GetResult<Prisma.$MinecraftLoaderPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one MinecraftLoader that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {MinecraftLoaderFindUniqueOrThrowArgs} args - Arguments to find a MinecraftLoader
   * @example
   * // Get one MinecraftLoader
   * const minecraftLoader = await prisma.minecraftLoader.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends MinecraftLoaderFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, MinecraftLoaderFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__MinecraftLoaderClient<runtime.Types.Result.GetResult<Prisma.$MinecraftLoaderPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first MinecraftLoader that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MinecraftLoaderFindFirstArgs} args - Arguments to find a MinecraftLoader
   * @example
   * // Get one MinecraftLoader
   * const minecraftLoader = await prisma.minecraftLoader.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends MinecraftLoaderFindFirstArgs>(args?: Prisma.SelectSubset<T, MinecraftLoaderFindFirstArgs<ExtArgs>>): Prisma.Prisma__MinecraftLoaderClient<runtime.Types.Result.GetResult<Prisma.$MinecraftLoaderPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first MinecraftLoader that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MinecraftLoaderFindFirstOrThrowArgs} args - Arguments to find a MinecraftLoader
   * @example
   * // Get one MinecraftLoader
   * const minecraftLoader = await prisma.minecraftLoader.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends MinecraftLoaderFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, MinecraftLoaderFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__MinecraftLoaderClient<runtime.Types.Result.GetResult<Prisma.$MinecraftLoaderPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more MinecraftLoaders that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MinecraftLoaderFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all MinecraftLoaders
   * const minecraftLoaders = await prisma.minecraftLoader.findMany()
   * 
   * // Get first 10 MinecraftLoaders
   * const minecraftLoaders = await prisma.minecraftLoader.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const minecraftLoaderWithIdOnly = await prisma.minecraftLoader.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends MinecraftLoaderFindManyArgs>(args?: Prisma.SelectSubset<T, MinecraftLoaderFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MinecraftLoaderPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a MinecraftLoader.
   * @param {MinecraftLoaderCreateArgs} args - Arguments to create a MinecraftLoader.
   * @example
   * // Create one MinecraftLoader
   * const MinecraftLoader = await prisma.minecraftLoader.create({
   *   data: {
   *     // ... data to create a MinecraftLoader
   *   }
   * })
   * 
   */
  create<T extends MinecraftLoaderCreateArgs>(args: Prisma.SelectSubset<T, MinecraftLoaderCreateArgs<ExtArgs>>): Prisma.Prisma__MinecraftLoaderClient<runtime.Types.Result.GetResult<Prisma.$MinecraftLoaderPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many MinecraftLoaders.
   * @param {MinecraftLoaderCreateManyArgs} args - Arguments to create many MinecraftLoaders.
   * @example
   * // Create many MinecraftLoaders
   * const minecraftLoader = await prisma.minecraftLoader.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends MinecraftLoaderCreateManyArgs>(args?: Prisma.SelectSubset<T, MinecraftLoaderCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many MinecraftLoaders and returns the data saved in the database.
   * @param {MinecraftLoaderCreateManyAndReturnArgs} args - Arguments to create many MinecraftLoaders.
   * @example
   * // Create many MinecraftLoaders
   * const minecraftLoader = await prisma.minecraftLoader.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many MinecraftLoaders and only return the `id`
   * const minecraftLoaderWithIdOnly = await prisma.minecraftLoader.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends MinecraftLoaderCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, MinecraftLoaderCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MinecraftLoaderPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a MinecraftLoader.
   * @param {MinecraftLoaderDeleteArgs} args - Arguments to delete one MinecraftLoader.
   * @example
   * // Delete one MinecraftLoader
   * const MinecraftLoader = await prisma.minecraftLoader.delete({
   *   where: {
   *     // ... filter to delete one MinecraftLoader
   *   }
   * })
   * 
   */
  delete<T extends MinecraftLoaderDeleteArgs>(args: Prisma.SelectSubset<T, MinecraftLoaderDeleteArgs<ExtArgs>>): Prisma.Prisma__MinecraftLoaderClient<runtime.Types.Result.GetResult<Prisma.$MinecraftLoaderPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one MinecraftLoader.
   * @param {MinecraftLoaderUpdateArgs} args - Arguments to update one MinecraftLoader.
   * @example
   * // Update one MinecraftLoader
   * const minecraftLoader = await prisma.minecraftLoader.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends MinecraftLoaderUpdateArgs>(args: Prisma.SelectSubset<T, MinecraftLoaderUpdateArgs<ExtArgs>>): Prisma.Prisma__MinecraftLoaderClient<runtime.Types.Result.GetResult<Prisma.$MinecraftLoaderPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more MinecraftLoaders.
   * @param {MinecraftLoaderDeleteManyArgs} args - Arguments to filter MinecraftLoaders to delete.
   * @example
   * // Delete a few MinecraftLoaders
   * const { count } = await prisma.minecraftLoader.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends MinecraftLoaderDeleteManyArgs>(args?: Prisma.SelectSubset<T, MinecraftLoaderDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more MinecraftLoaders.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MinecraftLoaderUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many MinecraftLoaders
   * const minecraftLoader = await prisma.minecraftLoader.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends MinecraftLoaderUpdateManyArgs>(args: Prisma.SelectSubset<T, MinecraftLoaderUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more MinecraftLoaders and returns the data updated in the database.
   * @param {MinecraftLoaderUpdateManyAndReturnArgs} args - Arguments to update many MinecraftLoaders.
   * @example
   * // Update many MinecraftLoaders
   * const minecraftLoader = await prisma.minecraftLoader.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more MinecraftLoaders and only return the `id`
   * const minecraftLoaderWithIdOnly = await prisma.minecraftLoader.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends MinecraftLoaderUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, MinecraftLoaderUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MinecraftLoaderPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one MinecraftLoader.
   * @param {MinecraftLoaderUpsertArgs} args - Arguments to update or create a MinecraftLoader.
   * @example
   * // Update or create a MinecraftLoader
   * const minecraftLoader = await prisma.minecraftLoader.upsert({
   *   create: {
   *     // ... data to create a MinecraftLoader
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the MinecraftLoader we want to update
   *   }
   * })
   */
  upsert<T extends MinecraftLoaderUpsertArgs>(args: Prisma.SelectSubset<T, MinecraftLoaderUpsertArgs<ExtArgs>>): Prisma.Prisma__MinecraftLoaderClient<runtime.Types.Result.GetResult<Prisma.$MinecraftLoaderPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of MinecraftLoaders.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MinecraftLoaderCountArgs} args - Arguments to filter MinecraftLoaders to count.
   * @example
   * // Count the number of MinecraftLoaders
   * const count = await prisma.minecraftLoader.count({
   *   where: {
   *     // ... the filter for the MinecraftLoaders we want to count
   *   }
   * })
  **/
  count<T extends MinecraftLoaderCountArgs>(
    args?: Prisma.Subset<T, MinecraftLoaderCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], MinecraftLoaderCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a MinecraftLoader.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MinecraftLoaderAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends MinecraftLoaderAggregateArgs>(args: Prisma.Subset<T, MinecraftLoaderAggregateArgs>): Prisma.PrismaPromise<GetMinecraftLoaderAggregateType<T>>

  /**
   * Group by MinecraftLoader.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MinecraftLoaderGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends MinecraftLoaderGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: MinecraftLoaderGroupByArgs['orderBy'] }
      : { orderBy?: MinecraftLoaderGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, MinecraftLoaderGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetMinecraftLoaderGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the MinecraftLoader model
 */
readonly fields: MinecraftLoaderFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for MinecraftLoader.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__MinecraftLoaderClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  icon<T extends Prisma.MinecraftLoader$iconArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.MinecraftLoader$iconArgs<ExtArgs>>): Prisma.Prisma__FileClient<runtime.Types.Result.GetResult<Prisma.$FilePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  modFiles<T extends Prisma.MinecraftLoader$modFilesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.MinecraftLoader$modFilesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ModFilePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  shaderFiles<T extends Prisma.MinecraftLoader$shaderFilesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.MinecraftLoader$shaderFilesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ShaderFilePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  packVersions<T extends Prisma.MinecraftLoader$packVersionsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.MinecraftLoader$packVersionsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PackVersionPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the MinecraftLoader model
 */
export interface MinecraftLoaderFieldRefs {
  readonly id: Prisma.FieldRef<"MinecraftLoader", 'String'>
  readonly name: Prisma.FieldRef<"MinecraftLoader", 'String'>
  readonly iconId: Prisma.FieldRef<"MinecraftLoader", 'String'>
  readonly createdAt: Prisma.FieldRef<"MinecraftLoader", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"MinecraftLoader", 'DateTime'>
}
    

// Custom InputTypes
/**
 * MinecraftLoader findUnique
 */
export type MinecraftLoaderFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MinecraftLoader
   */
  select?: Prisma.MinecraftLoaderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MinecraftLoader
   */
  omit?: Prisma.MinecraftLoaderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MinecraftLoaderInclude<ExtArgs> | null
  /**
   * Filter, which MinecraftLoader to fetch.
   */
  where: Prisma.MinecraftLoaderWhereUniqueInput
}

/**
 * MinecraftLoader findUniqueOrThrow
 */
export type MinecraftLoaderFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MinecraftLoader
   */
  select?: Prisma.MinecraftLoaderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MinecraftLoader
   */
  omit?: Prisma.MinecraftLoaderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MinecraftLoaderInclude<ExtArgs> | null
  /**
   * Filter, which MinecraftLoader to fetch.
   */
  where: Prisma.MinecraftLoaderWhereUniqueInput
}

/**
 * MinecraftLoader findFirst
 */
export type MinecraftLoaderFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MinecraftLoader
   */
  select?: Prisma.MinecraftLoaderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MinecraftLoader
   */
  omit?: Prisma.MinecraftLoaderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MinecraftLoaderInclude<ExtArgs> | null
  /**
   * Filter, which MinecraftLoader to fetch.
   */
  where?: Prisma.MinecraftLoaderWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MinecraftLoaders to fetch.
   */
  orderBy?: Prisma.MinecraftLoaderOrderByWithRelationInput | Prisma.MinecraftLoaderOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for MinecraftLoaders.
   */
  cursor?: Prisma.MinecraftLoaderWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MinecraftLoaders from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MinecraftLoaders.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of MinecraftLoaders.
   */
  distinct?: Prisma.MinecraftLoaderScalarFieldEnum | Prisma.MinecraftLoaderScalarFieldEnum[]
}

/**
 * MinecraftLoader findFirstOrThrow
 */
export type MinecraftLoaderFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MinecraftLoader
   */
  select?: Prisma.MinecraftLoaderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MinecraftLoader
   */
  omit?: Prisma.MinecraftLoaderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MinecraftLoaderInclude<ExtArgs> | null
  /**
   * Filter, which MinecraftLoader to fetch.
   */
  where?: Prisma.MinecraftLoaderWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MinecraftLoaders to fetch.
   */
  orderBy?: Prisma.MinecraftLoaderOrderByWithRelationInput | Prisma.MinecraftLoaderOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for MinecraftLoaders.
   */
  cursor?: Prisma.MinecraftLoaderWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MinecraftLoaders from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MinecraftLoaders.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of MinecraftLoaders.
   */
  distinct?: Prisma.MinecraftLoaderScalarFieldEnum | Prisma.MinecraftLoaderScalarFieldEnum[]
}

/**
 * MinecraftLoader findMany
 */
export type MinecraftLoaderFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MinecraftLoader
   */
  select?: Prisma.MinecraftLoaderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MinecraftLoader
   */
  omit?: Prisma.MinecraftLoaderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MinecraftLoaderInclude<ExtArgs> | null
  /**
   * Filter, which MinecraftLoaders to fetch.
   */
  where?: Prisma.MinecraftLoaderWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MinecraftLoaders to fetch.
   */
  orderBy?: Prisma.MinecraftLoaderOrderByWithRelationInput | Prisma.MinecraftLoaderOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing MinecraftLoaders.
   */
  cursor?: Prisma.MinecraftLoaderWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MinecraftLoaders from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MinecraftLoaders.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of MinecraftLoaders.
   */
  distinct?: Prisma.MinecraftLoaderScalarFieldEnum | Prisma.MinecraftLoaderScalarFieldEnum[]
}

/**
 * MinecraftLoader create
 */
export type MinecraftLoaderCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MinecraftLoader
   */
  select?: Prisma.MinecraftLoaderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MinecraftLoader
   */
  omit?: Prisma.MinecraftLoaderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MinecraftLoaderInclude<ExtArgs> | null
  /**
   * The data needed to create a MinecraftLoader.
   */
  data: Prisma.XOR<Prisma.MinecraftLoaderCreateInput, Prisma.MinecraftLoaderUncheckedCreateInput>
}

/**
 * MinecraftLoader createMany
 */
export type MinecraftLoaderCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many MinecraftLoaders.
   */
  data: Prisma.MinecraftLoaderCreateManyInput | Prisma.MinecraftLoaderCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * MinecraftLoader createManyAndReturn
 */
export type MinecraftLoaderCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MinecraftLoader
   */
  select?: Prisma.MinecraftLoaderSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the MinecraftLoader
   */
  omit?: Prisma.MinecraftLoaderOmit<ExtArgs> | null
  /**
   * The data used to create many MinecraftLoaders.
   */
  data: Prisma.MinecraftLoaderCreateManyInput | Prisma.MinecraftLoaderCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MinecraftLoaderIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * MinecraftLoader update
 */
export type MinecraftLoaderUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MinecraftLoader
   */
  select?: Prisma.MinecraftLoaderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MinecraftLoader
   */
  omit?: Prisma.MinecraftLoaderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MinecraftLoaderInclude<ExtArgs> | null
  /**
   * The data needed to update a MinecraftLoader.
   */
  data: Prisma.XOR<Prisma.MinecraftLoaderUpdateInput, Prisma.MinecraftLoaderUncheckedUpdateInput>
  /**
   * Choose, which MinecraftLoader to update.
   */
  where: Prisma.MinecraftLoaderWhereUniqueInput
}

/**
 * MinecraftLoader updateMany
 */
export type MinecraftLoaderUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update MinecraftLoaders.
   */
  data: Prisma.XOR<Prisma.MinecraftLoaderUpdateManyMutationInput, Prisma.MinecraftLoaderUncheckedUpdateManyInput>
  /**
   * Filter which MinecraftLoaders to update
   */
  where?: Prisma.MinecraftLoaderWhereInput
  /**
   * Limit how many MinecraftLoaders to update.
   */
  limit?: number
}

/**
 * MinecraftLoader updateManyAndReturn
 */
export type MinecraftLoaderUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MinecraftLoader
   */
  select?: Prisma.MinecraftLoaderSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the MinecraftLoader
   */
  omit?: Prisma.MinecraftLoaderOmit<ExtArgs> | null
  /**
   * The data used to update MinecraftLoaders.
   */
  data: Prisma.XOR<Prisma.MinecraftLoaderUpdateManyMutationInput, Prisma.MinecraftLoaderUncheckedUpdateManyInput>
  /**
   * Filter which MinecraftLoaders to update
   */
  where?: Prisma.MinecraftLoaderWhereInput
  /**
   * Limit how many MinecraftLoaders to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MinecraftLoaderIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * MinecraftLoader upsert
 */
export type MinecraftLoaderUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MinecraftLoader
   */
  select?: Prisma.MinecraftLoaderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MinecraftLoader
   */
  omit?: Prisma.MinecraftLoaderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MinecraftLoaderInclude<ExtArgs> | null
  /**
   * The filter to search for the MinecraftLoader to update in case it exists.
   */
  where: Prisma.MinecraftLoaderWhereUniqueInput
  /**
   * In case the MinecraftLoader found by the `where` argument doesn't exist, create a new MinecraftLoader with this data.
   */
  create: Prisma.XOR<Prisma.MinecraftLoaderCreateInput, Prisma.MinecraftLoaderUncheckedCreateInput>
  /**
   * In case the MinecraftLoader was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.MinecraftLoaderUpdateInput, Prisma.MinecraftLoaderUncheckedUpdateInput>
}

/**
 * MinecraftLoader delete
 */
export type MinecraftLoaderDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MinecraftLoader
   */
  select?: Prisma.MinecraftLoaderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MinecraftLoader
   */
  omit?: Prisma.MinecraftLoaderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MinecraftLoaderInclude<ExtArgs> | null
  /**
   * Filter which MinecraftLoader to delete.
   */
  where: Prisma.MinecraftLoaderWhereUniqueInput
}

/**
 * MinecraftLoader deleteMany
 */
export type MinecraftLoaderDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which MinecraftLoaders to delete
   */
  where?: Prisma.MinecraftLoaderWhereInput
  /**
   * Limit how many MinecraftLoaders to delete.
   */
  limit?: number
}

/**
 * MinecraftLoader.icon
 */
export type MinecraftLoader$iconArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the File
   */
  select?: Prisma.FileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the File
   */
  omit?: Prisma.FileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FileInclude<ExtArgs> | null
  where?: Prisma.FileWhereInput
}

/**
 * MinecraftLoader.modFiles
 */
export type MinecraftLoader$modFilesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ModFile
   */
  select?: Prisma.ModFileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ModFile
   */
  omit?: Prisma.ModFileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ModFileInclude<ExtArgs> | null
  where?: Prisma.ModFileWhereInput
  orderBy?: Prisma.ModFileOrderByWithRelationInput | Prisma.ModFileOrderByWithRelationInput[]
  cursor?: Prisma.ModFileWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ModFileScalarFieldEnum | Prisma.ModFileScalarFieldEnum[]
}

/**
 * MinecraftLoader.shaderFiles
 */
export type MinecraftLoader$shaderFilesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ShaderFile
   */
  select?: Prisma.ShaderFileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ShaderFile
   */
  omit?: Prisma.ShaderFileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ShaderFileInclude<ExtArgs> | null
  where?: Prisma.ShaderFileWhereInput
  orderBy?: Prisma.ShaderFileOrderByWithRelationInput | Prisma.ShaderFileOrderByWithRelationInput[]
  cursor?: Prisma.ShaderFileWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ShaderFileScalarFieldEnum | Prisma.ShaderFileScalarFieldEnum[]
}

/**
 * MinecraftLoader.packVersions
 */
export type MinecraftLoader$packVersionsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PackVersion
   */
  select?: Prisma.PackVersionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PackVersion
   */
  omit?: Prisma.PackVersionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PackVersionInclude<ExtArgs> | null
  where?: Prisma.PackVersionWhereInput
  orderBy?: Prisma.PackVersionOrderByWithRelationInput | Prisma.PackVersionOrderByWithRelationInput[]
  cursor?: Prisma.PackVersionWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.PackVersionScalarFieldEnum | Prisma.PackVersionScalarFieldEnum[]
}

/**
 * MinecraftLoader without action
 */
export type MinecraftLoaderDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MinecraftLoader
   */
  select?: Prisma.MinecraftLoaderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MinecraftLoader
   */
  omit?: Prisma.MinecraftLoaderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MinecraftLoaderInclude<ExtArgs> | null
}
