
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `MinecraftVersion` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model MinecraftVersion
 * 
 */
export type MinecraftVersionModel = runtime.Types.Result.DefaultSelection<Prisma.$MinecraftVersionPayload>

export type AggregateMinecraftVersion = {
  _count: MinecraftVersionCountAggregateOutputType | null
  _avg: MinecraftVersionAvgAggregateOutputType | null
  _sum: MinecraftVersionSumAggregateOutputType | null
  _min: MinecraftVersionMinAggregateOutputType | null
  _max: MinecraftVersionMaxAggregateOutputType | null
}

export type MinecraftVersionAvgAggregateOutputType = {
  major: number | null
  minor: number | null
  patch: number | null
}

export type MinecraftVersionSumAggregateOutputType = {
  major: number | null
  minor: number | null
  patch: number | null
}

export type MinecraftVersionMinAggregateOutputType = {
  id: string | null
  major: number | null
  minor: number | null
  patch: number | null
}

export type MinecraftVersionMaxAggregateOutputType = {
  id: string | null
  major: number | null
  minor: number | null
  patch: number | null
}

export type MinecraftVersionCountAggregateOutputType = {
  id: number
  major: number
  minor: number
  patch: number
  _all: number
}


export type MinecraftVersionAvgAggregateInputType = {
  major?: true
  minor?: true
  patch?: true
}

export type MinecraftVersionSumAggregateInputType = {
  major?: true
  minor?: true
  patch?: true
}

export type MinecraftVersionMinAggregateInputType = {
  id?: true
  major?: true
  minor?: true
  patch?: true
}

export type MinecraftVersionMaxAggregateInputType = {
  id?: true
  major?: true
  minor?: true
  patch?: true
}

export type MinecraftVersionCountAggregateInputType = {
  id?: true
  major?: true
  minor?: true
  patch?: true
  _all?: true
}

export type MinecraftVersionAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which MinecraftVersion to aggregate.
   */
  where?: Prisma.MinecraftVersionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MinecraftVersions to fetch.
   */
  orderBy?: Prisma.MinecraftVersionOrderByWithRelationInput | Prisma.MinecraftVersionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.MinecraftVersionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MinecraftVersions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MinecraftVersions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned MinecraftVersions
  **/
  _count?: true | MinecraftVersionCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: MinecraftVersionAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: MinecraftVersionSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: MinecraftVersionMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: MinecraftVersionMaxAggregateInputType
}

export type GetMinecraftVersionAggregateType<T extends MinecraftVersionAggregateArgs> = {
      [P in keyof T & keyof AggregateMinecraftVersion]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateMinecraftVersion[P]>
    : Prisma.GetScalarType<T[P], AggregateMinecraftVersion[P]>
}




export type MinecraftVersionGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.MinecraftVersionWhereInput
  orderBy?: Prisma.MinecraftVersionOrderByWithAggregationInput | Prisma.MinecraftVersionOrderByWithAggregationInput[]
  by: Prisma.MinecraftVersionScalarFieldEnum[] | Prisma.MinecraftVersionScalarFieldEnum
  having?: Prisma.MinecraftVersionScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: MinecraftVersionCountAggregateInputType | true
  _avg?: MinecraftVersionAvgAggregateInputType
  _sum?: MinecraftVersionSumAggregateInputType
  _min?: MinecraftVersionMinAggregateInputType
  _max?: MinecraftVersionMaxAggregateInputType
}

export type MinecraftVersionGroupByOutputType = {
  id: string
  major: number
  minor: number
  patch: number
  _count: MinecraftVersionCountAggregateOutputType | null
  _avg: MinecraftVersionAvgAggregateOutputType | null
  _sum: MinecraftVersionSumAggregateOutputType | null
  _min: MinecraftVersionMinAggregateOutputType | null
  _max: MinecraftVersionMaxAggregateOutputType | null
}

export type GetMinecraftVersionGroupByPayload<T extends MinecraftVersionGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<MinecraftVersionGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof MinecraftVersionGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], MinecraftVersionGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], MinecraftVersionGroupByOutputType[P]>
      }
    >
  >



export type MinecraftVersionWhereInput = {
  AND?: Prisma.MinecraftVersionWhereInput | Prisma.MinecraftVersionWhereInput[]
  OR?: Prisma.MinecraftVersionWhereInput[]
  NOT?: Prisma.MinecraftVersionWhereInput | Prisma.MinecraftVersionWhereInput[]
  id?: Prisma.StringFilter<"MinecraftVersion"> | string
  major?: Prisma.IntFilter<"MinecraftVersion"> | number
  minor?: Prisma.IntFilter<"MinecraftVersion"> | number
  patch?: Prisma.IntFilter<"MinecraftVersion"> | number
  modFiles?: Prisma.ModFileListRelationFilter
  shaderFiles?: Prisma.ShaderFileListRelationFilter
  packVersions?: Prisma.PackVersionListRelationFilter
}

export type MinecraftVersionOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  major?: Prisma.SortOrder
  minor?: Prisma.SortOrder
  patch?: Prisma.SortOrder
  modFiles?: Prisma.ModFileOrderByRelationAggregateInput
  shaderFiles?: Prisma.ShaderFileOrderByRelationAggregateInput
  packVersions?: Prisma.PackVersionOrderByRelationAggregateInput
}

export type MinecraftVersionWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.MinecraftVersionWhereInput | Prisma.MinecraftVersionWhereInput[]
  OR?: Prisma.MinecraftVersionWhereInput[]
  NOT?: Prisma.MinecraftVersionWhereInput | Prisma.MinecraftVersionWhereInput[]
  major?: Prisma.IntFilter<"MinecraftVersion"> | number
  minor?: Prisma.IntFilter<"MinecraftVersion"> | number
  patch?: Prisma.IntFilter<"MinecraftVersion"> | number
  modFiles?: Prisma.ModFileListRelationFilter
  shaderFiles?: Prisma.ShaderFileListRelationFilter
  packVersions?: Prisma.PackVersionListRelationFilter
}, "id">

export type MinecraftVersionOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  major?: Prisma.SortOrder
  minor?: Prisma.SortOrder
  patch?: Prisma.SortOrder
  _count?: Prisma.MinecraftVersionCountOrderByAggregateInput
  _avg?: Prisma.MinecraftVersionAvgOrderByAggregateInput
  _max?: Prisma.MinecraftVersionMaxOrderByAggregateInput
  _min?: Prisma.MinecraftVersionMinOrderByAggregateInput
  _sum?: Prisma.MinecraftVersionSumOrderByAggregateInput
}

export type MinecraftVersionScalarWhereWithAggregatesInput = {
  AND?: Prisma.MinecraftVersionScalarWhereWithAggregatesInput | Prisma.MinecraftVersionScalarWhereWithAggregatesInput[]
  OR?: Prisma.MinecraftVersionScalarWhereWithAggregatesInput[]
  NOT?: Prisma.MinecraftVersionScalarWhereWithAggregatesInput | Prisma.MinecraftVersionScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"MinecraftVersion"> | string
  major?: Prisma.IntWithAggregatesFilter<"MinecraftVersion"> | number
  minor?: Prisma.IntWithAggregatesFilter<"MinecraftVersion"> | number
  patch?: Prisma.IntWithAggregatesFilter<"MinecraftVersion"> | number
}

export type MinecraftVersionCreateInput = {
  id?: string
  major: number
  minor: number
  patch: number
  modFiles?: Prisma.ModFileCreateNestedManyWithoutMinecraftVersionInput
  shaderFiles?: Prisma.ShaderFileCreateNestedManyWithoutMinecraftVersionInput
  packVersions?: Prisma.PackVersionCreateNestedManyWithoutMinecraftVersionInput
}

export type MinecraftVersionUncheckedCreateInput = {
  id?: string
  major: number
  minor: number
  patch: number
  modFiles?: Prisma.ModFileUncheckedCreateNestedManyWithoutMinecraftVersionInput
  shaderFiles?: Prisma.ShaderFileUncheckedCreateNestedManyWithoutMinecraftVersionInput
  packVersions?: Prisma.PackVersionUncheckedCreateNestedManyWithoutMinecraftVersionInput
}

export type MinecraftVersionUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  major?: Prisma.IntFieldUpdateOperationsInput | number
  minor?: Prisma.IntFieldUpdateOperationsInput | number
  patch?: Prisma.IntFieldUpdateOperationsInput | number
  modFiles?: Prisma.ModFileUpdateManyWithoutMinecraftVersionNestedInput
  shaderFiles?: Prisma.ShaderFileUpdateManyWithoutMinecraftVersionNestedInput
  packVersions?: Prisma.PackVersionUpdateManyWithoutMinecraftVersionNestedInput
}

export type MinecraftVersionUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  major?: Prisma.IntFieldUpdateOperationsInput | number
  minor?: Prisma.IntFieldUpdateOperationsInput | number
  patch?: Prisma.IntFieldUpdateOperationsInput | number
  modFiles?: Prisma.ModFileUncheckedUpdateManyWithoutMinecraftVersionNestedInput
  shaderFiles?: Prisma.ShaderFileUncheckedUpdateManyWithoutMinecraftVersionNestedInput
  packVersions?: Prisma.PackVersionUncheckedUpdateManyWithoutMinecraftVersionNestedInput
}

export type MinecraftVersionCreateManyInput = {
  id?: string
  major: number
  minor: number
  patch: number
}

export type MinecraftVersionUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  major?: Prisma.IntFieldUpdateOperationsInput | number
  minor?: Prisma.IntFieldUpdateOperationsInput | number
  patch?: Prisma.IntFieldUpdateOperationsInput | number
}

export type MinecraftVersionUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  major?: Prisma.IntFieldUpdateOperationsInput | number
  minor?: Prisma.IntFieldUpdateOperationsInput | number
  patch?: Prisma.IntFieldUpdateOperationsInput | number
}

export type MinecraftVersionCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  major?: Prisma.SortOrder
  minor?: Prisma.SortOrder
  patch?: Prisma.SortOrder
}

export type MinecraftVersionAvgOrderByAggregateInput = {
  major?: Prisma.SortOrder
  minor?: Prisma.SortOrder
  patch?: Prisma.SortOrder
}

export type MinecraftVersionMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  major?: Prisma.SortOrder
  minor?: Prisma.SortOrder
  patch?: Prisma.SortOrder
}

export type MinecraftVersionMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  major?: Prisma.SortOrder
  minor?: Prisma.SortOrder
  patch?: Prisma.SortOrder
}

export type MinecraftVersionSumOrderByAggregateInput = {
  major?: Prisma.SortOrder
  minor?: Prisma.SortOrder
  patch?: Prisma.SortOrder
}

export type MinecraftVersionScalarRelationFilter = {
  is?: Prisma.MinecraftVersionWhereInput
  isNot?: Prisma.MinecraftVersionWhereInput
}

export type MinecraftVersionCreateNestedOneWithoutModFilesInput = {
  create?: Prisma.XOR<Prisma.MinecraftVersionCreateWithoutModFilesInput, Prisma.MinecraftVersionUncheckedCreateWithoutModFilesInput>
  connectOrCreate?: Prisma.MinecraftVersionCreateOrConnectWithoutModFilesInput
  connect?: Prisma.MinecraftVersionWhereUniqueInput
}

export type MinecraftVersionUpdateOneRequiredWithoutModFilesNestedInput = {
  create?: Prisma.XOR<Prisma.MinecraftVersionCreateWithoutModFilesInput, Prisma.MinecraftVersionUncheckedCreateWithoutModFilesInput>
  connectOrCreate?: Prisma.MinecraftVersionCreateOrConnectWithoutModFilesInput
  upsert?: Prisma.MinecraftVersionUpsertWithoutModFilesInput
  connect?: Prisma.MinecraftVersionWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.MinecraftVersionUpdateToOneWithWhereWithoutModFilesInput, Prisma.MinecraftVersionUpdateWithoutModFilesInput>, Prisma.MinecraftVersionUncheckedUpdateWithoutModFilesInput>
}

export type MinecraftVersionCreateNestedOneWithoutShaderFilesInput = {
  create?: Prisma.XOR<Prisma.MinecraftVersionCreateWithoutShaderFilesInput, Prisma.MinecraftVersionUncheckedCreateWithoutShaderFilesInput>
  connectOrCreate?: Prisma.MinecraftVersionCreateOrConnectWithoutShaderFilesInput
  connect?: Prisma.MinecraftVersionWhereUniqueInput
}

export type MinecraftVersionUpdateOneRequiredWithoutShaderFilesNestedInput = {
  create?: Prisma.XOR<Prisma.MinecraftVersionCreateWithoutShaderFilesInput, Prisma.MinecraftVersionUncheckedCreateWithoutShaderFilesInput>
  connectOrCreate?: Prisma.MinecraftVersionCreateOrConnectWithoutShaderFilesInput
  upsert?: Prisma.MinecraftVersionUpsertWithoutShaderFilesInput
  connect?: Prisma.MinecraftVersionWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.MinecraftVersionUpdateToOneWithWhereWithoutShaderFilesInput, Prisma.MinecraftVersionUpdateWithoutShaderFilesInput>, Prisma.MinecraftVersionUncheckedUpdateWithoutShaderFilesInput>
}

export type MinecraftVersionCreateNestedOneWithoutPackVersionsInput = {
  create?: Prisma.XOR<Prisma.MinecraftVersionCreateWithoutPackVersionsInput, Prisma.MinecraftVersionUncheckedCreateWithoutPackVersionsInput>
  connectOrCreate?: Prisma.MinecraftVersionCreateOrConnectWithoutPackVersionsInput
  connect?: Prisma.MinecraftVersionWhereUniqueInput
}

export type MinecraftVersionUpdateOneRequiredWithoutPackVersionsNestedInput = {
  create?: Prisma.XOR<Prisma.MinecraftVersionCreateWithoutPackVersionsInput, Prisma.MinecraftVersionUncheckedCreateWithoutPackVersionsInput>
  connectOrCreate?: Prisma.MinecraftVersionCreateOrConnectWithoutPackVersionsInput
  upsert?: Prisma.MinecraftVersionUpsertWithoutPackVersionsInput
  connect?: Prisma.MinecraftVersionWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.MinecraftVersionUpdateToOneWithWhereWithoutPackVersionsInput, Prisma.MinecraftVersionUpdateWithoutPackVersionsInput>, Prisma.MinecraftVersionUncheckedUpdateWithoutPackVersionsInput>
}

export type MinecraftVersionCreateWithoutModFilesInput = {
  id?: string
  major: number
  minor: number
  patch: number
  shaderFiles?: Prisma.ShaderFileCreateNestedManyWithoutMinecraftVersionInput
  packVersions?: Prisma.PackVersionCreateNestedManyWithoutMinecraftVersionInput
}

export type MinecraftVersionUncheckedCreateWithoutModFilesInput = {
  id?: string
  major: number
  minor: number
  patch: number
  shaderFiles?: Prisma.ShaderFileUncheckedCreateNestedManyWithoutMinecraftVersionInput
  packVersions?: Prisma.PackVersionUncheckedCreateNestedManyWithoutMinecraftVersionInput
}

export type MinecraftVersionCreateOrConnectWithoutModFilesInput = {
  where: Prisma.MinecraftVersionWhereUniqueInput
  create: Prisma.XOR<Prisma.MinecraftVersionCreateWithoutModFilesInput, Prisma.MinecraftVersionUncheckedCreateWithoutModFilesInput>
}

export type MinecraftVersionUpsertWithoutModFilesInput = {
  update: Prisma.XOR<Prisma.MinecraftVersionUpdateWithoutModFilesInput, Prisma.MinecraftVersionUncheckedUpdateWithoutModFilesInput>
  create: Prisma.XOR<Prisma.MinecraftVersionCreateWithoutModFilesInput, Prisma.MinecraftVersionUncheckedCreateWithoutModFilesInput>
  where?: Prisma.MinecraftVersionWhereInput
}

export type MinecraftVersionUpdateToOneWithWhereWithoutModFilesInput = {
  where?: Prisma.MinecraftVersionWhereInput
  data: Prisma.XOR<Prisma.MinecraftVersionUpdateWithoutModFilesInput, Prisma.MinecraftVersionUncheckedUpdateWithoutModFilesInput>
}

export type MinecraftVersionUpdateWithoutModFilesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  major?: Prisma.IntFieldUpdateOperationsInput | number
  minor?: Prisma.IntFieldUpdateOperationsInput | number
  patch?: Prisma.IntFieldUpdateOperationsInput | number
  shaderFiles?: Prisma.ShaderFileUpdateManyWithoutMinecraftVersionNestedInput
  packVersions?: Prisma.PackVersionUpdateManyWithoutMinecraftVersionNestedInput
}

export type MinecraftVersionUncheckedUpdateWithoutModFilesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  major?: Prisma.IntFieldUpdateOperationsInput | number
  minor?: Prisma.IntFieldUpdateOperationsInput | number
  patch?: Prisma.IntFieldUpdateOperationsInput | number
  shaderFiles?: Prisma.ShaderFileUncheckedUpdateManyWithoutMinecraftVersionNestedInput
  packVersions?: Prisma.PackVersionUncheckedUpdateManyWithoutMinecraftVersionNestedInput
}

export type MinecraftVersionCreateWithoutShaderFilesInput = {
  id?: string
  major: number
  minor: number
  patch: number
  modFiles?: Prisma.ModFileCreateNestedManyWithoutMinecraftVersionInput
  packVersions?: Prisma.PackVersionCreateNestedManyWithoutMinecraftVersionInput
}

export type MinecraftVersionUncheckedCreateWithoutShaderFilesInput = {
  id?: string
  major: number
  minor: number
  patch: number
  modFiles?: Prisma.ModFileUncheckedCreateNestedManyWithoutMinecraftVersionInput
  packVersions?: Prisma.PackVersionUncheckedCreateNestedManyWithoutMinecraftVersionInput
}

export type MinecraftVersionCreateOrConnectWithoutShaderFilesInput = {
  where: Prisma.MinecraftVersionWhereUniqueInput
  create: Prisma.XOR<Prisma.MinecraftVersionCreateWithoutShaderFilesInput, Prisma.MinecraftVersionUncheckedCreateWithoutShaderFilesInput>
}

export type MinecraftVersionUpsertWithoutShaderFilesInput = {
  update: Prisma.XOR<Prisma.MinecraftVersionUpdateWithoutShaderFilesInput, Prisma.MinecraftVersionUncheckedUpdateWithoutShaderFilesInput>
  create: Prisma.XOR<Prisma.MinecraftVersionCreateWithoutShaderFilesInput, Prisma.MinecraftVersionUncheckedCreateWithoutShaderFilesInput>
  where?: Prisma.MinecraftVersionWhereInput
}

export type MinecraftVersionUpdateToOneWithWhereWithoutShaderFilesInput = {
  where?: Prisma.MinecraftVersionWhereInput
  data: Prisma.XOR<Prisma.MinecraftVersionUpdateWithoutShaderFilesInput, Prisma.MinecraftVersionUncheckedUpdateWithoutShaderFilesInput>
}

export type MinecraftVersionUpdateWithoutShaderFilesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  major?: Prisma.IntFieldUpdateOperationsInput | number
  minor?: Prisma.IntFieldUpdateOperationsInput | number
  patch?: Prisma.IntFieldUpdateOperationsInput | number
  modFiles?: Prisma.ModFileUpdateManyWithoutMinecraftVersionNestedInput
  packVersions?: Prisma.PackVersionUpdateManyWithoutMinecraftVersionNestedInput
}

export type MinecraftVersionUncheckedUpdateWithoutShaderFilesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  major?: Prisma.IntFieldUpdateOperationsInput | number
  minor?: Prisma.IntFieldUpdateOperationsInput | number
  patch?: Prisma.IntFieldUpdateOperationsInput | number
  modFiles?: Prisma.ModFileUncheckedUpdateManyWithoutMinecraftVersionNestedInput
  packVersions?: Prisma.PackVersionUncheckedUpdateManyWithoutMinecraftVersionNestedInput
}

export type MinecraftVersionCreateWithoutPackVersionsInput = {
  id?: string
  major: number
  minor: number
  patch: number
  modFiles?: Prisma.ModFileCreateNestedManyWithoutMinecraftVersionInput
  shaderFiles?: Prisma.ShaderFileCreateNestedManyWithoutMinecraftVersionInput
}

export type MinecraftVersionUncheckedCreateWithoutPackVersionsInput = {
  id?: string
  major: number
  minor: number
  patch: number
  modFiles?: Prisma.ModFileUncheckedCreateNestedManyWithoutMinecraftVersionInput
  shaderFiles?: Prisma.ShaderFileUncheckedCreateNestedManyWithoutMinecraftVersionInput
}

export type MinecraftVersionCreateOrConnectWithoutPackVersionsInput = {
  where: Prisma.MinecraftVersionWhereUniqueInput
  create: Prisma.XOR<Prisma.MinecraftVersionCreateWithoutPackVersionsInput, Prisma.MinecraftVersionUncheckedCreateWithoutPackVersionsInput>
}

export type MinecraftVersionUpsertWithoutPackVersionsInput = {
  update: Prisma.XOR<Prisma.MinecraftVersionUpdateWithoutPackVersionsInput, Prisma.MinecraftVersionUncheckedUpdateWithoutPackVersionsInput>
  create: Prisma.XOR<Prisma.MinecraftVersionCreateWithoutPackVersionsInput, Prisma.MinecraftVersionUncheckedCreateWithoutPackVersionsInput>
  where?: Prisma.MinecraftVersionWhereInput
}

export type MinecraftVersionUpdateToOneWithWhereWithoutPackVersionsInput = {
  where?: Prisma.MinecraftVersionWhereInput
  data: Prisma.XOR<Prisma.MinecraftVersionUpdateWithoutPackVersionsInput, Prisma.MinecraftVersionUncheckedUpdateWithoutPackVersionsInput>
}

export type MinecraftVersionUpdateWithoutPackVersionsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  major?: Prisma.IntFieldUpdateOperationsInput | number
  minor?: Prisma.IntFieldUpdateOperationsInput | number
  patch?: Prisma.IntFieldUpdateOperationsInput | number
  modFiles?: Prisma.ModFileUpdateManyWithoutMinecraftVersionNestedInput
  shaderFiles?: Prisma.ShaderFileUpdateManyWithoutMinecraftVersionNestedInput
}

export type MinecraftVersionUncheckedUpdateWithoutPackVersionsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  major?: Prisma.IntFieldUpdateOperationsInput | number
  minor?: Prisma.IntFieldUpdateOperationsInput | number
  patch?: Prisma.IntFieldUpdateOperationsInput | number
  modFiles?: Prisma.ModFileUncheckedUpdateManyWithoutMinecraftVersionNestedInput
  shaderFiles?: Prisma.ShaderFileUncheckedUpdateManyWithoutMinecraftVersionNestedInput
}


/**
 * Count Type MinecraftVersionCountOutputType
 */

export type MinecraftVersionCountOutputType = {
  modFiles: number
  shaderFiles: number
  packVersions: number
}

export type MinecraftVersionCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  modFiles?: boolean | MinecraftVersionCountOutputTypeCountModFilesArgs
  shaderFiles?: boolean | MinecraftVersionCountOutputTypeCountShaderFilesArgs
  packVersions?: boolean | MinecraftVersionCountOutputTypeCountPackVersionsArgs
}

/**
 * MinecraftVersionCountOutputType without action
 */
export type MinecraftVersionCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MinecraftVersionCountOutputType
   */
  select?: Prisma.MinecraftVersionCountOutputTypeSelect<ExtArgs> | null
}

/**
 * MinecraftVersionCountOutputType without action
 */
export type MinecraftVersionCountOutputTypeCountModFilesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ModFileWhereInput
}

/**
 * MinecraftVersionCountOutputType without action
 */
export type MinecraftVersionCountOutputTypeCountShaderFilesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ShaderFileWhereInput
}

/**
 * MinecraftVersionCountOutputType without action
 */
export type MinecraftVersionCountOutputTypeCountPackVersionsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PackVersionWhereInput
}


export type MinecraftVersionSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  major?: boolean
  minor?: boolean
  patch?: boolean
  modFiles?: boolean | Prisma.MinecraftVersion$modFilesArgs<ExtArgs>
  shaderFiles?: boolean | Prisma.MinecraftVersion$shaderFilesArgs<ExtArgs>
  packVersions?: boolean | Prisma.MinecraftVersion$packVersionsArgs<ExtArgs>
  _count?: boolean | Prisma.MinecraftVersionCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["minecraftVersion"]>

export type MinecraftVersionSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  major?: boolean
  minor?: boolean
  patch?: boolean
}, ExtArgs["result"]["minecraftVersion"]>

export type MinecraftVersionSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  major?: boolean
  minor?: boolean
  patch?: boolean
}, ExtArgs["result"]["minecraftVersion"]>

export type MinecraftVersionSelectScalar = {
  id?: boolean
  major?: boolean
  minor?: boolean
  patch?: boolean
}

export type MinecraftVersionOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "major" | "minor" | "patch", ExtArgs["result"]["minecraftVersion"]>
export type MinecraftVersionInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  modFiles?: boolean | Prisma.MinecraftVersion$modFilesArgs<ExtArgs>
  shaderFiles?: boolean | Prisma.MinecraftVersion$shaderFilesArgs<ExtArgs>
  packVersions?: boolean | Prisma.MinecraftVersion$packVersionsArgs<ExtArgs>
  _count?: boolean | Prisma.MinecraftVersionCountOutputTypeDefaultArgs<ExtArgs>
}
export type MinecraftVersionIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type MinecraftVersionIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $MinecraftVersionPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "MinecraftVersion"
  objects: {
    modFiles: Prisma.$ModFilePayload<ExtArgs>[]
    shaderFiles: Prisma.$ShaderFilePayload<ExtArgs>[]
    packVersions: Prisma.$PackVersionPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    major: number
    minor: number
    patch: number
  }, ExtArgs["result"]["minecraftVersion"]>
  composites: {}
}

export type MinecraftVersionGetPayload<S extends boolean | null | undefined | MinecraftVersionDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$MinecraftVersionPayload, S>

export type MinecraftVersionCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<MinecraftVersionFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: MinecraftVersionCountAggregateInputType | true
  }

export interface MinecraftVersionDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['MinecraftVersion'], meta: { name: 'MinecraftVersion' } }
  /**
   * Find zero or one MinecraftVersion that matches the filter.
   * @param {MinecraftVersionFindUniqueArgs} args - Arguments to find a MinecraftVersion
   * @example
   * // Get one MinecraftVersion
   * const minecraftVersion = await prisma.minecraftVersion.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends MinecraftVersionFindUniqueArgs>(args: Prisma.SelectSubset<T, MinecraftVersionFindUniqueArgs<ExtArgs>>): Prisma.Prisma__MinecraftVersionClient<runtime.Types.Result.GetResult<Prisma.$MinecraftVersionPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one MinecraftVersion that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {MinecraftVersionFindUniqueOrThrowArgs} args - Arguments to find a MinecraftVersion
   * @example
   * // Get one MinecraftVersion
   * const minecraftVersion = await prisma.minecraftVersion.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends MinecraftVersionFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, MinecraftVersionFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__MinecraftVersionClient<runtime.Types.Result.GetResult<Prisma.$MinecraftVersionPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first MinecraftVersion that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MinecraftVersionFindFirstArgs} args - Arguments to find a MinecraftVersion
   * @example
   * // Get one MinecraftVersion
   * const minecraftVersion = await prisma.minecraftVersion.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends MinecraftVersionFindFirstArgs>(args?: Prisma.SelectSubset<T, MinecraftVersionFindFirstArgs<ExtArgs>>): Prisma.Prisma__MinecraftVersionClient<runtime.Types.Result.GetResult<Prisma.$MinecraftVersionPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first MinecraftVersion that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MinecraftVersionFindFirstOrThrowArgs} args - Arguments to find a MinecraftVersion
   * @example
   * // Get one MinecraftVersion
   * const minecraftVersion = await prisma.minecraftVersion.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends MinecraftVersionFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, MinecraftVersionFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__MinecraftVersionClient<runtime.Types.Result.GetResult<Prisma.$MinecraftVersionPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more MinecraftVersions that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MinecraftVersionFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all MinecraftVersions
   * const minecraftVersions = await prisma.minecraftVersion.findMany()
   * 
   * // Get first 10 MinecraftVersions
   * const minecraftVersions = await prisma.minecraftVersion.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const minecraftVersionWithIdOnly = await prisma.minecraftVersion.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends MinecraftVersionFindManyArgs>(args?: Prisma.SelectSubset<T, MinecraftVersionFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MinecraftVersionPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a MinecraftVersion.
   * @param {MinecraftVersionCreateArgs} args - Arguments to create a MinecraftVersion.
   * @example
   * // Create one MinecraftVersion
   * const MinecraftVersion = await prisma.minecraftVersion.create({
   *   data: {
   *     // ... data to create a MinecraftVersion
   *   }
   * })
   * 
   */
  create<T extends MinecraftVersionCreateArgs>(args: Prisma.SelectSubset<T, MinecraftVersionCreateArgs<ExtArgs>>): Prisma.Prisma__MinecraftVersionClient<runtime.Types.Result.GetResult<Prisma.$MinecraftVersionPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many MinecraftVersions.
   * @param {MinecraftVersionCreateManyArgs} args - Arguments to create many MinecraftVersions.
   * @example
   * // Create many MinecraftVersions
   * const minecraftVersion = await prisma.minecraftVersion.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends MinecraftVersionCreateManyArgs>(args?: Prisma.SelectSubset<T, MinecraftVersionCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many MinecraftVersions and returns the data saved in the database.
   * @param {MinecraftVersionCreateManyAndReturnArgs} args - Arguments to create many MinecraftVersions.
   * @example
   * // Create many MinecraftVersions
   * const minecraftVersion = await prisma.minecraftVersion.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many MinecraftVersions and only return the `id`
   * const minecraftVersionWithIdOnly = await prisma.minecraftVersion.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends MinecraftVersionCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, MinecraftVersionCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MinecraftVersionPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a MinecraftVersion.
   * @param {MinecraftVersionDeleteArgs} args - Arguments to delete one MinecraftVersion.
   * @example
   * // Delete one MinecraftVersion
   * const MinecraftVersion = await prisma.minecraftVersion.delete({
   *   where: {
   *     // ... filter to delete one MinecraftVersion
   *   }
   * })
   * 
   */
  delete<T extends MinecraftVersionDeleteArgs>(args: Prisma.SelectSubset<T, MinecraftVersionDeleteArgs<ExtArgs>>): Prisma.Prisma__MinecraftVersionClient<runtime.Types.Result.GetResult<Prisma.$MinecraftVersionPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one MinecraftVersion.
   * @param {MinecraftVersionUpdateArgs} args - Arguments to update one MinecraftVersion.
   * @example
   * // Update one MinecraftVersion
   * const minecraftVersion = await prisma.minecraftVersion.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends MinecraftVersionUpdateArgs>(args: Prisma.SelectSubset<T, MinecraftVersionUpdateArgs<ExtArgs>>): Prisma.Prisma__MinecraftVersionClient<runtime.Types.Result.GetResult<Prisma.$MinecraftVersionPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more MinecraftVersions.
   * @param {MinecraftVersionDeleteManyArgs} args - Arguments to filter MinecraftVersions to delete.
   * @example
   * // Delete a few MinecraftVersions
   * const { count } = await prisma.minecraftVersion.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends MinecraftVersionDeleteManyArgs>(args?: Prisma.SelectSubset<T, MinecraftVersionDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more MinecraftVersions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MinecraftVersionUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many MinecraftVersions
   * const minecraftVersion = await prisma.minecraftVersion.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends MinecraftVersionUpdateManyArgs>(args: Prisma.SelectSubset<T, MinecraftVersionUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more MinecraftVersions and returns the data updated in the database.
   * @param {MinecraftVersionUpdateManyAndReturnArgs} args - Arguments to update many MinecraftVersions.
   * @example
   * // Update many MinecraftVersions
   * const minecraftVersion = await prisma.minecraftVersion.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more MinecraftVersions and only return the `id`
   * const minecraftVersionWithIdOnly = await prisma.minecraftVersion.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends MinecraftVersionUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, MinecraftVersionUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MinecraftVersionPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one MinecraftVersion.
   * @param {MinecraftVersionUpsertArgs} args - Arguments to update or create a MinecraftVersion.
   * @example
   * // Update or create a MinecraftVersion
   * const minecraftVersion = await prisma.minecraftVersion.upsert({
   *   create: {
   *     // ... data to create a MinecraftVersion
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the MinecraftVersion we want to update
   *   }
   * })
   */
  upsert<T extends MinecraftVersionUpsertArgs>(args: Prisma.SelectSubset<T, MinecraftVersionUpsertArgs<ExtArgs>>): Prisma.Prisma__MinecraftVersionClient<runtime.Types.Result.GetResult<Prisma.$MinecraftVersionPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of MinecraftVersions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MinecraftVersionCountArgs} args - Arguments to filter MinecraftVersions to count.
   * @example
   * // Count the number of MinecraftVersions
   * const count = await prisma.minecraftVersion.count({
   *   where: {
   *     // ... the filter for the MinecraftVersions we want to count
   *   }
   * })
  **/
  count<T extends MinecraftVersionCountArgs>(
    args?: Prisma.Subset<T, MinecraftVersionCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], MinecraftVersionCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a MinecraftVersion.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MinecraftVersionAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends MinecraftVersionAggregateArgs>(args: Prisma.Subset<T, MinecraftVersionAggregateArgs>): Prisma.PrismaPromise<GetMinecraftVersionAggregateType<T>>

  /**
   * Group by MinecraftVersion.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MinecraftVersionGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends MinecraftVersionGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: MinecraftVersionGroupByArgs['orderBy'] }
      : { orderBy?: MinecraftVersionGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, MinecraftVersionGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetMinecraftVersionGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the MinecraftVersion model
 */
readonly fields: MinecraftVersionFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for MinecraftVersion.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__MinecraftVersionClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  modFiles<T extends Prisma.MinecraftVersion$modFilesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.MinecraftVersion$modFilesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ModFilePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  shaderFiles<T extends Prisma.MinecraftVersion$shaderFilesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.MinecraftVersion$shaderFilesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ShaderFilePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  packVersions<T extends Prisma.MinecraftVersion$packVersionsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.MinecraftVersion$packVersionsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PackVersionPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the MinecraftVersion model
 */
export interface MinecraftVersionFieldRefs {
  readonly id: Prisma.FieldRef<"MinecraftVersion", 'String'>
  readonly major: Prisma.FieldRef<"MinecraftVersion", 'Int'>
  readonly minor: Prisma.FieldRef<"MinecraftVersion", 'Int'>
  readonly patch: Prisma.FieldRef<"MinecraftVersion", 'Int'>
}
    

// Custom InputTypes
/**
 * MinecraftVersion findUnique
 */
export type MinecraftVersionFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MinecraftVersion
   */
  select?: Prisma.MinecraftVersionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MinecraftVersion
   */
  omit?: Prisma.MinecraftVersionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MinecraftVersionInclude<ExtArgs> | null
  /**
   * Filter, which MinecraftVersion to fetch.
   */
  where: Prisma.MinecraftVersionWhereUniqueInput
}

/**
 * MinecraftVersion findUniqueOrThrow
 */
export type MinecraftVersionFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MinecraftVersion
   */
  select?: Prisma.MinecraftVersionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MinecraftVersion
   */
  omit?: Prisma.MinecraftVersionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MinecraftVersionInclude<ExtArgs> | null
  /**
   * Filter, which MinecraftVersion to fetch.
   */
  where: Prisma.MinecraftVersionWhereUniqueInput
}

/**
 * MinecraftVersion findFirst
 */
export type MinecraftVersionFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MinecraftVersion
   */
  select?: Prisma.MinecraftVersionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MinecraftVersion
   */
  omit?: Prisma.MinecraftVersionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MinecraftVersionInclude<ExtArgs> | null
  /**
   * Filter, which MinecraftVersion to fetch.
   */
  where?: Prisma.MinecraftVersionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MinecraftVersions to fetch.
   */
  orderBy?: Prisma.MinecraftVersionOrderByWithRelationInput | Prisma.MinecraftVersionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for MinecraftVersions.
   */
  cursor?: Prisma.MinecraftVersionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MinecraftVersions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MinecraftVersions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of MinecraftVersions.
   */
  distinct?: Prisma.MinecraftVersionScalarFieldEnum | Prisma.MinecraftVersionScalarFieldEnum[]
}

/**
 * MinecraftVersion findFirstOrThrow
 */
export type MinecraftVersionFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MinecraftVersion
   */
  select?: Prisma.MinecraftVersionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MinecraftVersion
   */
  omit?: Prisma.MinecraftVersionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MinecraftVersionInclude<ExtArgs> | null
  /**
   * Filter, which MinecraftVersion to fetch.
   */
  where?: Prisma.MinecraftVersionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MinecraftVersions to fetch.
   */
  orderBy?: Prisma.MinecraftVersionOrderByWithRelationInput | Prisma.MinecraftVersionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for MinecraftVersions.
   */
  cursor?: Prisma.MinecraftVersionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MinecraftVersions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MinecraftVersions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of MinecraftVersions.
   */
  distinct?: Prisma.MinecraftVersionScalarFieldEnum | Prisma.MinecraftVersionScalarFieldEnum[]
}

/**
 * MinecraftVersion findMany
 */
export type MinecraftVersionFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MinecraftVersion
   */
  select?: Prisma.MinecraftVersionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MinecraftVersion
   */
  omit?: Prisma.MinecraftVersionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MinecraftVersionInclude<ExtArgs> | null
  /**
   * Filter, which MinecraftVersions to fetch.
   */
  where?: Prisma.MinecraftVersionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MinecraftVersions to fetch.
   */
  orderBy?: Prisma.MinecraftVersionOrderByWithRelationInput | Prisma.MinecraftVersionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing MinecraftVersions.
   */
  cursor?: Prisma.MinecraftVersionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MinecraftVersions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MinecraftVersions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of MinecraftVersions.
   */
  distinct?: Prisma.MinecraftVersionScalarFieldEnum | Prisma.MinecraftVersionScalarFieldEnum[]
}

/**
 * MinecraftVersion create
 */
export type MinecraftVersionCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MinecraftVersion
   */
  select?: Prisma.MinecraftVersionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MinecraftVersion
   */
  omit?: Prisma.MinecraftVersionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MinecraftVersionInclude<ExtArgs> | null
  /**
   * The data needed to create a MinecraftVersion.
   */
  data: Prisma.XOR<Prisma.MinecraftVersionCreateInput, Prisma.MinecraftVersionUncheckedCreateInput>
}

/**
 * MinecraftVersion createMany
 */
export type MinecraftVersionCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many MinecraftVersions.
   */
  data: Prisma.MinecraftVersionCreateManyInput | Prisma.MinecraftVersionCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * MinecraftVersion createManyAndReturn
 */
export type MinecraftVersionCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MinecraftVersion
   */
  select?: Prisma.MinecraftVersionSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the MinecraftVersion
   */
  omit?: Prisma.MinecraftVersionOmit<ExtArgs> | null
  /**
   * The data used to create many MinecraftVersions.
   */
  data: Prisma.MinecraftVersionCreateManyInput | Prisma.MinecraftVersionCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * MinecraftVersion update
 */
export type MinecraftVersionUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MinecraftVersion
   */
  select?: Prisma.MinecraftVersionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MinecraftVersion
   */
  omit?: Prisma.MinecraftVersionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MinecraftVersionInclude<ExtArgs> | null
  /**
   * The data needed to update a MinecraftVersion.
   */
  data: Prisma.XOR<Prisma.MinecraftVersionUpdateInput, Prisma.MinecraftVersionUncheckedUpdateInput>
  /**
   * Choose, which MinecraftVersion to update.
   */
  where: Prisma.MinecraftVersionWhereUniqueInput
}

/**
 * MinecraftVersion updateMany
 */
export type MinecraftVersionUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update MinecraftVersions.
   */
  data: Prisma.XOR<Prisma.MinecraftVersionUpdateManyMutationInput, Prisma.MinecraftVersionUncheckedUpdateManyInput>
  /**
   * Filter which MinecraftVersions to update
   */
  where?: Prisma.MinecraftVersionWhereInput
  /**
   * Limit how many MinecraftVersions to update.
   */
  limit?: number
}

/**
 * MinecraftVersion updateManyAndReturn
 */
export type MinecraftVersionUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MinecraftVersion
   */
  select?: Prisma.MinecraftVersionSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the MinecraftVersion
   */
  omit?: Prisma.MinecraftVersionOmit<ExtArgs> | null
  /**
   * The data used to update MinecraftVersions.
   */
  data: Prisma.XOR<Prisma.MinecraftVersionUpdateManyMutationInput, Prisma.MinecraftVersionUncheckedUpdateManyInput>
  /**
   * Filter which MinecraftVersions to update
   */
  where?: Prisma.MinecraftVersionWhereInput
  /**
   * Limit how many MinecraftVersions to update.
   */
  limit?: number
}

/**
 * MinecraftVersion upsert
 */
export type MinecraftVersionUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MinecraftVersion
   */
  select?: Prisma.MinecraftVersionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MinecraftVersion
   */
  omit?: Prisma.MinecraftVersionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MinecraftVersionInclude<ExtArgs> | null
  /**
   * The filter to search for the MinecraftVersion to update in case it exists.
   */
  where: Prisma.MinecraftVersionWhereUniqueInput
  /**
   * In case the MinecraftVersion found by the `where` argument doesn't exist, create a new MinecraftVersion with this data.
   */
  create: Prisma.XOR<Prisma.MinecraftVersionCreateInput, Prisma.MinecraftVersionUncheckedCreateInput>
  /**
   * In case the MinecraftVersion was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.MinecraftVersionUpdateInput, Prisma.MinecraftVersionUncheckedUpdateInput>
}

/**
 * MinecraftVersion delete
 */
export type MinecraftVersionDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MinecraftVersion
   */
  select?: Prisma.MinecraftVersionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MinecraftVersion
   */
  omit?: Prisma.MinecraftVersionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MinecraftVersionInclude<ExtArgs> | null
  /**
   * Filter which MinecraftVersion to delete.
   */
  where: Prisma.MinecraftVersionWhereUniqueInput
}

/**
 * MinecraftVersion deleteMany
 */
export type MinecraftVersionDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which MinecraftVersions to delete
   */
  where?: Prisma.MinecraftVersionWhereInput
  /**
   * Limit how many MinecraftVersions to delete.
   */
  limit?: number
}

/**
 * MinecraftVersion.modFiles
 */
export type MinecraftVersion$modFilesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ModFile
   */
  select?: Prisma.ModFileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ModFile
   */
  omit?: Prisma.ModFileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ModFileInclude<ExtArgs> | null
  where?: Prisma.ModFileWhereInput
  orderBy?: Prisma.ModFileOrderByWithRelationInput | Prisma.ModFileOrderByWithRelationInput[]
  cursor?: Prisma.ModFileWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ModFileScalarFieldEnum | Prisma.ModFileScalarFieldEnum[]
}

/**
 * MinecraftVersion.shaderFiles
 */
export type MinecraftVersion$shaderFilesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ShaderFile
   */
  select?: Prisma.ShaderFileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ShaderFile
   */
  omit?: Prisma.ShaderFileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ShaderFileInclude<ExtArgs> | null
  where?: Prisma.ShaderFileWhereInput
  orderBy?: Prisma.ShaderFileOrderByWithRelationInput | Prisma.ShaderFileOrderByWithRelationInput[]
  cursor?: Prisma.ShaderFileWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ShaderFileScalarFieldEnum | Prisma.ShaderFileScalarFieldEnum[]
}

/**
 * MinecraftVersion.packVersions
 */
export type MinecraftVersion$packVersionsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PackVersion
   */
  select?: Prisma.PackVersionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PackVersion
   */
  omit?: Prisma.PackVersionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PackVersionInclude<ExtArgs> | null
  where?: Prisma.PackVersionWhereInput
  orderBy?: Prisma.PackVersionOrderByWithRelationInput | Prisma.PackVersionOrderByWithRelationInput[]
  cursor?: Prisma.PackVersionWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.PackVersionScalarFieldEnum | Prisma.PackVersionScalarFieldEnum[]
}

/**
 * MinecraftVersion without action
 */
export type MinecraftVersionDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MinecraftVersion
   */
  select?: Prisma.MinecraftVersionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MinecraftVersion
   */
  omit?: Prisma.MinecraftVersionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MinecraftVersionInclude<ExtArgs> | null
}
