
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ModDependency` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model ModDependency
 * 
 */
export type ModDependencyModel = runtime.Types.Result.DefaultSelection<Prisma.$ModDependencyPayload>

export type AggregateModDependency = {
  _count: ModDependencyCountAggregateOutputType | null
  _min: ModDependencyMinAggregateOutputType | null
  _max: ModDependencyMaxAggregateOutputType | null
}

export type ModDependencyMinAggregateOutputType = {
  id: string | null
  modId: string | null
  dependencyModId: string | null
  createdAt: Date | null
  updatedAt: Date | null
  minVersion: string | null
  maxVersion: string | null
  rol: $Enums.ModDependencyRol | null
}

export type ModDependencyMaxAggregateOutputType = {
  id: string | null
  modId: string | null
  dependencyModId: string | null
  createdAt: Date | null
  updatedAt: Date | null
  minVersion: string | null
  maxVersion: string | null
  rol: $Enums.ModDependencyRol | null
}

export type ModDependencyCountAggregateOutputType = {
  id: number
  modId: number
  dependencyModId: number
  createdAt: number
  updatedAt: number
  minVersion: number
  maxVersion: number
  rol: number
  _all: number
}


export type ModDependencyMinAggregateInputType = {
  id?: true
  modId?: true
  dependencyModId?: true
  createdAt?: true
  updatedAt?: true
  minVersion?: true
  maxVersion?: true
  rol?: true
}

export type ModDependencyMaxAggregateInputType = {
  id?: true
  modId?: true
  dependencyModId?: true
  createdAt?: true
  updatedAt?: true
  minVersion?: true
  maxVersion?: true
  rol?: true
}

export type ModDependencyCountAggregateInputType = {
  id?: true
  modId?: true
  dependencyModId?: true
  createdAt?: true
  updatedAt?: true
  minVersion?: true
  maxVersion?: true
  rol?: true
  _all?: true
}

export type ModDependencyAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ModDependency to aggregate.
   */
  where?: Prisma.ModDependencyWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ModDependencies to fetch.
   */
  orderBy?: Prisma.ModDependencyOrderByWithRelationInput | Prisma.ModDependencyOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ModDependencyWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ModDependencies from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ModDependencies.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ModDependencies
  **/
  _count?: true | ModDependencyCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ModDependencyMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ModDependencyMaxAggregateInputType
}

export type GetModDependencyAggregateType<T extends ModDependencyAggregateArgs> = {
      [P in keyof T & keyof AggregateModDependency]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateModDependency[P]>
    : Prisma.GetScalarType<T[P], AggregateModDependency[P]>
}




export type ModDependencyGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ModDependencyWhereInput
  orderBy?: Prisma.ModDependencyOrderByWithAggregationInput | Prisma.ModDependencyOrderByWithAggregationInput[]
  by: Prisma.ModDependencyScalarFieldEnum[] | Prisma.ModDependencyScalarFieldEnum
  having?: Prisma.ModDependencyScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ModDependencyCountAggregateInputType | true
  _min?: ModDependencyMinAggregateInputType
  _max?: ModDependencyMaxAggregateInputType
}

export type ModDependencyGroupByOutputType = {
  id: string
  modId: string
  dependencyModId: string
  createdAt: Date
  updatedAt: Date
  minVersion: string
  maxVersion: string
  rol: $Enums.ModDependencyRol
  _count: ModDependencyCountAggregateOutputType | null
  _min: ModDependencyMinAggregateOutputType | null
  _max: ModDependencyMaxAggregateOutputType | null
}

export type GetModDependencyGroupByPayload<T extends ModDependencyGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ModDependencyGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ModDependencyGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ModDependencyGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ModDependencyGroupByOutputType[P]>
      }
    >
  >



export type ModDependencyWhereInput = {
  AND?: Prisma.ModDependencyWhereInput | Prisma.ModDependencyWhereInput[]
  OR?: Prisma.ModDependencyWhereInput[]
  NOT?: Prisma.ModDependencyWhereInput | Prisma.ModDependencyWhereInput[]
  id?: Prisma.StringFilter<"ModDependency"> | string
  modId?: Prisma.StringFilter<"ModDependency"> | string
  dependencyModId?: Prisma.StringFilter<"ModDependency"> | string
  createdAt?: Prisma.DateTimeFilter<"ModDependency"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"ModDependency"> | Date | string
  minVersion?: Prisma.StringFilter<"ModDependency"> | string
  maxVersion?: Prisma.StringFilter<"ModDependency"> | string
  rol?: Prisma.EnumModDependencyRolFilter<"ModDependency"> | $Enums.ModDependencyRol
  mod?: Prisma.XOR<Prisma.ModScalarRelationFilter, Prisma.ModWhereInput>
  dependencyMod?: Prisma.XOR<Prisma.ModScalarRelationFilter, Prisma.ModWhereInput>
}

export type ModDependencyOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  modId?: Prisma.SortOrder
  dependencyModId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  minVersion?: Prisma.SortOrder
  maxVersion?: Prisma.SortOrder
  rol?: Prisma.SortOrder
  mod?: Prisma.ModOrderByWithRelationInput
  dependencyMod?: Prisma.ModOrderByWithRelationInput
}

export type ModDependencyWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.ModDependencyWhereInput | Prisma.ModDependencyWhereInput[]
  OR?: Prisma.ModDependencyWhereInput[]
  NOT?: Prisma.ModDependencyWhereInput | Prisma.ModDependencyWhereInput[]
  modId?: Prisma.StringFilter<"ModDependency"> | string
  dependencyModId?: Prisma.StringFilter<"ModDependency"> | string
  createdAt?: Prisma.DateTimeFilter<"ModDependency"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"ModDependency"> | Date | string
  minVersion?: Prisma.StringFilter<"ModDependency"> | string
  maxVersion?: Prisma.StringFilter<"ModDependency"> | string
  rol?: Prisma.EnumModDependencyRolFilter<"ModDependency"> | $Enums.ModDependencyRol
  mod?: Prisma.XOR<Prisma.ModScalarRelationFilter, Prisma.ModWhereInput>
  dependencyMod?: Prisma.XOR<Prisma.ModScalarRelationFilter, Prisma.ModWhereInput>
}, "id">

export type ModDependencyOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  modId?: Prisma.SortOrder
  dependencyModId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  minVersion?: Prisma.SortOrder
  maxVersion?: Prisma.SortOrder
  rol?: Prisma.SortOrder
  _count?: Prisma.ModDependencyCountOrderByAggregateInput
  _max?: Prisma.ModDependencyMaxOrderByAggregateInput
  _min?: Prisma.ModDependencyMinOrderByAggregateInput
}

export type ModDependencyScalarWhereWithAggregatesInput = {
  AND?: Prisma.ModDependencyScalarWhereWithAggregatesInput | Prisma.ModDependencyScalarWhereWithAggregatesInput[]
  OR?: Prisma.ModDependencyScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ModDependencyScalarWhereWithAggregatesInput | Prisma.ModDependencyScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"ModDependency"> | string
  modId?: Prisma.StringWithAggregatesFilter<"ModDependency"> | string
  dependencyModId?: Prisma.StringWithAggregatesFilter<"ModDependency"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"ModDependency"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"ModDependency"> | Date | string
  minVersion?: Prisma.StringWithAggregatesFilter<"ModDependency"> | string
  maxVersion?: Prisma.StringWithAggregatesFilter<"ModDependency"> | string
  rol?: Prisma.EnumModDependencyRolWithAggregatesFilter<"ModDependency"> | $Enums.ModDependencyRol
}

export type ModDependencyCreateInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  minVersion: string
  maxVersion: string
  rol?: $Enums.ModDependencyRol
  mod: Prisma.ModCreateNestedOneWithoutModDependenciesFromInput
  dependencyMod: Prisma.ModCreateNestedOneWithoutModDependenciesToInput
}

export type ModDependencyUncheckedCreateInput = {
  id?: string
  modId: string
  dependencyModId: string
  createdAt?: Date | string
  updatedAt?: Date | string
  minVersion: string
  maxVersion: string
  rol?: $Enums.ModDependencyRol
}

export type ModDependencyUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  minVersion?: Prisma.StringFieldUpdateOperationsInput | string
  maxVersion?: Prisma.StringFieldUpdateOperationsInput | string
  rol?: Prisma.EnumModDependencyRolFieldUpdateOperationsInput | $Enums.ModDependencyRol
  mod?: Prisma.ModUpdateOneRequiredWithoutModDependenciesFromNestedInput
  dependencyMod?: Prisma.ModUpdateOneRequiredWithoutModDependenciesToNestedInput
}

export type ModDependencyUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  modId?: Prisma.StringFieldUpdateOperationsInput | string
  dependencyModId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  minVersion?: Prisma.StringFieldUpdateOperationsInput | string
  maxVersion?: Prisma.StringFieldUpdateOperationsInput | string
  rol?: Prisma.EnumModDependencyRolFieldUpdateOperationsInput | $Enums.ModDependencyRol
}

export type ModDependencyCreateManyInput = {
  id?: string
  modId: string
  dependencyModId: string
  createdAt?: Date | string
  updatedAt?: Date | string
  minVersion: string
  maxVersion: string
  rol?: $Enums.ModDependencyRol
}

export type ModDependencyUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  minVersion?: Prisma.StringFieldUpdateOperationsInput | string
  maxVersion?: Prisma.StringFieldUpdateOperationsInput | string
  rol?: Prisma.EnumModDependencyRolFieldUpdateOperationsInput | $Enums.ModDependencyRol
}

export type ModDependencyUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  modId?: Prisma.StringFieldUpdateOperationsInput | string
  dependencyModId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  minVersion?: Prisma.StringFieldUpdateOperationsInput | string
  maxVersion?: Prisma.StringFieldUpdateOperationsInput | string
  rol?: Prisma.EnumModDependencyRolFieldUpdateOperationsInput | $Enums.ModDependencyRol
}

export type ModDependencyListRelationFilter = {
  every?: Prisma.ModDependencyWhereInput
  some?: Prisma.ModDependencyWhereInput
  none?: Prisma.ModDependencyWhereInput
}

export type ModDependencyOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type ModDependencyCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  modId?: Prisma.SortOrder
  dependencyModId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  minVersion?: Prisma.SortOrder
  maxVersion?: Prisma.SortOrder
  rol?: Prisma.SortOrder
}

export type ModDependencyMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  modId?: Prisma.SortOrder
  dependencyModId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  minVersion?: Prisma.SortOrder
  maxVersion?: Prisma.SortOrder
  rol?: Prisma.SortOrder
}

export type ModDependencyMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  modId?: Prisma.SortOrder
  dependencyModId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  minVersion?: Prisma.SortOrder
  maxVersion?: Prisma.SortOrder
  rol?: Prisma.SortOrder
}

export type ModDependencyCreateNestedManyWithoutModInput = {
  create?: Prisma.XOR<Prisma.ModDependencyCreateWithoutModInput, Prisma.ModDependencyUncheckedCreateWithoutModInput> | Prisma.ModDependencyCreateWithoutModInput[] | Prisma.ModDependencyUncheckedCreateWithoutModInput[]
  connectOrCreate?: Prisma.ModDependencyCreateOrConnectWithoutModInput | Prisma.ModDependencyCreateOrConnectWithoutModInput[]
  createMany?: Prisma.ModDependencyCreateManyModInputEnvelope
  connect?: Prisma.ModDependencyWhereUniqueInput | Prisma.ModDependencyWhereUniqueInput[]
}

export type ModDependencyCreateNestedManyWithoutDependencyModInput = {
  create?: Prisma.XOR<Prisma.ModDependencyCreateWithoutDependencyModInput, Prisma.ModDependencyUncheckedCreateWithoutDependencyModInput> | Prisma.ModDependencyCreateWithoutDependencyModInput[] | Prisma.ModDependencyUncheckedCreateWithoutDependencyModInput[]
  connectOrCreate?: Prisma.ModDependencyCreateOrConnectWithoutDependencyModInput | Prisma.ModDependencyCreateOrConnectWithoutDependencyModInput[]
  createMany?: Prisma.ModDependencyCreateManyDependencyModInputEnvelope
  connect?: Prisma.ModDependencyWhereUniqueInput | Prisma.ModDependencyWhereUniqueInput[]
}

export type ModDependencyUncheckedCreateNestedManyWithoutModInput = {
  create?: Prisma.XOR<Prisma.ModDependencyCreateWithoutModInput, Prisma.ModDependencyUncheckedCreateWithoutModInput> | Prisma.ModDependencyCreateWithoutModInput[] | Prisma.ModDependencyUncheckedCreateWithoutModInput[]
  connectOrCreate?: Prisma.ModDependencyCreateOrConnectWithoutModInput | Prisma.ModDependencyCreateOrConnectWithoutModInput[]
  createMany?: Prisma.ModDependencyCreateManyModInputEnvelope
  connect?: Prisma.ModDependencyWhereUniqueInput | Prisma.ModDependencyWhereUniqueInput[]
}

export type ModDependencyUncheckedCreateNestedManyWithoutDependencyModInput = {
  create?: Prisma.XOR<Prisma.ModDependencyCreateWithoutDependencyModInput, Prisma.ModDependencyUncheckedCreateWithoutDependencyModInput> | Prisma.ModDependencyCreateWithoutDependencyModInput[] | Prisma.ModDependencyUncheckedCreateWithoutDependencyModInput[]
  connectOrCreate?: Prisma.ModDependencyCreateOrConnectWithoutDependencyModInput | Prisma.ModDependencyCreateOrConnectWithoutDependencyModInput[]
  createMany?: Prisma.ModDependencyCreateManyDependencyModInputEnvelope
  connect?: Prisma.ModDependencyWhereUniqueInput | Prisma.ModDependencyWhereUniqueInput[]
}

export type ModDependencyUpdateManyWithoutModNestedInput = {
  create?: Prisma.XOR<Prisma.ModDependencyCreateWithoutModInput, Prisma.ModDependencyUncheckedCreateWithoutModInput> | Prisma.ModDependencyCreateWithoutModInput[] | Prisma.ModDependencyUncheckedCreateWithoutModInput[]
  connectOrCreate?: Prisma.ModDependencyCreateOrConnectWithoutModInput | Prisma.ModDependencyCreateOrConnectWithoutModInput[]
  upsert?: Prisma.ModDependencyUpsertWithWhereUniqueWithoutModInput | Prisma.ModDependencyUpsertWithWhereUniqueWithoutModInput[]
  createMany?: Prisma.ModDependencyCreateManyModInputEnvelope
  set?: Prisma.ModDependencyWhereUniqueInput | Prisma.ModDependencyWhereUniqueInput[]
  disconnect?: Prisma.ModDependencyWhereUniqueInput | Prisma.ModDependencyWhereUniqueInput[]
  delete?: Prisma.ModDependencyWhereUniqueInput | Prisma.ModDependencyWhereUniqueInput[]
  connect?: Prisma.ModDependencyWhereUniqueInput | Prisma.ModDependencyWhereUniqueInput[]
  update?: Prisma.ModDependencyUpdateWithWhereUniqueWithoutModInput | Prisma.ModDependencyUpdateWithWhereUniqueWithoutModInput[]
  updateMany?: Prisma.ModDependencyUpdateManyWithWhereWithoutModInput | Prisma.ModDependencyUpdateManyWithWhereWithoutModInput[]
  deleteMany?: Prisma.ModDependencyScalarWhereInput | Prisma.ModDependencyScalarWhereInput[]
}

export type ModDependencyUpdateManyWithoutDependencyModNestedInput = {
  create?: Prisma.XOR<Prisma.ModDependencyCreateWithoutDependencyModInput, Prisma.ModDependencyUncheckedCreateWithoutDependencyModInput> | Prisma.ModDependencyCreateWithoutDependencyModInput[] | Prisma.ModDependencyUncheckedCreateWithoutDependencyModInput[]
  connectOrCreate?: Prisma.ModDependencyCreateOrConnectWithoutDependencyModInput | Prisma.ModDependencyCreateOrConnectWithoutDependencyModInput[]
  upsert?: Prisma.ModDependencyUpsertWithWhereUniqueWithoutDependencyModInput | Prisma.ModDependencyUpsertWithWhereUniqueWithoutDependencyModInput[]
  createMany?: Prisma.ModDependencyCreateManyDependencyModInputEnvelope
  set?: Prisma.ModDependencyWhereUniqueInput | Prisma.ModDependencyWhereUniqueInput[]
  disconnect?: Prisma.ModDependencyWhereUniqueInput | Prisma.ModDependencyWhereUniqueInput[]
  delete?: Prisma.ModDependencyWhereUniqueInput | Prisma.ModDependencyWhereUniqueInput[]
  connect?: Prisma.ModDependencyWhereUniqueInput | Prisma.ModDependencyWhereUniqueInput[]
  update?: Prisma.ModDependencyUpdateWithWhereUniqueWithoutDependencyModInput | Prisma.ModDependencyUpdateWithWhereUniqueWithoutDependencyModInput[]
  updateMany?: Prisma.ModDependencyUpdateManyWithWhereWithoutDependencyModInput | Prisma.ModDependencyUpdateManyWithWhereWithoutDependencyModInput[]
  deleteMany?: Prisma.ModDependencyScalarWhereInput | Prisma.ModDependencyScalarWhereInput[]
}

export type ModDependencyUncheckedUpdateManyWithoutModNestedInput = {
  create?: Prisma.XOR<Prisma.ModDependencyCreateWithoutModInput, Prisma.ModDependencyUncheckedCreateWithoutModInput> | Prisma.ModDependencyCreateWithoutModInput[] | Prisma.ModDependencyUncheckedCreateWithoutModInput[]
  connectOrCreate?: Prisma.ModDependencyCreateOrConnectWithoutModInput | Prisma.ModDependencyCreateOrConnectWithoutModInput[]
  upsert?: Prisma.ModDependencyUpsertWithWhereUniqueWithoutModInput | Prisma.ModDependencyUpsertWithWhereUniqueWithoutModInput[]
  createMany?: Prisma.ModDependencyCreateManyModInputEnvelope
  set?: Prisma.ModDependencyWhereUniqueInput | Prisma.ModDependencyWhereUniqueInput[]
  disconnect?: Prisma.ModDependencyWhereUniqueInput | Prisma.ModDependencyWhereUniqueInput[]
  delete?: Prisma.ModDependencyWhereUniqueInput | Prisma.ModDependencyWhereUniqueInput[]
  connect?: Prisma.ModDependencyWhereUniqueInput | Prisma.ModDependencyWhereUniqueInput[]
  update?: Prisma.ModDependencyUpdateWithWhereUniqueWithoutModInput | Prisma.ModDependencyUpdateWithWhereUniqueWithoutModInput[]
  updateMany?: Prisma.ModDependencyUpdateManyWithWhereWithoutModInput | Prisma.ModDependencyUpdateManyWithWhereWithoutModInput[]
  deleteMany?: Prisma.ModDependencyScalarWhereInput | Prisma.ModDependencyScalarWhereInput[]
}

export type ModDependencyUncheckedUpdateManyWithoutDependencyModNestedInput = {
  create?: Prisma.XOR<Prisma.ModDependencyCreateWithoutDependencyModInput, Prisma.ModDependencyUncheckedCreateWithoutDependencyModInput> | Prisma.ModDependencyCreateWithoutDependencyModInput[] | Prisma.ModDependencyUncheckedCreateWithoutDependencyModInput[]
  connectOrCreate?: Prisma.ModDependencyCreateOrConnectWithoutDependencyModInput | Prisma.ModDependencyCreateOrConnectWithoutDependencyModInput[]
  upsert?: Prisma.ModDependencyUpsertWithWhereUniqueWithoutDependencyModInput | Prisma.ModDependencyUpsertWithWhereUniqueWithoutDependencyModInput[]
  createMany?: Prisma.ModDependencyCreateManyDependencyModInputEnvelope
  set?: Prisma.ModDependencyWhereUniqueInput | Prisma.ModDependencyWhereUniqueInput[]
  disconnect?: Prisma.ModDependencyWhereUniqueInput | Prisma.ModDependencyWhereUniqueInput[]
  delete?: Prisma.ModDependencyWhereUniqueInput | Prisma.ModDependencyWhereUniqueInput[]
  connect?: Prisma.ModDependencyWhereUniqueInput | Prisma.ModDependencyWhereUniqueInput[]
  update?: Prisma.ModDependencyUpdateWithWhereUniqueWithoutDependencyModInput | Prisma.ModDependencyUpdateWithWhereUniqueWithoutDependencyModInput[]
  updateMany?: Prisma.ModDependencyUpdateManyWithWhereWithoutDependencyModInput | Prisma.ModDependencyUpdateManyWithWhereWithoutDependencyModInput[]
  deleteMany?: Prisma.ModDependencyScalarWhereInput | Prisma.ModDependencyScalarWhereInput[]
}

export type EnumModDependencyRolFieldUpdateOperationsInput = {
  set?: $Enums.ModDependencyRol
}

export type ModDependencyCreateWithoutModInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  minVersion: string
  maxVersion: string
  rol?: $Enums.ModDependencyRol
  dependencyMod: Prisma.ModCreateNestedOneWithoutModDependenciesToInput
}

export type ModDependencyUncheckedCreateWithoutModInput = {
  id?: string
  dependencyModId: string
  createdAt?: Date | string
  updatedAt?: Date | string
  minVersion: string
  maxVersion: string
  rol?: $Enums.ModDependencyRol
}

export type ModDependencyCreateOrConnectWithoutModInput = {
  where: Prisma.ModDependencyWhereUniqueInput
  create: Prisma.XOR<Prisma.ModDependencyCreateWithoutModInput, Prisma.ModDependencyUncheckedCreateWithoutModInput>
}

export type ModDependencyCreateManyModInputEnvelope = {
  data: Prisma.ModDependencyCreateManyModInput | Prisma.ModDependencyCreateManyModInput[]
  skipDuplicates?: boolean
}

export type ModDependencyCreateWithoutDependencyModInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  minVersion: string
  maxVersion: string
  rol?: $Enums.ModDependencyRol
  mod: Prisma.ModCreateNestedOneWithoutModDependenciesFromInput
}

export type ModDependencyUncheckedCreateWithoutDependencyModInput = {
  id?: string
  modId: string
  createdAt?: Date | string
  updatedAt?: Date | string
  minVersion: string
  maxVersion: string
  rol?: $Enums.ModDependencyRol
}

export type ModDependencyCreateOrConnectWithoutDependencyModInput = {
  where: Prisma.ModDependencyWhereUniqueInput
  create: Prisma.XOR<Prisma.ModDependencyCreateWithoutDependencyModInput, Prisma.ModDependencyUncheckedCreateWithoutDependencyModInput>
}

export type ModDependencyCreateManyDependencyModInputEnvelope = {
  data: Prisma.ModDependencyCreateManyDependencyModInput | Prisma.ModDependencyCreateManyDependencyModInput[]
  skipDuplicates?: boolean
}

export type ModDependencyUpsertWithWhereUniqueWithoutModInput = {
  where: Prisma.ModDependencyWhereUniqueInput
  update: Prisma.XOR<Prisma.ModDependencyUpdateWithoutModInput, Prisma.ModDependencyUncheckedUpdateWithoutModInput>
  create: Prisma.XOR<Prisma.ModDependencyCreateWithoutModInput, Prisma.ModDependencyUncheckedCreateWithoutModInput>
}

export type ModDependencyUpdateWithWhereUniqueWithoutModInput = {
  where: Prisma.ModDependencyWhereUniqueInput
  data: Prisma.XOR<Prisma.ModDependencyUpdateWithoutModInput, Prisma.ModDependencyUncheckedUpdateWithoutModInput>
}

export type ModDependencyUpdateManyWithWhereWithoutModInput = {
  where: Prisma.ModDependencyScalarWhereInput
  data: Prisma.XOR<Prisma.ModDependencyUpdateManyMutationInput, Prisma.ModDependencyUncheckedUpdateManyWithoutModInput>
}

export type ModDependencyScalarWhereInput = {
  AND?: Prisma.ModDependencyScalarWhereInput | Prisma.ModDependencyScalarWhereInput[]
  OR?: Prisma.ModDependencyScalarWhereInput[]
  NOT?: Prisma.ModDependencyScalarWhereInput | Prisma.ModDependencyScalarWhereInput[]
  id?: Prisma.StringFilter<"ModDependency"> | string
  modId?: Prisma.StringFilter<"ModDependency"> | string
  dependencyModId?: Prisma.StringFilter<"ModDependency"> | string
  createdAt?: Prisma.DateTimeFilter<"ModDependency"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"ModDependency"> | Date | string
  minVersion?: Prisma.StringFilter<"ModDependency"> | string
  maxVersion?: Prisma.StringFilter<"ModDependency"> | string
  rol?: Prisma.EnumModDependencyRolFilter<"ModDependency"> | $Enums.ModDependencyRol
}

export type ModDependencyUpsertWithWhereUniqueWithoutDependencyModInput = {
  where: Prisma.ModDependencyWhereUniqueInput
  update: Prisma.XOR<Prisma.ModDependencyUpdateWithoutDependencyModInput, Prisma.ModDependencyUncheckedUpdateWithoutDependencyModInput>
  create: Prisma.XOR<Prisma.ModDependencyCreateWithoutDependencyModInput, Prisma.ModDependencyUncheckedCreateWithoutDependencyModInput>
}

export type ModDependencyUpdateWithWhereUniqueWithoutDependencyModInput = {
  where: Prisma.ModDependencyWhereUniqueInput
  data: Prisma.XOR<Prisma.ModDependencyUpdateWithoutDependencyModInput, Prisma.ModDependencyUncheckedUpdateWithoutDependencyModInput>
}

export type ModDependencyUpdateManyWithWhereWithoutDependencyModInput = {
  where: Prisma.ModDependencyScalarWhereInput
  data: Prisma.XOR<Prisma.ModDependencyUpdateManyMutationInput, Prisma.ModDependencyUncheckedUpdateManyWithoutDependencyModInput>
}

export type ModDependencyCreateManyModInput = {
  id?: string
  dependencyModId: string
  createdAt?: Date | string
  updatedAt?: Date | string
  minVersion: string
  maxVersion: string
  rol?: $Enums.ModDependencyRol
}

export type ModDependencyCreateManyDependencyModInput = {
  id?: string
  modId: string
  createdAt?: Date | string
  updatedAt?: Date | string
  minVersion: string
  maxVersion: string
  rol?: $Enums.ModDependencyRol
}

export type ModDependencyUpdateWithoutModInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  minVersion?: Prisma.StringFieldUpdateOperationsInput | string
  maxVersion?: Prisma.StringFieldUpdateOperationsInput | string
  rol?: Prisma.EnumModDependencyRolFieldUpdateOperationsInput | $Enums.ModDependencyRol
  dependencyMod?: Prisma.ModUpdateOneRequiredWithoutModDependenciesToNestedInput
}

export type ModDependencyUncheckedUpdateWithoutModInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  dependencyModId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  minVersion?: Prisma.StringFieldUpdateOperationsInput | string
  maxVersion?: Prisma.StringFieldUpdateOperationsInput | string
  rol?: Prisma.EnumModDependencyRolFieldUpdateOperationsInput | $Enums.ModDependencyRol
}

export type ModDependencyUncheckedUpdateManyWithoutModInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  dependencyModId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  minVersion?: Prisma.StringFieldUpdateOperationsInput | string
  maxVersion?: Prisma.StringFieldUpdateOperationsInput | string
  rol?: Prisma.EnumModDependencyRolFieldUpdateOperationsInput | $Enums.ModDependencyRol
}

export type ModDependencyUpdateWithoutDependencyModInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  minVersion?: Prisma.StringFieldUpdateOperationsInput | string
  maxVersion?: Prisma.StringFieldUpdateOperationsInput | string
  rol?: Prisma.EnumModDependencyRolFieldUpdateOperationsInput | $Enums.ModDependencyRol
  mod?: Prisma.ModUpdateOneRequiredWithoutModDependenciesFromNestedInput
}

export type ModDependencyUncheckedUpdateWithoutDependencyModInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  modId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  minVersion?: Prisma.StringFieldUpdateOperationsInput | string
  maxVersion?: Prisma.StringFieldUpdateOperationsInput | string
  rol?: Prisma.EnumModDependencyRolFieldUpdateOperationsInput | $Enums.ModDependencyRol
}

export type ModDependencyUncheckedUpdateManyWithoutDependencyModInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  modId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  minVersion?: Prisma.StringFieldUpdateOperationsInput | string
  maxVersion?: Prisma.StringFieldUpdateOperationsInput | string
  rol?: Prisma.EnumModDependencyRolFieldUpdateOperationsInput | $Enums.ModDependencyRol
}



export type ModDependencySelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  modId?: boolean
  dependencyModId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  minVersion?: boolean
  maxVersion?: boolean
  rol?: boolean
  mod?: boolean | Prisma.ModDefaultArgs<ExtArgs>
  dependencyMod?: boolean | Prisma.ModDefaultArgs<ExtArgs>
}, ExtArgs["result"]["modDependency"]>

export type ModDependencySelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  modId?: boolean
  dependencyModId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  minVersion?: boolean
  maxVersion?: boolean
  rol?: boolean
  mod?: boolean | Prisma.ModDefaultArgs<ExtArgs>
  dependencyMod?: boolean | Prisma.ModDefaultArgs<ExtArgs>
}, ExtArgs["result"]["modDependency"]>

export type ModDependencySelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  modId?: boolean
  dependencyModId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  minVersion?: boolean
  maxVersion?: boolean
  rol?: boolean
  mod?: boolean | Prisma.ModDefaultArgs<ExtArgs>
  dependencyMod?: boolean | Prisma.ModDefaultArgs<ExtArgs>
}, ExtArgs["result"]["modDependency"]>

export type ModDependencySelectScalar = {
  id?: boolean
  modId?: boolean
  dependencyModId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  minVersion?: boolean
  maxVersion?: boolean
  rol?: boolean
}

export type ModDependencyOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "modId" | "dependencyModId" | "createdAt" | "updatedAt" | "minVersion" | "maxVersion" | "rol", ExtArgs["result"]["modDependency"]>
export type ModDependencyInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  mod?: boolean | Prisma.ModDefaultArgs<ExtArgs>
  dependencyMod?: boolean | Prisma.ModDefaultArgs<ExtArgs>
}
export type ModDependencyIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  mod?: boolean | Prisma.ModDefaultArgs<ExtArgs>
  dependencyMod?: boolean | Prisma.ModDefaultArgs<ExtArgs>
}
export type ModDependencyIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  mod?: boolean | Prisma.ModDefaultArgs<ExtArgs>
  dependencyMod?: boolean | Prisma.ModDefaultArgs<ExtArgs>
}

export type $ModDependencyPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ModDependency"
  objects: {
    mod: Prisma.$ModPayload<ExtArgs>
    dependencyMod: Prisma.$ModPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    modId: string
    dependencyModId: string
    createdAt: Date
    updatedAt: Date
    minVersion: string
    maxVersion: string
    rol: $Enums.ModDependencyRol
  }, ExtArgs["result"]["modDependency"]>
  composites: {}
}

export type ModDependencyGetPayload<S extends boolean | null | undefined | ModDependencyDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ModDependencyPayload, S>

export type ModDependencyCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ModDependencyFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ModDependencyCountAggregateInputType | true
  }

export interface ModDependencyDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ModDependency'], meta: { name: 'ModDependency' } }
  /**
   * Find zero or one ModDependency that matches the filter.
   * @param {ModDependencyFindUniqueArgs} args - Arguments to find a ModDependency
   * @example
   * // Get one ModDependency
   * const modDependency = await prisma.modDependency.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ModDependencyFindUniqueArgs>(args: Prisma.SelectSubset<T, ModDependencyFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ModDependencyClient<runtime.Types.Result.GetResult<Prisma.$ModDependencyPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ModDependency that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ModDependencyFindUniqueOrThrowArgs} args - Arguments to find a ModDependency
   * @example
   * // Get one ModDependency
   * const modDependency = await prisma.modDependency.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ModDependencyFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ModDependencyFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ModDependencyClient<runtime.Types.Result.GetResult<Prisma.$ModDependencyPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ModDependency that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ModDependencyFindFirstArgs} args - Arguments to find a ModDependency
   * @example
   * // Get one ModDependency
   * const modDependency = await prisma.modDependency.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ModDependencyFindFirstArgs>(args?: Prisma.SelectSubset<T, ModDependencyFindFirstArgs<ExtArgs>>): Prisma.Prisma__ModDependencyClient<runtime.Types.Result.GetResult<Prisma.$ModDependencyPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ModDependency that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ModDependencyFindFirstOrThrowArgs} args - Arguments to find a ModDependency
   * @example
   * // Get one ModDependency
   * const modDependency = await prisma.modDependency.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ModDependencyFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ModDependencyFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ModDependencyClient<runtime.Types.Result.GetResult<Prisma.$ModDependencyPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ModDependencies that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ModDependencyFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ModDependencies
   * const modDependencies = await prisma.modDependency.findMany()
   * 
   * // Get first 10 ModDependencies
   * const modDependencies = await prisma.modDependency.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const modDependencyWithIdOnly = await prisma.modDependency.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ModDependencyFindManyArgs>(args?: Prisma.SelectSubset<T, ModDependencyFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ModDependencyPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ModDependency.
   * @param {ModDependencyCreateArgs} args - Arguments to create a ModDependency.
   * @example
   * // Create one ModDependency
   * const ModDependency = await prisma.modDependency.create({
   *   data: {
   *     // ... data to create a ModDependency
   *   }
   * })
   * 
   */
  create<T extends ModDependencyCreateArgs>(args: Prisma.SelectSubset<T, ModDependencyCreateArgs<ExtArgs>>): Prisma.Prisma__ModDependencyClient<runtime.Types.Result.GetResult<Prisma.$ModDependencyPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ModDependencies.
   * @param {ModDependencyCreateManyArgs} args - Arguments to create many ModDependencies.
   * @example
   * // Create many ModDependencies
   * const modDependency = await prisma.modDependency.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ModDependencyCreateManyArgs>(args?: Prisma.SelectSubset<T, ModDependencyCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many ModDependencies and returns the data saved in the database.
   * @param {ModDependencyCreateManyAndReturnArgs} args - Arguments to create many ModDependencies.
   * @example
   * // Create many ModDependencies
   * const modDependency = await prisma.modDependency.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many ModDependencies and only return the `id`
   * const modDependencyWithIdOnly = await prisma.modDependency.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ModDependencyCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ModDependencyCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ModDependencyPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a ModDependency.
   * @param {ModDependencyDeleteArgs} args - Arguments to delete one ModDependency.
   * @example
   * // Delete one ModDependency
   * const ModDependency = await prisma.modDependency.delete({
   *   where: {
   *     // ... filter to delete one ModDependency
   *   }
   * })
   * 
   */
  delete<T extends ModDependencyDeleteArgs>(args: Prisma.SelectSubset<T, ModDependencyDeleteArgs<ExtArgs>>): Prisma.Prisma__ModDependencyClient<runtime.Types.Result.GetResult<Prisma.$ModDependencyPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ModDependency.
   * @param {ModDependencyUpdateArgs} args - Arguments to update one ModDependency.
   * @example
   * // Update one ModDependency
   * const modDependency = await prisma.modDependency.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ModDependencyUpdateArgs>(args: Prisma.SelectSubset<T, ModDependencyUpdateArgs<ExtArgs>>): Prisma.Prisma__ModDependencyClient<runtime.Types.Result.GetResult<Prisma.$ModDependencyPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ModDependencies.
   * @param {ModDependencyDeleteManyArgs} args - Arguments to filter ModDependencies to delete.
   * @example
   * // Delete a few ModDependencies
   * const { count } = await prisma.modDependency.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ModDependencyDeleteManyArgs>(args?: Prisma.SelectSubset<T, ModDependencyDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ModDependencies.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ModDependencyUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ModDependencies
   * const modDependency = await prisma.modDependency.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ModDependencyUpdateManyArgs>(args: Prisma.SelectSubset<T, ModDependencyUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ModDependencies and returns the data updated in the database.
   * @param {ModDependencyUpdateManyAndReturnArgs} args - Arguments to update many ModDependencies.
   * @example
   * // Update many ModDependencies
   * const modDependency = await prisma.modDependency.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more ModDependencies and only return the `id`
   * const modDependencyWithIdOnly = await prisma.modDependency.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ModDependencyUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ModDependencyUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ModDependencyPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one ModDependency.
   * @param {ModDependencyUpsertArgs} args - Arguments to update or create a ModDependency.
   * @example
   * // Update or create a ModDependency
   * const modDependency = await prisma.modDependency.upsert({
   *   create: {
   *     // ... data to create a ModDependency
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ModDependency we want to update
   *   }
   * })
   */
  upsert<T extends ModDependencyUpsertArgs>(args: Prisma.SelectSubset<T, ModDependencyUpsertArgs<ExtArgs>>): Prisma.Prisma__ModDependencyClient<runtime.Types.Result.GetResult<Prisma.$ModDependencyPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ModDependencies.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ModDependencyCountArgs} args - Arguments to filter ModDependencies to count.
   * @example
   * // Count the number of ModDependencies
   * const count = await prisma.modDependency.count({
   *   where: {
   *     // ... the filter for the ModDependencies we want to count
   *   }
   * })
  **/
  count<T extends ModDependencyCountArgs>(
    args?: Prisma.Subset<T, ModDependencyCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ModDependencyCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ModDependency.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ModDependencyAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ModDependencyAggregateArgs>(args: Prisma.Subset<T, ModDependencyAggregateArgs>): Prisma.PrismaPromise<GetModDependencyAggregateType<T>>

  /**
   * Group by ModDependency.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ModDependencyGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ModDependencyGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ModDependencyGroupByArgs['orderBy'] }
      : { orderBy?: ModDependencyGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ModDependencyGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetModDependencyGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ModDependency model
 */
readonly fields: ModDependencyFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ModDependency.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ModDependencyClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  mod<T extends Prisma.ModDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ModDefaultArgs<ExtArgs>>): Prisma.Prisma__ModClient<runtime.Types.Result.GetResult<Prisma.$ModPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  dependencyMod<T extends Prisma.ModDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ModDefaultArgs<ExtArgs>>): Prisma.Prisma__ModClient<runtime.Types.Result.GetResult<Prisma.$ModPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ModDependency model
 */
export interface ModDependencyFieldRefs {
  readonly id: Prisma.FieldRef<"ModDependency", 'String'>
  readonly modId: Prisma.FieldRef<"ModDependency", 'String'>
  readonly dependencyModId: Prisma.FieldRef<"ModDependency", 'String'>
  readonly createdAt: Prisma.FieldRef<"ModDependency", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"ModDependency", 'DateTime'>
  readonly minVersion: Prisma.FieldRef<"ModDependency", 'String'>
  readonly maxVersion: Prisma.FieldRef<"ModDependency", 'String'>
  readonly rol: Prisma.FieldRef<"ModDependency", 'ModDependencyRol'>
}
    

// Custom InputTypes
/**
 * ModDependency findUnique
 */
export type ModDependencyFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ModDependency
   */
  select?: Prisma.ModDependencySelect<ExtArgs> | null
  /**
   * Omit specific fields from the ModDependency
   */
  omit?: Prisma.ModDependencyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ModDependencyInclude<ExtArgs> | null
  /**
   * Filter, which ModDependency to fetch.
   */
  where: Prisma.ModDependencyWhereUniqueInput
}

/**
 * ModDependency findUniqueOrThrow
 */
export type ModDependencyFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ModDependency
   */
  select?: Prisma.ModDependencySelect<ExtArgs> | null
  /**
   * Omit specific fields from the ModDependency
   */
  omit?: Prisma.ModDependencyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ModDependencyInclude<ExtArgs> | null
  /**
   * Filter, which ModDependency to fetch.
   */
  where: Prisma.ModDependencyWhereUniqueInput
}

/**
 * ModDependency findFirst
 */
export type ModDependencyFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ModDependency
   */
  select?: Prisma.ModDependencySelect<ExtArgs> | null
  /**
   * Omit specific fields from the ModDependency
   */
  omit?: Prisma.ModDependencyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ModDependencyInclude<ExtArgs> | null
  /**
   * Filter, which ModDependency to fetch.
   */
  where?: Prisma.ModDependencyWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ModDependencies to fetch.
   */
  orderBy?: Prisma.ModDependencyOrderByWithRelationInput | Prisma.ModDependencyOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ModDependencies.
   */
  cursor?: Prisma.ModDependencyWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ModDependencies from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ModDependencies.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ModDependencies.
   */
  distinct?: Prisma.ModDependencyScalarFieldEnum | Prisma.ModDependencyScalarFieldEnum[]
}

/**
 * ModDependency findFirstOrThrow
 */
export type ModDependencyFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ModDependency
   */
  select?: Prisma.ModDependencySelect<ExtArgs> | null
  /**
   * Omit specific fields from the ModDependency
   */
  omit?: Prisma.ModDependencyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ModDependencyInclude<ExtArgs> | null
  /**
   * Filter, which ModDependency to fetch.
   */
  where?: Prisma.ModDependencyWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ModDependencies to fetch.
   */
  orderBy?: Prisma.ModDependencyOrderByWithRelationInput | Prisma.ModDependencyOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ModDependencies.
   */
  cursor?: Prisma.ModDependencyWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ModDependencies from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ModDependencies.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ModDependencies.
   */
  distinct?: Prisma.ModDependencyScalarFieldEnum | Prisma.ModDependencyScalarFieldEnum[]
}

/**
 * ModDependency findMany
 */
export type ModDependencyFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ModDependency
   */
  select?: Prisma.ModDependencySelect<ExtArgs> | null
  /**
   * Omit specific fields from the ModDependency
   */
  omit?: Prisma.ModDependencyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ModDependencyInclude<ExtArgs> | null
  /**
   * Filter, which ModDependencies to fetch.
   */
  where?: Prisma.ModDependencyWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ModDependencies to fetch.
   */
  orderBy?: Prisma.ModDependencyOrderByWithRelationInput | Prisma.ModDependencyOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ModDependencies.
   */
  cursor?: Prisma.ModDependencyWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ModDependencies from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ModDependencies.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ModDependencies.
   */
  distinct?: Prisma.ModDependencyScalarFieldEnum | Prisma.ModDependencyScalarFieldEnum[]
}

/**
 * ModDependency create
 */
export type ModDependencyCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ModDependency
   */
  select?: Prisma.ModDependencySelect<ExtArgs> | null
  /**
   * Omit specific fields from the ModDependency
   */
  omit?: Prisma.ModDependencyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ModDependencyInclude<ExtArgs> | null
  /**
   * The data needed to create a ModDependency.
   */
  data: Prisma.XOR<Prisma.ModDependencyCreateInput, Prisma.ModDependencyUncheckedCreateInput>
}

/**
 * ModDependency createMany
 */
export type ModDependencyCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ModDependencies.
   */
  data: Prisma.ModDependencyCreateManyInput | Prisma.ModDependencyCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ModDependency createManyAndReturn
 */
export type ModDependencyCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ModDependency
   */
  select?: Prisma.ModDependencySelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ModDependency
   */
  omit?: Prisma.ModDependencyOmit<ExtArgs> | null
  /**
   * The data used to create many ModDependencies.
   */
  data: Prisma.ModDependencyCreateManyInput | Prisma.ModDependencyCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ModDependencyIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * ModDependency update
 */
export type ModDependencyUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ModDependency
   */
  select?: Prisma.ModDependencySelect<ExtArgs> | null
  /**
   * Omit specific fields from the ModDependency
   */
  omit?: Prisma.ModDependencyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ModDependencyInclude<ExtArgs> | null
  /**
   * The data needed to update a ModDependency.
   */
  data: Prisma.XOR<Prisma.ModDependencyUpdateInput, Prisma.ModDependencyUncheckedUpdateInput>
  /**
   * Choose, which ModDependency to update.
   */
  where: Prisma.ModDependencyWhereUniqueInput
}

/**
 * ModDependency updateMany
 */
export type ModDependencyUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ModDependencies.
   */
  data: Prisma.XOR<Prisma.ModDependencyUpdateManyMutationInput, Prisma.ModDependencyUncheckedUpdateManyInput>
  /**
   * Filter which ModDependencies to update
   */
  where?: Prisma.ModDependencyWhereInput
  /**
   * Limit how many ModDependencies to update.
   */
  limit?: number
}

/**
 * ModDependency updateManyAndReturn
 */
export type ModDependencyUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ModDependency
   */
  select?: Prisma.ModDependencySelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ModDependency
   */
  omit?: Prisma.ModDependencyOmit<ExtArgs> | null
  /**
   * The data used to update ModDependencies.
   */
  data: Prisma.XOR<Prisma.ModDependencyUpdateManyMutationInput, Prisma.ModDependencyUncheckedUpdateManyInput>
  /**
   * Filter which ModDependencies to update
   */
  where?: Prisma.ModDependencyWhereInput
  /**
   * Limit how many ModDependencies to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ModDependencyIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * ModDependency upsert
 */
export type ModDependencyUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ModDependency
   */
  select?: Prisma.ModDependencySelect<ExtArgs> | null
  /**
   * Omit specific fields from the ModDependency
   */
  omit?: Prisma.ModDependencyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ModDependencyInclude<ExtArgs> | null
  /**
   * The filter to search for the ModDependency to update in case it exists.
   */
  where: Prisma.ModDependencyWhereUniqueInput
  /**
   * In case the ModDependency found by the `where` argument doesn't exist, create a new ModDependency with this data.
   */
  create: Prisma.XOR<Prisma.ModDependencyCreateInput, Prisma.ModDependencyUncheckedCreateInput>
  /**
   * In case the ModDependency was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ModDependencyUpdateInput, Prisma.ModDependencyUncheckedUpdateInput>
}

/**
 * ModDependency delete
 */
export type ModDependencyDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ModDependency
   */
  select?: Prisma.ModDependencySelect<ExtArgs> | null
  /**
   * Omit specific fields from the ModDependency
   */
  omit?: Prisma.ModDependencyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ModDependencyInclude<ExtArgs> | null
  /**
   * Filter which ModDependency to delete.
   */
  where: Prisma.ModDependencyWhereUniqueInput
}

/**
 * ModDependency deleteMany
 */
export type ModDependencyDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ModDependencies to delete
   */
  where?: Prisma.ModDependencyWhereInput
  /**
   * Limit how many ModDependencies to delete.
   */
  limit?: number
}

/**
 * ModDependency without action
 */
export type ModDependencyDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ModDependency
   */
  select?: Prisma.ModDependencySelect<ExtArgs> | null
  /**
   * Omit specific fields from the ModDependency
   */
  omit?: Prisma.ModDependencyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ModDependencyInclude<ExtArgs> | null
}
