
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `PackShader` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model PackShader
 * 
 */
export type PackShaderModel = runtime.Types.Result.DefaultSelection<Prisma.$PackShaderPayload>

export type AggregatePackShader = {
  _count: PackShaderCountAggregateOutputType | null
  _min: PackShaderMinAggregateOutputType | null
  _max: PackShaderMaxAggregateOutputType | null
}

export type PackShaderMinAggregateOutputType = {
  id: string | null
  shaderFileId: string | null
  packVersionId: string | null
}

export type PackShaderMaxAggregateOutputType = {
  id: string | null
  shaderFileId: string | null
  packVersionId: string | null
}

export type PackShaderCountAggregateOutputType = {
  id: number
  shaderFileId: number
  packVersionId: number
  _all: number
}


export type PackShaderMinAggregateInputType = {
  id?: true
  shaderFileId?: true
  packVersionId?: true
}

export type PackShaderMaxAggregateInputType = {
  id?: true
  shaderFileId?: true
  packVersionId?: true
}

export type PackShaderCountAggregateInputType = {
  id?: true
  shaderFileId?: true
  packVersionId?: true
  _all?: true
}

export type PackShaderAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PackShader to aggregate.
   */
  where?: Prisma.PackShaderWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PackShaders to fetch.
   */
  orderBy?: Prisma.PackShaderOrderByWithRelationInput | Prisma.PackShaderOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.PackShaderWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PackShaders from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PackShaders.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned PackShaders
  **/
  _count?: true | PackShaderCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: PackShaderMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: PackShaderMaxAggregateInputType
}

export type GetPackShaderAggregateType<T extends PackShaderAggregateArgs> = {
      [P in keyof T & keyof AggregatePackShader]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregatePackShader[P]>
    : Prisma.GetScalarType<T[P], AggregatePackShader[P]>
}




export type PackShaderGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PackShaderWhereInput
  orderBy?: Prisma.PackShaderOrderByWithAggregationInput | Prisma.PackShaderOrderByWithAggregationInput[]
  by: Prisma.PackShaderScalarFieldEnum[] | Prisma.PackShaderScalarFieldEnum
  having?: Prisma.PackShaderScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: PackShaderCountAggregateInputType | true
  _min?: PackShaderMinAggregateInputType
  _max?: PackShaderMaxAggregateInputType
}

export type PackShaderGroupByOutputType = {
  id: string
  shaderFileId: string
  packVersionId: string
  _count: PackShaderCountAggregateOutputType | null
  _min: PackShaderMinAggregateOutputType | null
  _max: PackShaderMaxAggregateOutputType | null
}

export type GetPackShaderGroupByPayload<T extends PackShaderGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<PackShaderGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof PackShaderGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], PackShaderGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], PackShaderGroupByOutputType[P]>
      }
    >
  >



export type PackShaderWhereInput = {
  AND?: Prisma.PackShaderWhereInput | Prisma.PackShaderWhereInput[]
  OR?: Prisma.PackShaderWhereInput[]
  NOT?: Prisma.PackShaderWhereInput | Prisma.PackShaderWhereInput[]
  id?: Prisma.StringFilter<"PackShader"> | string
  shaderFileId?: Prisma.StringFilter<"PackShader"> | string
  packVersionId?: Prisma.StringFilter<"PackShader"> | string
  shaderFile?: Prisma.XOR<Prisma.ShaderFileScalarRelationFilter, Prisma.ShaderFileWhereInput>
  packVersion?: Prisma.XOR<Prisma.PackVersionScalarRelationFilter, Prisma.PackVersionWhereInput>
}

export type PackShaderOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  shaderFileId?: Prisma.SortOrder
  packVersionId?: Prisma.SortOrder
  shaderFile?: Prisma.ShaderFileOrderByWithRelationInput
  packVersion?: Prisma.PackVersionOrderByWithRelationInput
}

export type PackShaderWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.PackShaderWhereInput | Prisma.PackShaderWhereInput[]
  OR?: Prisma.PackShaderWhereInput[]
  NOT?: Prisma.PackShaderWhereInput | Prisma.PackShaderWhereInput[]
  shaderFileId?: Prisma.StringFilter<"PackShader"> | string
  packVersionId?: Prisma.StringFilter<"PackShader"> | string
  shaderFile?: Prisma.XOR<Prisma.ShaderFileScalarRelationFilter, Prisma.ShaderFileWhereInput>
  packVersion?: Prisma.XOR<Prisma.PackVersionScalarRelationFilter, Prisma.PackVersionWhereInput>
}, "id">

export type PackShaderOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  shaderFileId?: Prisma.SortOrder
  packVersionId?: Prisma.SortOrder
  _count?: Prisma.PackShaderCountOrderByAggregateInput
  _max?: Prisma.PackShaderMaxOrderByAggregateInput
  _min?: Prisma.PackShaderMinOrderByAggregateInput
}

export type PackShaderScalarWhereWithAggregatesInput = {
  AND?: Prisma.PackShaderScalarWhereWithAggregatesInput | Prisma.PackShaderScalarWhereWithAggregatesInput[]
  OR?: Prisma.PackShaderScalarWhereWithAggregatesInput[]
  NOT?: Prisma.PackShaderScalarWhereWithAggregatesInput | Prisma.PackShaderScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"PackShader"> | string
  shaderFileId?: Prisma.StringWithAggregatesFilter<"PackShader"> | string
  packVersionId?: Prisma.StringWithAggregatesFilter<"PackShader"> | string
}

export type PackShaderCreateInput = {
  id?: string
  shaderFile: Prisma.ShaderFileCreateNestedOneWithoutPackShadersInput
  packVersion: Prisma.PackVersionCreateNestedOneWithoutPackShadersInput
}

export type PackShaderUncheckedCreateInput = {
  id?: string
  shaderFileId: string
  packVersionId: string
}

export type PackShaderUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  shaderFile?: Prisma.ShaderFileUpdateOneRequiredWithoutPackShadersNestedInput
  packVersion?: Prisma.PackVersionUpdateOneRequiredWithoutPackShadersNestedInput
}

export type PackShaderUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  shaderFileId?: Prisma.StringFieldUpdateOperationsInput | string
  packVersionId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type PackShaderCreateManyInput = {
  id?: string
  shaderFileId: string
  packVersionId: string
}

export type PackShaderUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
}

export type PackShaderUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  shaderFileId?: Prisma.StringFieldUpdateOperationsInput | string
  packVersionId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type PackShaderListRelationFilter = {
  every?: Prisma.PackShaderWhereInput
  some?: Prisma.PackShaderWhereInput
  none?: Prisma.PackShaderWhereInput
}

export type PackShaderOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type PackShaderCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  shaderFileId?: Prisma.SortOrder
  packVersionId?: Prisma.SortOrder
}

export type PackShaderMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  shaderFileId?: Prisma.SortOrder
  packVersionId?: Prisma.SortOrder
}

export type PackShaderMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  shaderFileId?: Prisma.SortOrder
  packVersionId?: Prisma.SortOrder
}

export type PackShaderCreateNestedManyWithoutShaderFileInput = {
  create?: Prisma.XOR<Prisma.PackShaderCreateWithoutShaderFileInput, Prisma.PackShaderUncheckedCreateWithoutShaderFileInput> | Prisma.PackShaderCreateWithoutShaderFileInput[] | Prisma.PackShaderUncheckedCreateWithoutShaderFileInput[]
  connectOrCreate?: Prisma.PackShaderCreateOrConnectWithoutShaderFileInput | Prisma.PackShaderCreateOrConnectWithoutShaderFileInput[]
  createMany?: Prisma.PackShaderCreateManyShaderFileInputEnvelope
  connect?: Prisma.PackShaderWhereUniqueInput | Prisma.PackShaderWhereUniqueInput[]
}

export type PackShaderUncheckedCreateNestedManyWithoutShaderFileInput = {
  create?: Prisma.XOR<Prisma.PackShaderCreateWithoutShaderFileInput, Prisma.PackShaderUncheckedCreateWithoutShaderFileInput> | Prisma.PackShaderCreateWithoutShaderFileInput[] | Prisma.PackShaderUncheckedCreateWithoutShaderFileInput[]
  connectOrCreate?: Prisma.PackShaderCreateOrConnectWithoutShaderFileInput | Prisma.PackShaderCreateOrConnectWithoutShaderFileInput[]
  createMany?: Prisma.PackShaderCreateManyShaderFileInputEnvelope
  connect?: Prisma.PackShaderWhereUniqueInput | Prisma.PackShaderWhereUniqueInput[]
}

export type PackShaderUpdateManyWithoutShaderFileNestedInput = {
  create?: Prisma.XOR<Prisma.PackShaderCreateWithoutShaderFileInput, Prisma.PackShaderUncheckedCreateWithoutShaderFileInput> | Prisma.PackShaderCreateWithoutShaderFileInput[] | Prisma.PackShaderUncheckedCreateWithoutShaderFileInput[]
  connectOrCreate?: Prisma.PackShaderCreateOrConnectWithoutShaderFileInput | Prisma.PackShaderCreateOrConnectWithoutShaderFileInput[]
  upsert?: Prisma.PackShaderUpsertWithWhereUniqueWithoutShaderFileInput | Prisma.PackShaderUpsertWithWhereUniqueWithoutShaderFileInput[]
  createMany?: Prisma.PackShaderCreateManyShaderFileInputEnvelope
  set?: Prisma.PackShaderWhereUniqueInput | Prisma.PackShaderWhereUniqueInput[]
  disconnect?: Prisma.PackShaderWhereUniqueInput | Prisma.PackShaderWhereUniqueInput[]
  delete?: Prisma.PackShaderWhereUniqueInput | Prisma.PackShaderWhereUniqueInput[]
  connect?: Prisma.PackShaderWhereUniqueInput | Prisma.PackShaderWhereUniqueInput[]
  update?: Prisma.PackShaderUpdateWithWhereUniqueWithoutShaderFileInput | Prisma.PackShaderUpdateWithWhereUniqueWithoutShaderFileInput[]
  updateMany?: Prisma.PackShaderUpdateManyWithWhereWithoutShaderFileInput | Prisma.PackShaderUpdateManyWithWhereWithoutShaderFileInput[]
  deleteMany?: Prisma.PackShaderScalarWhereInput | Prisma.PackShaderScalarWhereInput[]
}

export type PackShaderUncheckedUpdateManyWithoutShaderFileNestedInput = {
  create?: Prisma.XOR<Prisma.PackShaderCreateWithoutShaderFileInput, Prisma.PackShaderUncheckedCreateWithoutShaderFileInput> | Prisma.PackShaderCreateWithoutShaderFileInput[] | Prisma.PackShaderUncheckedCreateWithoutShaderFileInput[]
  connectOrCreate?: Prisma.PackShaderCreateOrConnectWithoutShaderFileInput | Prisma.PackShaderCreateOrConnectWithoutShaderFileInput[]
  upsert?: Prisma.PackShaderUpsertWithWhereUniqueWithoutShaderFileInput | Prisma.PackShaderUpsertWithWhereUniqueWithoutShaderFileInput[]
  createMany?: Prisma.PackShaderCreateManyShaderFileInputEnvelope
  set?: Prisma.PackShaderWhereUniqueInput | Prisma.PackShaderWhereUniqueInput[]
  disconnect?: Prisma.PackShaderWhereUniqueInput | Prisma.PackShaderWhereUniqueInput[]
  delete?: Prisma.PackShaderWhereUniqueInput | Prisma.PackShaderWhereUniqueInput[]
  connect?: Prisma.PackShaderWhereUniqueInput | Prisma.PackShaderWhereUniqueInput[]
  update?: Prisma.PackShaderUpdateWithWhereUniqueWithoutShaderFileInput | Prisma.PackShaderUpdateWithWhereUniqueWithoutShaderFileInput[]
  updateMany?: Prisma.PackShaderUpdateManyWithWhereWithoutShaderFileInput | Prisma.PackShaderUpdateManyWithWhereWithoutShaderFileInput[]
  deleteMany?: Prisma.PackShaderScalarWhereInput | Prisma.PackShaderScalarWhereInput[]
}

export type PackShaderCreateNestedManyWithoutPackVersionInput = {
  create?: Prisma.XOR<Prisma.PackShaderCreateWithoutPackVersionInput, Prisma.PackShaderUncheckedCreateWithoutPackVersionInput> | Prisma.PackShaderCreateWithoutPackVersionInput[] | Prisma.PackShaderUncheckedCreateWithoutPackVersionInput[]
  connectOrCreate?: Prisma.PackShaderCreateOrConnectWithoutPackVersionInput | Prisma.PackShaderCreateOrConnectWithoutPackVersionInput[]
  createMany?: Prisma.PackShaderCreateManyPackVersionInputEnvelope
  connect?: Prisma.PackShaderWhereUniqueInput | Prisma.PackShaderWhereUniqueInput[]
}

export type PackShaderUncheckedCreateNestedManyWithoutPackVersionInput = {
  create?: Prisma.XOR<Prisma.PackShaderCreateWithoutPackVersionInput, Prisma.PackShaderUncheckedCreateWithoutPackVersionInput> | Prisma.PackShaderCreateWithoutPackVersionInput[] | Prisma.PackShaderUncheckedCreateWithoutPackVersionInput[]
  connectOrCreate?: Prisma.PackShaderCreateOrConnectWithoutPackVersionInput | Prisma.PackShaderCreateOrConnectWithoutPackVersionInput[]
  createMany?: Prisma.PackShaderCreateManyPackVersionInputEnvelope
  connect?: Prisma.PackShaderWhereUniqueInput | Prisma.PackShaderWhereUniqueInput[]
}

export type PackShaderUpdateManyWithoutPackVersionNestedInput = {
  create?: Prisma.XOR<Prisma.PackShaderCreateWithoutPackVersionInput, Prisma.PackShaderUncheckedCreateWithoutPackVersionInput> | Prisma.PackShaderCreateWithoutPackVersionInput[] | Prisma.PackShaderUncheckedCreateWithoutPackVersionInput[]
  connectOrCreate?: Prisma.PackShaderCreateOrConnectWithoutPackVersionInput | Prisma.PackShaderCreateOrConnectWithoutPackVersionInput[]
  upsert?: Prisma.PackShaderUpsertWithWhereUniqueWithoutPackVersionInput | Prisma.PackShaderUpsertWithWhereUniqueWithoutPackVersionInput[]
  createMany?: Prisma.PackShaderCreateManyPackVersionInputEnvelope
  set?: Prisma.PackShaderWhereUniqueInput | Prisma.PackShaderWhereUniqueInput[]
  disconnect?: Prisma.PackShaderWhereUniqueInput | Prisma.PackShaderWhereUniqueInput[]
  delete?: Prisma.PackShaderWhereUniqueInput | Prisma.PackShaderWhereUniqueInput[]
  connect?: Prisma.PackShaderWhereUniqueInput | Prisma.PackShaderWhereUniqueInput[]
  update?: Prisma.PackShaderUpdateWithWhereUniqueWithoutPackVersionInput | Prisma.PackShaderUpdateWithWhereUniqueWithoutPackVersionInput[]
  updateMany?: Prisma.PackShaderUpdateManyWithWhereWithoutPackVersionInput | Prisma.PackShaderUpdateManyWithWhereWithoutPackVersionInput[]
  deleteMany?: Prisma.PackShaderScalarWhereInput | Prisma.PackShaderScalarWhereInput[]
}

export type PackShaderUncheckedUpdateManyWithoutPackVersionNestedInput = {
  create?: Prisma.XOR<Prisma.PackShaderCreateWithoutPackVersionInput, Prisma.PackShaderUncheckedCreateWithoutPackVersionInput> | Prisma.PackShaderCreateWithoutPackVersionInput[] | Prisma.PackShaderUncheckedCreateWithoutPackVersionInput[]
  connectOrCreate?: Prisma.PackShaderCreateOrConnectWithoutPackVersionInput | Prisma.PackShaderCreateOrConnectWithoutPackVersionInput[]
  upsert?: Prisma.PackShaderUpsertWithWhereUniqueWithoutPackVersionInput | Prisma.PackShaderUpsertWithWhereUniqueWithoutPackVersionInput[]
  createMany?: Prisma.PackShaderCreateManyPackVersionInputEnvelope
  set?: Prisma.PackShaderWhereUniqueInput | Prisma.PackShaderWhereUniqueInput[]
  disconnect?: Prisma.PackShaderWhereUniqueInput | Prisma.PackShaderWhereUniqueInput[]
  delete?: Prisma.PackShaderWhereUniqueInput | Prisma.PackShaderWhereUniqueInput[]
  connect?: Prisma.PackShaderWhereUniqueInput | Prisma.PackShaderWhereUniqueInput[]
  update?: Prisma.PackShaderUpdateWithWhereUniqueWithoutPackVersionInput | Prisma.PackShaderUpdateWithWhereUniqueWithoutPackVersionInput[]
  updateMany?: Prisma.PackShaderUpdateManyWithWhereWithoutPackVersionInput | Prisma.PackShaderUpdateManyWithWhereWithoutPackVersionInput[]
  deleteMany?: Prisma.PackShaderScalarWhereInput | Prisma.PackShaderScalarWhereInput[]
}

export type PackShaderCreateWithoutShaderFileInput = {
  id?: string
  packVersion: Prisma.PackVersionCreateNestedOneWithoutPackShadersInput
}

export type PackShaderUncheckedCreateWithoutShaderFileInput = {
  id?: string
  packVersionId: string
}

export type PackShaderCreateOrConnectWithoutShaderFileInput = {
  where: Prisma.PackShaderWhereUniqueInput
  create: Prisma.XOR<Prisma.PackShaderCreateWithoutShaderFileInput, Prisma.PackShaderUncheckedCreateWithoutShaderFileInput>
}

export type PackShaderCreateManyShaderFileInputEnvelope = {
  data: Prisma.PackShaderCreateManyShaderFileInput | Prisma.PackShaderCreateManyShaderFileInput[]
  skipDuplicates?: boolean
}

export type PackShaderUpsertWithWhereUniqueWithoutShaderFileInput = {
  where: Prisma.PackShaderWhereUniqueInput
  update: Prisma.XOR<Prisma.PackShaderUpdateWithoutShaderFileInput, Prisma.PackShaderUncheckedUpdateWithoutShaderFileInput>
  create: Prisma.XOR<Prisma.PackShaderCreateWithoutShaderFileInput, Prisma.PackShaderUncheckedCreateWithoutShaderFileInput>
}

export type PackShaderUpdateWithWhereUniqueWithoutShaderFileInput = {
  where: Prisma.PackShaderWhereUniqueInput
  data: Prisma.XOR<Prisma.PackShaderUpdateWithoutShaderFileInput, Prisma.PackShaderUncheckedUpdateWithoutShaderFileInput>
}

export type PackShaderUpdateManyWithWhereWithoutShaderFileInput = {
  where: Prisma.PackShaderScalarWhereInput
  data: Prisma.XOR<Prisma.PackShaderUpdateManyMutationInput, Prisma.PackShaderUncheckedUpdateManyWithoutShaderFileInput>
}

export type PackShaderScalarWhereInput = {
  AND?: Prisma.PackShaderScalarWhereInput | Prisma.PackShaderScalarWhereInput[]
  OR?: Prisma.PackShaderScalarWhereInput[]
  NOT?: Prisma.PackShaderScalarWhereInput | Prisma.PackShaderScalarWhereInput[]
  id?: Prisma.StringFilter<"PackShader"> | string
  shaderFileId?: Prisma.StringFilter<"PackShader"> | string
  packVersionId?: Prisma.StringFilter<"PackShader"> | string
}

export type PackShaderCreateWithoutPackVersionInput = {
  id?: string
  shaderFile: Prisma.ShaderFileCreateNestedOneWithoutPackShadersInput
}

export type PackShaderUncheckedCreateWithoutPackVersionInput = {
  id?: string
  shaderFileId: string
}

export type PackShaderCreateOrConnectWithoutPackVersionInput = {
  where: Prisma.PackShaderWhereUniqueInput
  create: Prisma.XOR<Prisma.PackShaderCreateWithoutPackVersionInput, Prisma.PackShaderUncheckedCreateWithoutPackVersionInput>
}

export type PackShaderCreateManyPackVersionInputEnvelope = {
  data: Prisma.PackShaderCreateManyPackVersionInput | Prisma.PackShaderCreateManyPackVersionInput[]
  skipDuplicates?: boolean
}

export type PackShaderUpsertWithWhereUniqueWithoutPackVersionInput = {
  where: Prisma.PackShaderWhereUniqueInput
  update: Prisma.XOR<Prisma.PackShaderUpdateWithoutPackVersionInput, Prisma.PackShaderUncheckedUpdateWithoutPackVersionInput>
  create: Prisma.XOR<Prisma.PackShaderCreateWithoutPackVersionInput, Prisma.PackShaderUncheckedCreateWithoutPackVersionInput>
}

export type PackShaderUpdateWithWhereUniqueWithoutPackVersionInput = {
  where: Prisma.PackShaderWhereUniqueInput
  data: Prisma.XOR<Prisma.PackShaderUpdateWithoutPackVersionInput, Prisma.PackShaderUncheckedUpdateWithoutPackVersionInput>
}

export type PackShaderUpdateManyWithWhereWithoutPackVersionInput = {
  where: Prisma.PackShaderScalarWhereInput
  data: Prisma.XOR<Prisma.PackShaderUpdateManyMutationInput, Prisma.PackShaderUncheckedUpdateManyWithoutPackVersionInput>
}

export type PackShaderCreateManyShaderFileInput = {
  id?: string
  packVersionId: string
}

export type PackShaderUpdateWithoutShaderFileInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  packVersion?: Prisma.PackVersionUpdateOneRequiredWithoutPackShadersNestedInput
}

export type PackShaderUncheckedUpdateWithoutShaderFileInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  packVersionId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type PackShaderUncheckedUpdateManyWithoutShaderFileInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  packVersionId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type PackShaderCreateManyPackVersionInput = {
  id?: string
  shaderFileId: string
}

export type PackShaderUpdateWithoutPackVersionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  shaderFile?: Prisma.ShaderFileUpdateOneRequiredWithoutPackShadersNestedInput
}

export type PackShaderUncheckedUpdateWithoutPackVersionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  shaderFileId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type PackShaderUncheckedUpdateManyWithoutPackVersionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  shaderFileId?: Prisma.StringFieldUpdateOperationsInput | string
}



export type PackShaderSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  shaderFileId?: boolean
  packVersionId?: boolean
  shaderFile?: boolean | Prisma.ShaderFileDefaultArgs<ExtArgs>
  packVersion?: boolean | Prisma.PackVersionDefaultArgs<ExtArgs>
}, ExtArgs["result"]["packShader"]>

export type PackShaderSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  shaderFileId?: boolean
  packVersionId?: boolean
  shaderFile?: boolean | Prisma.ShaderFileDefaultArgs<ExtArgs>
  packVersion?: boolean | Prisma.PackVersionDefaultArgs<ExtArgs>
}, ExtArgs["result"]["packShader"]>

export type PackShaderSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  shaderFileId?: boolean
  packVersionId?: boolean
  shaderFile?: boolean | Prisma.ShaderFileDefaultArgs<ExtArgs>
  packVersion?: boolean | Prisma.PackVersionDefaultArgs<ExtArgs>
}, ExtArgs["result"]["packShader"]>

export type PackShaderSelectScalar = {
  id?: boolean
  shaderFileId?: boolean
  packVersionId?: boolean
}

export type PackShaderOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "shaderFileId" | "packVersionId", ExtArgs["result"]["packShader"]>
export type PackShaderInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  shaderFile?: boolean | Prisma.ShaderFileDefaultArgs<ExtArgs>
  packVersion?: boolean | Prisma.PackVersionDefaultArgs<ExtArgs>
}
export type PackShaderIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  shaderFile?: boolean | Prisma.ShaderFileDefaultArgs<ExtArgs>
  packVersion?: boolean | Prisma.PackVersionDefaultArgs<ExtArgs>
}
export type PackShaderIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  shaderFile?: boolean | Prisma.ShaderFileDefaultArgs<ExtArgs>
  packVersion?: boolean | Prisma.PackVersionDefaultArgs<ExtArgs>
}

export type $PackShaderPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "PackShader"
  objects: {
    shaderFile: Prisma.$ShaderFilePayload<ExtArgs>
    packVersion: Prisma.$PackVersionPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    shaderFileId: string
    packVersionId: string
  }, ExtArgs["result"]["packShader"]>
  composites: {}
}

export type PackShaderGetPayload<S extends boolean | null | undefined | PackShaderDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$PackShaderPayload, S>

export type PackShaderCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<PackShaderFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: PackShaderCountAggregateInputType | true
  }

export interface PackShaderDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['PackShader'], meta: { name: 'PackShader' } }
  /**
   * Find zero or one PackShader that matches the filter.
   * @param {PackShaderFindUniqueArgs} args - Arguments to find a PackShader
   * @example
   * // Get one PackShader
   * const packShader = await prisma.packShader.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends PackShaderFindUniqueArgs>(args: Prisma.SelectSubset<T, PackShaderFindUniqueArgs<ExtArgs>>): Prisma.Prisma__PackShaderClient<runtime.Types.Result.GetResult<Prisma.$PackShaderPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one PackShader that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {PackShaderFindUniqueOrThrowArgs} args - Arguments to find a PackShader
   * @example
   * // Get one PackShader
   * const packShader = await prisma.packShader.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends PackShaderFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, PackShaderFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__PackShaderClient<runtime.Types.Result.GetResult<Prisma.$PackShaderPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PackShader that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PackShaderFindFirstArgs} args - Arguments to find a PackShader
   * @example
   * // Get one PackShader
   * const packShader = await prisma.packShader.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends PackShaderFindFirstArgs>(args?: Prisma.SelectSubset<T, PackShaderFindFirstArgs<ExtArgs>>): Prisma.Prisma__PackShaderClient<runtime.Types.Result.GetResult<Prisma.$PackShaderPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PackShader that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PackShaderFindFirstOrThrowArgs} args - Arguments to find a PackShader
   * @example
   * // Get one PackShader
   * const packShader = await prisma.packShader.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends PackShaderFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, PackShaderFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__PackShaderClient<runtime.Types.Result.GetResult<Prisma.$PackShaderPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more PackShaders that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PackShaderFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all PackShaders
   * const packShaders = await prisma.packShader.findMany()
   * 
   * // Get first 10 PackShaders
   * const packShaders = await prisma.packShader.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const packShaderWithIdOnly = await prisma.packShader.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends PackShaderFindManyArgs>(args?: Prisma.SelectSubset<T, PackShaderFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PackShaderPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a PackShader.
   * @param {PackShaderCreateArgs} args - Arguments to create a PackShader.
   * @example
   * // Create one PackShader
   * const PackShader = await prisma.packShader.create({
   *   data: {
   *     // ... data to create a PackShader
   *   }
   * })
   * 
   */
  create<T extends PackShaderCreateArgs>(args: Prisma.SelectSubset<T, PackShaderCreateArgs<ExtArgs>>): Prisma.Prisma__PackShaderClient<runtime.Types.Result.GetResult<Prisma.$PackShaderPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many PackShaders.
   * @param {PackShaderCreateManyArgs} args - Arguments to create many PackShaders.
   * @example
   * // Create many PackShaders
   * const packShader = await prisma.packShader.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends PackShaderCreateManyArgs>(args?: Prisma.SelectSubset<T, PackShaderCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many PackShaders and returns the data saved in the database.
   * @param {PackShaderCreateManyAndReturnArgs} args - Arguments to create many PackShaders.
   * @example
   * // Create many PackShaders
   * const packShader = await prisma.packShader.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many PackShaders and only return the `id`
   * const packShaderWithIdOnly = await prisma.packShader.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends PackShaderCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, PackShaderCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PackShaderPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a PackShader.
   * @param {PackShaderDeleteArgs} args - Arguments to delete one PackShader.
   * @example
   * // Delete one PackShader
   * const PackShader = await prisma.packShader.delete({
   *   where: {
   *     // ... filter to delete one PackShader
   *   }
   * })
   * 
   */
  delete<T extends PackShaderDeleteArgs>(args: Prisma.SelectSubset<T, PackShaderDeleteArgs<ExtArgs>>): Prisma.Prisma__PackShaderClient<runtime.Types.Result.GetResult<Prisma.$PackShaderPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one PackShader.
   * @param {PackShaderUpdateArgs} args - Arguments to update one PackShader.
   * @example
   * // Update one PackShader
   * const packShader = await prisma.packShader.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends PackShaderUpdateArgs>(args: Prisma.SelectSubset<T, PackShaderUpdateArgs<ExtArgs>>): Prisma.Prisma__PackShaderClient<runtime.Types.Result.GetResult<Prisma.$PackShaderPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more PackShaders.
   * @param {PackShaderDeleteManyArgs} args - Arguments to filter PackShaders to delete.
   * @example
   * // Delete a few PackShaders
   * const { count } = await prisma.packShader.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends PackShaderDeleteManyArgs>(args?: Prisma.SelectSubset<T, PackShaderDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PackShaders.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PackShaderUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many PackShaders
   * const packShader = await prisma.packShader.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends PackShaderUpdateManyArgs>(args: Prisma.SelectSubset<T, PackShaderUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PackShaders and returns the data updated in the database.
   * @param {PackShaderUpdateManyAndReturnArgs} args - Arguments to update many PackShaders.
   * @example
   * // Update many PackShaders
   * const packShader = await prisma.packShader.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more PackShaders and only return the `id`
   * const packShaderWithIdOnly = await prisma.packShader.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends PackShaderUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, PackShaderUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PackShaderPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one PackShader.
   * @param {PackShaderUpsertArgs} args - Arguments to update or create a PackShader.
   * @example
   * // Update or create a PackShader
   * const packShader = await prisma.packShader.upsert({
   *   create: {
   *     // ... data to create a PackShader
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the PackShader we want to update
   *   }
   * })
   */
  upsert<T extends PackShaderUpsertArgs>(args: Prisma.SelectSubset<T, PackShaderUpsertArgs<ExtArgs>>): Prisma.Prisma__PackShaderClient<runtime.Types.Result.GetResult<Prisma.$PackShaderPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of PackShaders.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PackShaderCountArgs} args - Arguments to filter PackShaders to count.
   * @example
   * // Count the number of PackShaders
   * const count = await prisma.packShader.count({
   *   where: {
   *     // ... the filter for the PackShaders we want to count
   *   }
   * })
  **/
  count<T extends PackShaderCountArgs>(
    args?: Prisma.Subset<T, PackShaderCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], PackShaderCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a PackShader.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PackShaderAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends PackShaderAggregateArgs>(args: Prisma.Subset<T, PackShaderAggregateArgs>): Prisma.PrismaPromise<GetPackShaderAggregateType<T>>

  /**
   * Group by PackShader.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PackShaderGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends PackShaderGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: PackShaderGroupByArgs['orderBy'] }
      : { orderBy?: PackShaderGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, PackShaderGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetPackShaderGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the PackShader model
 */
readonly fields: PackShaderFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for PackShader.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__PackShaderClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  shaderFile<T extends Prisma.ShaderFileDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ShaderFileDefaultArgs<ExtArgs>>): Prisma.Prisma__ShaderFileClient<runtime.Types.Result.GetResult<Prisma.$ShaderFilePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  packVersion<T extends Prisma.PackVersionDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.PackVersionDefaultArgs<ExtArgs>>): Prisma.Prisma__PackVersionClient<runtime.Types.Result.GetResult<Prisma.$PackVersionPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the PackShader model
 */
export interface PackShaderFieldRefs {
  readonly id: Prisma.FieldRef<"PackShader", 'String'>
  readonly shaderFileId: Prisma.FieldRef<"PackShader", 'String'>
  readonly packVersionId: Prisma.FieldRef<"PackShader", 'String'>
}
    

// Custom InputTypes
/**
 * PackShader findUnique
 */
export type PackShaderFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PackShader
   */
  select?: Prisma.PackShaderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PackShader
   */
  omit?: Prisma.PackShaderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PackShaderInclude<ExtArgs> | null
  /**
   * Filter, which PackShader to fetch.
   */
  where: Prisma.PackShaderWhereUniqueInput
}

/**
 * PackShader findUniqueOrThrow
 */
export type PackShaderFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PackShader
   */
  select?: Prisma.PackShaderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PackShader
   */
  omit?: Prisma.PackShaderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PackShaderInclude<ExtArgs> | null
  /**
   * Filter, which PackShader to fetch.
   */
  where: Prisma.PackShaderWhereUniqueInput
}

/**
 * PackShader findFirst
 */
export type PackShaderFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PackShader
   */
  select?: Prisma.PackShaderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PackShader
   */
  omit?: Prisma.PackShaderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PackShaderInclude<ExtArgs> | null
  /**
   * Filter, which PackShader to fetch.
   */
  where?: Prisma.PackShaderWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PackShaders to fetch.
   */
  orderBy?: Prisma.PackShaderOrderByWithRelationInput | Prisma.PackShaderOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PackShaders.
   */
  cursor?: Prisma.PackShaderWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PackShaders from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PackShaders.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PackShaders.
   */
  distinct?: Prisma.PackShaderScalarFieldEnum | Prisma.PackShaderScalarFieldEnum[]
}

/**
 * PackShader findFirstOrThrow
 */
export type PackShaderFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PackShader
   */
  select?: Prisma.PackShaderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PackShader
   */
  omit?: Prisma.PackShaderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PackShaderInclude<ExtArgs> | null
  /**
   * Filter, which PackShader to fetch.
   */
  where?: Prisma.PackShaderWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PackShaders to fetch.
   */
  orderBy?: Prisma.PackShaderOrderByWithRelationInput | Prisma.PackShaderOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PackShaders.
   */
  cursor?: Prisma.PackShaderWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PackShaders from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PackShaders.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PackShaders.
   */
  distinct?: Prisma.PackShaderScalarFieldEnum | Prisma.PackShaderScalarFieldEnum[]
}

/**
 * PackShader findMany
 */
export type PackShaderFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PackShader
   */
  select?: Prisma.PackShaderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PackShader
   */
  omit?: Prisma.PackShaderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PackShaderInclude<ExtArgs> | null
  /**
   * Filter, which PackShaders to fetch.
   */
  where?: Prisma.PackShaderWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PackShaders to fetch.
   */
  orderBy?: Prisma.PackShaderOrderByWithRelationInput | Prisma.PackShaderOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing PackShaders.
   */
  cursor?: Prisma.PackShaderWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PackShaders from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PackShaders.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PackShaders.
   */
  distinct?: Prisma.PackShaderScalarFieldEnum | Prisma.PackShaderScalarFieldEnum[]
}

/**
 * PackShader create
 */
export type PackShaderCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PackShader
   */
  select?: Prisma.PackShaderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PackShader
   */
  omit?: Prisma.PackShaderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PackShaderInclude<ExtArgs> | null
  /**
   * The data needed to create a PackShader.
   */
  data: Prisma.XOR<Prisma.PackShaderCreateInput, Prisma.PackShaderUncheckedCreateInput>
}

/**
 * PackShader createMany
 */
export type PackShaderCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many PackShaders.
   */
  data: Prisma.PackShaderCreateManyInput | Prisma.PackShaderCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * PackShader createManyAndReturn
 */
export type PackShaderCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PackShader
   */
  select?: Prisma.PackShaderSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the PackShader
   */
  omit?: Prisma.PackShaderOmit<ExtArgs> | null
  /**
   * The data used to create many PackShaders.
   */
  data: Prisma.PackShaderCreateManyInput | Prisma.PackShaderCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PackShaderIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * PackShader update
 */
export type PackShaderUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PackShader
   */
  select?: Prisma.PackShaderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PackShader
   */
  omit?: Prisma.PackShaderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PackShaderInclude<ExtArgs> | null
  /**
   * The data needed to update a PackShader.
   */
  data: Prisma.XOR<Prisma.PackShaderUpdateInput, Prisma.PackShaderUncheckedUpdateInput>
  /**
   * Choose, which PackShader to update.
   */
  where: Prisma.PackShaderWhereUniqueInput
}

/**
 * PackShader updateMany
 */
export type PackShaderUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update PackShaders.
   */
  data: Prisma.XOR<Prisma.PackShaderUpdateManyMutationInput, Prisma.PackShaderUncheckedUpdateManyInput>
  /**
   * Filter which PackShaders to update
   */
  where?: Prisma.PackShaderWhereInput
  /**
   * Limit how many PackShaders to update.
   */
  limit?: number
}

/**
 * PackShader updateManyAndReturn
 */
export type PackShaderUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PackShader
   */
  select?: Prisma.PackShaderSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the PackShader
   */
  omit?: Prisma.PackShaderOmit<ExtArgs> | null
  /**
   * The data used to update PackShaders.
   */
  data: Prisma.XOR<Prisma.PackShaderUpdateManyMutationInput, Prisma.PackShaderUncheckedUpdateManyInput>
  /**
   * Filter which PackShaders to update
   */
  where?: Prisma.PackShaderWhereInput
  /**
   * Limit how many PackShaders to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PackShaderIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * PackShader upsert
 */
export type PackShaderUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PackShader
   */
  select?: Prisma.PackShaderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PackShader
   */
  omit?: Prisma.PackShaderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PackShaderInclude<ExtArgs> | null
  /**
   * The filter to search for the PackShader to update in case it exists.
   */
  where: Prisma.PackShaderWhereUniqueInput
  /**
   * In case the PackShader found by the `where` argument doesn't exist, create a new PackShader with this data.
   */
  create: Prisma.XOR<Prisma.PackShaderCreateInput, Prisma.PackShaderUncheckedCreateInput>
  /**
   * In case the PackShader was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.PackShaderUpdateInput, Prisma.PackShaderUncheckedUpdateInput>
}

/**
 * PackShader delete
 */
export type PackShaderDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PackShader
   */
  select?: Prisma.PackShaderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PackShader
   */
  omit?: Prisma.PackShaderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PackShaderInclude<ExtArgs> | null
  /**
   * Filter which PackShader to delete.
   */
  where: Prisma.PackShaderWhereUniqueInput
}

/**
 * PackShader deleteMany
 */
export type PackShaderDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PackShaders to delete
   */
  where?: Prisma.PackShaderWhereInput
  /**
   * Limit how many PackShaders to delete.
   */
  limit?: number
}

/**
 * PackShader without action
 */
export type PackShaderDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PackShader
   */
  select?: Prisma.PackShaderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PackShader
   */
  omit?: Prisma.PackShaderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PackShaderInclude<ExtArgs> | null
}
