
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `PackMod` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model PackMod
 * 
 */
export type PackModModel = runtime.Types.Result.DefaultSelection<Prisma.$PackModPayload>

export type AggregatePackMod = {
  _count: PackModCountAggregateOutputType | null
  _avg: PackModAvgAggregateOutputType | null
  _sum: PackModSumAggregateOutputType | null
  _min: PackModMinAggregateOutputType | null
  _max: PackModMaxAggregateOutputType | null
}

export type PackModAvgAggregateOutputType = {
  loadOrder: number | null
}

export type PackModSumAggregateOutputType = {
  loadOrder: number | null
}

export type PackModMinAggregateOutputType = {
  id: string | null
  packVersionId: string | null
  modFileId: string | null
  optional: boolean | null
  loadOrder: number | null
}

export type PackModMaxAggregateOutputType = {
  id: string | null
  packVersionId: string | null
  modFileId: string | null
  optional: boolean | null
  loadOrder: number | null
}

export type PackModCountAggregateOutputType = {
  id: number
  packVersionId: number
  modFileId: number
  optional: number
  loadOrder: number
  _all: number
}


export type PackModAvgAggregateInputType = {
  loadOrder?: true
}

export type PackModSumAggregateInputType = {
  loadOrder?: true
}

export type PackModMinAggregateInputType = {
  id?: true
  packVersionId?: true
  modFileId?: true
  optional?: true
  loadOrder?: true
}

export type PackModMaxAggregateInputType = {
  id?: true
  packVersionId?: true
  modFileId?: true
  optional?: true
  loadOrder?: true
}

export type PackModCountAggregateInputType = {
  id?: true
  packVersionId?: true
  modFileId?: true
  optional?: true
  loadOrder?: true
  _all?: true
}

export type PackModAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PackMod to aggregate.
   */
  where?: Prisma.PackModWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PackMods to fetch.
   */
  orderBy?: Prisma.PackModOrderByWithRelationInput | Prisma.PackModOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.PackModWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PackMods from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PackMods.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned PackMods
  **/
  _count?: true | PackModCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: PackModAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: PackModSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: PackModMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: PackModMaxAggregateInputType
}

export type GetPackModAggregateType<T extends PackModAggregateArgs> = {
      [P in keyof T & keyof AggregatePackMod]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregatePackMod[P]>
    : Prisma.GetScalarType<T[P], AggregatePackMod[P]>
}




export type PackModGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PackModWhereInput
  orderBy?: Prisma.PackModOrderByWithAggregationInput | Prisma.PackModOrderByWithAggregationInput[]
  by: Prisma.PackModScalarFieldEnum[] | Prisma.PackModScalarFieldEnum
  having?: Prisma.PackModScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: PackModCountAggregateInputType | true
  _avg?: PackModAvgAggregateInputType
  _sum?: PackModSumAggregateInputType
  _min?: PackModMinAggregateInputType
  _max?: PackModMaxAggregateInputType
}

export type PackModGroupByOutputType = {
  id: string
  packVersionId: string
  modFileId: string
  optional: boolean
  loadOrder: number
  _count: PackModCountAggregateOutputType | null
  _avg: PackModAvgAggregateOutputType | null
  _sum: PackModSumAggregateOutputType | null
  _min: PackModMinAggregateOutputType | null
  _max: PackModMaxAggregateOutputType | null
}

export type GetPackModGroupByPayload<T extends PackModGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<PackModGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof PackModGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], PackModGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], PackModGroupByOutputType[P]>
      }
    >
  >



export type PackModWhereInput = {
  AND?: Prisma.PackModWhereInput | Prisma.PackModWhereInput[]
  OR?: Prisma.PackModWhereInput[]
  NOT?: Prisma.PackModWhereInput | Prisma.PackModWhereInput[]
  id?: Prisma.StringFilter<"PackMod"> | string
  packVersionId?: Prisma.StringFilter<"PackMod"> | string
  modFileId?: Prisma.StringFilter<"PackMod"> | string
  optional?: Prisma.BoolFilter<"PackMod"> | boolean
  loadOrder?: Prisma.IntFilter<"PackMod"> | number
  packVersion?: Prisma.XOR<Prisma.PackVersionScalarRelationFilter, Prisma.PackVersionWhereInput>
  modFile?: Prisma.XOR<Prisma.ModFileScalarRelationFilter, Prisma.ModFileWhereInput>
}

export type PackModOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  packVersionId?: Prisma.SortOrder
  modFileId?: Prisma.SortOrder
  optional?: Prisma.SortOrder
  loadOrder?: Prisma.SortOrder
  packVersion?: Prisma.PackVersionOrderByWithRelationInput
  modFile?: Prisma.ModFileOrderByWithRelationInput
}

export type PackModWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.PackModWhereInput | Prisma.PackModWhereInput[]
  OR?: Prisma.PackModWhereInput[]
  NOT?: Prisma.PackModWhereInput | Prisma.PackModWhereInput[]
  packVersionId?: Prisma.StringFilter<"PackMod"> | string
  modFileId?: Prisma.StringFilter<"PackMod"> | string
  optional?: Prisma.BoolFilter<"PackMod"> | boolean
  loadOrder?: Prisma.IntFilter<"PackMod"> | number
  packVersion?: Prisma.XOR<Prisma.PackVersionScalarRelationFilter, Prisma.PackVersionWhereInput>
  modFile?: Prisma.XOR<Prisma.ModFileScalarRelationFilter, Prisma.ModFileWhereInput>
}, "id">

export type PackModOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  packVersionId?: Prisma.SortOrder
  modFileId?: Prisma.SortOrder
  optional?: Prisma.SortOrder
  loadOrder?: Prisma.SortOrder
  _count?: Prisma.PackModCountOrderByAggregateInput
  _avg?: Prisma.PackModAvgOrderByAggregateInput
  _max?: Prisma.PackModMaxOrderByAggregateInput
  _min?: Prisma.PackModMinOrderByAggregateInput
  _sum?: Prisma.PackModSumOrderByAggregateInput
}

export type PackModScalarWhereWithAggregatesInput = {
  AND?: Prisma.PackModScalarWhereWithAggregatesInput | Prisma.PackModScalarWhereWithAggregatesInput[]
  OR?: Prisma.PackModScalarWhereWithAggregatesInput[]
  NOT?: Prisma.PackModScalarWhereWithAggregatesInput | Prisma.PackModScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"PackMod"> | string
  packVersionId?: Prisma.StringWithAggregatesFilter<"PackMod"> | string
  modFileId?: Prisma.StringWithAggregatesFilter<"PackMod"> | string
  optional?: Prisma.BoolWithAggregatesFilter<"PackMod"> | boolean
  loadOrder?: Prisma.IntWithAggregatesFilter<"PackMod"> | number
}

export type PackModCreateInput = {
  id?: string
  optional: boolean
  loadOrder: number
  packVersion: Prisma.PackVersionCreateNestedOneWithoutPackModsInput
  modFile: Prisma.ModFileCreateNestedOneWithoutPackModsInput
}

export type PackModUncheckedCreateInput = {
  id?: string
  packVersionId: string
  modFileId: string
  optional: boolean
  loadOrder: number
}

export type PackModUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  optional?: Prisma.BoolFieldUpdateOperationsInput | boolean
  loadOrder?: Prisma.IntFieldUpdateOperationsInput | number
  packVersion?: Prisma.PackVersionUpdateOneRequiredWithoutPackModsNestedInput
  modFile?: Prisma.ModFileUpdateOneRequiredWithoutPackModsNestedInput
}

export type PackModUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  packVersionId?: Prisma.StringFieldUpdateOperationsInput | string
  modFileId?: Prisma.StringFieldUpdateOperationsInput | string
  optional?: Prisma.BoolFieldUpdateOperationsInput | boolean
  loadOrder?: Prisma.IntFieldUpdateOperationsInput | number
}

export type PackModCreateManyInput = {
  id?: string
  packVersionId: string
  modFileId: string
  optional: boolean
  loadOrder: number
}

export type PackModUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  optional?: Prisma.BoolFieldUpdateOperationsInput | boolean
  loadOrder?: Prisma.IntFieldUpdateOperationsInput | number
}

export type PackModUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  packVersionId?: Prisma.StringFieldUpdateOperationsInput | string
  modFileId?: Prisma.StringFieldUpdateOperationsInput | string
  optional?: Prisma.BoolFieldUpdateOperationsInput | boolean
  loadOrder?: Prisma.IntFieldUpdateOperationsInput | number
}

export type PackModListRelationFilter = {
  every?: Prisma.PackModWhereInput
  some?: Prisma.PackModWhereInput
  none?: Prisma.PackModWhereInput
}

export type PackModOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type PackModCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  packVersionId?: Prisma.SortOrder
  modFileId?: Prisma.SortOrder
  optional?: Prisma.SortOrder
  loadOrder?: Prisma.SortOrder
}

export type PackModAvgOrderByAggregateInput = {
  loadOrder?: Prisma.SortOrder
}

export type PackModMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  packVersionId?: Prisma.SortOrder
  modFileId?: Prisma.SortOrder
  optional?: Prisma.SortOrder
  loadOrder?: Prisma.SortOrder
}

export type PackModMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  packVersionId?: Prisma.SortOrder
  modFileId?: Prisma.SortOrder
  optional?: Prisma.SortOrder
  loadOrder?: Prisma.SortOrder
}

export type PackModSumOrderByAggregateInput = {
  loadOrder?: Prisma.SortOrder
}

export type PackModCreateNestedManyWithoutModFileInput = {
  create?: Prisma.XOR<Prisma.PackModCreateWithoutModFileInput, Prisma.PackModUncheckedCreateWithoutModFileInput> | Prisma.PackModCreateWithoutModFileInput[] | Prisma.PackModUncheckedCreateWithoutModFileInput[]
  connectOrCreate?: Prisma.PackModCreateOrConnectWithoutModFileInput | Prisma.PackModCreateOrConnectWithoutModFileInput[]
  createMany?: Prisma.PackModCreateManyModFileInputEnvelope
  connect?: Prisma.PackModWhereUniqueInput | Prisma.PackModWhereUniqueInput[]
}

export type PackModUncheckedCreateNestedManyWithoutModFileInput = {
  create?: Prisma.XOR<Prisma.PackModCreateWithoutModFileInput, Prisma.PackModUncheckedCreateWithoutModFileInput> | Prisma.PackModCreateWithoutModFileInput[] | Prisma.PackModUncheckedCreateWithoutModFileInput[]
  connectOrCreate?: Prisma.PackModCreateOrConnectWithoutModFileInput | Prisma.PackModCreateOrConnectWithoutModFileInput[]
  createMany?: Prisma.PackModCreateManyModFileInputEnvelope
  connect?: Prisma.PackModWhereUniqueInput | Prisma.PackModWhereUniqueInput[]
}

export type PackModUpdateManyWithoutModFileNestedInput = {
  create?: Prisma.XOR<Prisma.PackModCreateWithoutModFileInput, Prisma.PackModUncheckedCreateWithoutModFileInput> | Prisma.PackModCreateWithoutModFileInput[] | Prisma.PackModUncheckedCreateWithoutModFileInput[]
  connectOrCreate?: Prisma.PackModCreateOrConnectWithoutModFileInput | Prisma.PackModCreateOrConnectWithoutModFileInput[]
  upsert?: Prisma.PackModUpsertWithWhereUniqueWithoutModFileInput | Prisma.PackModUpsertWithWhereUniqueWithoutModFileInput[]
  createMany?: Prisma.PackModCreateManyModFileInputEnvelope
  set?: Prisma.PackModWhereUniqueInput | Prisma.PackModWhereUniqueInput[]
  disconnect?: Prisma.PackModWhereUniqueInput | Prisma.PackModWhereUniqueInput[]
  delete?: Prisma.PackModWhereUniqueInput | Prisma.PackModWhereUniqueInput[]
  connect?: Prisma.PackModWhereUniqueInput | Prisma.PackModWhereUniqueInput[]
  update?: Prisma.PackModUpdateWithWhereUniqueWithoutModFileInput | Prisma.PackModUpdateWithWhereUniqueWithoutModFileInput[]
  updateMany?: Prisma.PackModUpdateManyWithWhereWithoutModFileInput | Prisma.PackModUpdateManyWithWhereWithoutModFileInput[]
  deleteMany?: Prisma.PackModScalarWhereInput | Prisma.PackModScalarWhereInput[]
}

export type PackModUncheckedUpdateManyWithoutModFileNestedInput = {
  create?: Prisma.XOR<Prisma.PackModCreateWithoutModFileInput, Prisma.PackModUncheckedCreateWithoutModFileInput> | Prisma.PackModCreateWithoutModFileInput[] | Prisma.PackModUncheckedCreateWithoutModFileInput[]
  connectOrCreate?: Prisma.PackModCreateOrConnectWithoutModFileInput | Prisma.PackModCreateOrConnectWithoutModFileInput[]
  upsert?: Prisma.PackModUpsertWithWhereUniqueWithoutModFileInput | Prisma.PackModUpsertWithWhereUniqueWithoutModFileInput[]
  createMany?: Prisma.PackModCreateManyModFileInputEnvelope
  set?: Prisma.PackModWhereUniqueInput | Prisma.PackModWhereUniqueInput[]
  disconnect?: Prisma.PackModWhereUniqueInput | Prisma.PackModWhereUniqueInput[]
  delete?: Prisma.PackModWhereUniqueInput | Prisma.PackModWhereUniqueInput[]
  connect?: Prisma.PackModWhereUniqueInput | Prisma.PackModWhereUniqueInput[]
  update?: Prisma.PackModUpdateWithWhereUniqueWithoutModFileInput | Prisma.PackModUpdateWithWhereUniqueWithoutModFileInput[]
  updateMany?: Prisma.PackModUpdateManyWithWhereWithoutModFileInput | Prisma.PackModUpdateManyWithWhereWithoutModFileInput[]
  deleteMany?: Prisma.PackModScalarWhereInput | Prisma.PackModScalarWhereInput[]
}

export type PackModCreateNestedManyWithoutPackVersionInput = {
  create?: Prisma.XOR<Prisma.PackModCreateWithoutPackVersionInput, Prisma.PackModUncheckedCreateWithoutPackVersionInput> | Prisma.PackModCreateWithoutPackVersionInput[] | Prisma.PackModUncheckedCreateWithoutPackVersionInput[]
  connectOrCreate?: Prisma.PackModCreateOrConnectWithoutPackVersionInput | Prisma.PackModCreateOrConnectWithoutPackVersionInput[]
  createMany?: Prisma.PackModCreateManyPackVersionInputEnvelope
  connect?: Prisma.PackModWhereUniqueInput | Prisma.PackModWhereUniqueInput[]
}

export type PackModUncheckedCreateNestedManyWithoutPackVersionInput = {
  create?: Prisma.XOR<Prisma.PackModCreateWithoutPackVersionInput, Prisma.PackModUncheckedCreateWithoutPackVersionInput> | Prisma.PackModCreateWithoutPackVersionInput[] | Prisma.PackModUncheckedCreateWithoutPackVersionInput[]
  connectOrCreate?: Prisma.PackModCreateOrConnectWithoutPackVersionInput | Prisma.PackModCreateOrConnectWithoutPackVersionInput[]
  createMany?: Prisma.PackModCreateManyPackVersionInputEnvelope
  connect?: Prisma.PackModWhereUniqueInput | Prisma.PackModWhereUniqueInput[]
}

export type PackModUpdateManyWithoutPackVersionNestedInput = {
  create?: Prisma.XOR<Prisma.PackModCreateWithoutPackVersionInput, Prisma.PackModUncheckedCreateWithoutPackVersionInput> | Prisma.PackModCreateWithoutPackVersionInput[] | Prisma.PackModUncheckedCreateWithoutPackVersionInput[]
  connectOrCreate?: Prisma.PackModCreateOrConnectWithoutPackVersionInput | Prisma.PackModCreateOrConnectWithoutPackVersionInput[]
  upsert?: Prisma.PackModUpsertWithWhereUniqueWithoutPackVersionInput | Prisma.PackModUpsertWithWhereUniqueWithoutPackVersionInput[]
  createMany?: Prisma.PackModCreateManyPackVersionInputEnvelope
  set?: Prisma.PackModWhereUniqueInput | Prisma.PackModWhereUniqueInput[]
  disconnect?: Prisma.PackModWhereUniqueInput | Prisma.PackModWhereUniqueInput[]
  delete?: Prisma.PackModWhereUniqueInput | Prisma.PackModWhereUniqueInput[]
  connect?: Prisma.PackModWhereUniqueInput | Prisma.PackModWhereUniqueInput[]
  update?: Prisma.PackModUpdateWithWhereUniqueWithoutPackVersionInput | Prisma.PackModUpdateWithWhereUniqueWithoutPackVersionInput[]
  updateMany?: Prisma.PackModUpdateManyWithWhereWithoutPackVersionInput | Prisma.PackModUpdateManyWithWhereWithoutPackVersionInput[]
  deleteMany?: Prisma.PackModScalarWhereInput | Prisma.PackModScalarWhereInput[]
}

export type PackModUncheckedUpdateManyWithoutPackVersionNestedInput = {
  create?: Prisma.XOR<Prisma.PackModCreateWithoutPackVersionInput, Prisma.PackModUncheckedCreateWithoutPackVersionInput> | Prisma.PackModCreateWithoutPackVersionInput[] | Prisma.PackModUncheckedCreateWithoutPackVersionInput[]
  connectOrCreate?: Prisma.PackModCreateOrConnectWithoutPackVersionInput | Prisma.PackModCreateOrConnectWithoutPackVersionInput[]
  upsert?: Prisma.PackModUpsertWithWhereUniqueWithoutPackVersionInput | Prisma.PackModUpsertWithWhereUniqueWithoutPackVersionInput[]
  createMany?: Prisma.PackModCreateManyPackVersionInputEnvelope
  set?: Prisma.PackModWhereUniqueInput | Prisma.PackModWhereUniqueInput[]
  disconnect?: Prisma.PackModWhereUniqueInput | Prisma.PackModWhereUniqueInput[]
  delete?: Prisma.PackModWhereUniqueInput | Prisma.PackModWhereUniqueInput[]
  connect?: Prisma.PackModWhereUniqueInput | Prisma.PackModWhereUniqueInput[]
  update?: Prisma.PackModUpdateWithWhereUniqueWithoutPackVersionInput | Prisma.PackModUpdateWithWhereUniqueWithoutPackVersionInput[]
  updateMany?: Prisma.PackModUpdateManyWithWhereWithoutPackVersionInput | Prisma.PackModUpdateManyWithWhereWithoutPackVersionInput[]
  deleteMany?: Prisma.PackModScalarWhereInput | Prisma.PackModScalarWhereInput[]
}

export type BoolFieldUpdateOperationsInput = {
  set?: boolean
}

export type PackModCreateWithoutModFileInput = {
  id?: string
  optional: boolean
  loadOrder: number
  packVersion: Prisma.PackVersionCreateNestedOneWithoutPackModsInput
}

export type PackModUncheckedCreateWithoutModFileInput = {
  id?: string
  packVersionId: string
  optional: boolean
  loadOrder: number
}

export type PackModCreateOrConnectWithoutModFileInput = {
  where: Prisma.PackModWhereUniqueInput
  create: Prisma.XOR<Prisma.PackModCreateWithoutModFileInput, Prisma.PackModUncheckedCreateWithoutModFileInput>
}

export type PackModCreateManyModFileInputEnvelope = {
  data: Prisma.PackModCreateManyModFileInput | Prisma.PackModCreateManyModFileInput[]
  skipDuplicates?: boolean
}

export type PackModUpsertWithWhereUniqueWithoutModFileInput = {
  where: Prisma.PackModWhereUniqueInput
  update: Prisma.XOR<Prisma.PackModUpdateWithoutModFileInput, Prisma.PackModUncheckedUpdateWithoutModFileInput>
  create: Prisma.XOR<Prisma.PackModCreateWithoutModFileInput, Prisma.PackModUncheckedCreateWithoutModFileInput>
}

export type PackModUpdateWithWhereUniqueWithoutModFileInput = {
  where: Prisma.PackModWhereUniqueInput
  data: Prisma.XOR<Prisma.PackModUpdateWithoutModFileInput, Prisma.PackModUncheckedUpdateWithoutModFileInput>
}

export type PackModUpdateManyWithWhereWithoutModFileInput = {
  where: Prisma.PackModScalarWhereInput
  data: Prisma.XOR<Prisma.PackModUpdateManyMutationInput, Prisma.PackModUncheckedUpdateManyWithoutModFileInput>
}

export type PackModScalarWhereInput = {
  AND?: Prisma.PackModScalarWhereInput | Prisma.PackModScalarWhereInput[]
  OR?: Prisma.PackModScalarWhereInput[]
  NOT?: Prisma.PackModScalarWhereInput | Prisma.PackModScalarWhereInput[]
  id?: Prisma.StringFilter<"PackMod"> | string
  packVersionId?: Prisma.StringFilter<"PackMod"> | string
  modFileId?: Prisma.StringFilter<"PackMod"> | string
  optional?: Prisma.BoolFilter<"PackMod"> | boolean
  loadOrder?: Prisma.IntFilter<"PackMod"> | number
}

export type PackModCreateWithoutPackVersionInput = {
  id?: string
  optional: boolean
  loadOrder: number
  modFile: Prisma.ModFileCreateNestedOneWithoutPackModsInput
}

export type PackModUncheckedCreateWithoutPackVersionInput = {
  id?: string
  modFileId: string
  optional: boolean
  loadOrder: number
}

export type PackModCreateOrConnectWithoutPackVersionInput = {
  where: Prisma.PackModWhereUniqueInput
  create: Prisma.XOR<Prisma.PackModCreateWithoutPackVersionInput, Prisma.PackModUncheckedCreateWithoutPackVersionInput>
}

export type PackModCreateManyPackVersionInputEnvelope = {
  data: Prisma.PackModCreateManyPackVersionInput | Prisma.PackModCreateManyPackVersionInput[]
  skipDuplicates?: boolean
}

export type PackModUpsertWithWhereUniqueWithoutPackVersionInput = {
  where: Prisma.PackModWhereUniqueInput
  update: Prisma.XOR<Prisma.PackModUpdateWithoutPackVersionInput, Prisma.PackModUncheckedUpdateWithoutPackVersionInput>
  create: Prisma.XOR<Prisma.PackModCreateWithoutPackVersionInput, Prisma.PackModUncheckedCreateWithoutPackVersionInput>
}

export type PackModUpdateWithWhereUniqueWithoutPackVersionInput = {
  where: Prisma.PackModWhereUniqueInput
  data: Prisma.XOR<Prisma.PackModUpdateWithoutPackVersionInput, Prisma.PackModUncheckedUpdateWithoutPackVersionInput>
}

export type PackModUpdateManyWithWhereWithoutPackVersionInput = {
  where: Prisma.PackModScalarWhereInput
  data: Prisma.XOR<Prisma.PackModUpdateManyMutationInput, Prisma.PackModUncheckedUpdateManyWithoutPackVersionInput>
}

export type PackModCreateManyModFileInput = {
  id?: string
  packVersionId: string
  optional: boolean
  loadOrder: number
}

export type PackModUpdateWithoutModFileInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  optional?: Prisma.BoolFieldUpdateOperationsInput | boolean
  loadOrder?: Prisma.IntFieldUpdateOperationsInput | number
  packVersion?: Prisma.PackVersionUpdateOneRequiredWithoutPackModsNestedInput
}

export type PackModUncheckedUpdateWithoutModFileInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  packVersionId?: Prisma.StringFieldUpdateOperationsInput | string
  optional?: Prisma.BoolFieldUpdateOperationsInput | boolean
  loadOrder?: Prisma.IntFieldUpdateOperationsInput | number
}

export type PackModUncheckedUpdateManyWithoutModFileInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  packVersionId?: Prisma.StringFieldUpdateOperationsInput | string
  optional?: Prisma.BoolFieldUpdateOperationsInput | boolean
  loadOrder?: Prisma.IntFieldUpdateOperationsInput | number
}

export type PackModCreateManyPackVersionInput = {
  id?: string
  modFileId: string
  optional: boolean
  loadOrder: number
}

export type PackModUpdateWithoutPackVersionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  optional?: Prisma.BoolFieldUpdateOperationsInput | boolean
  loadOrder?: Prisma.IntFieldUpdateOperationsInput | number
  modFile?: Prisma.ModFileUpdateOneRequiredWithoutPackModsNestedInput
}

export type PackModUncheckedUpdateWithoutPackVersionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  modFileId?: Prisma.StringFieldUpdateOperationsInput | string
  optional?: Prisma.BoolFieldUpdateOperationsInput | boolean
  loadOrder?: Prisma.IntFieldUpdateOperationsInput | number
}

export type PackModUncheckedUpdateManyWithoutPackVersionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  modFileId?: Prisma.StringFieldUpdateOperationsInput | string
  optional?: Prisma.BoolFieldUpdateOperationsInput | boolean
  loadOrder?: Prisma.IntFieldUpdateOperationsInput | number
}



export type PackModSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  packVersionId?: boolean
  modFileId?: boolean
  optional?: boolean
  loadOrder?: boolean
  packVersion?: boolean | Prisma.PackVersionDefaultArgs<ExtArgs>
  modFile?: boolean | Prisma.ModFileDefaultArgs<ExtArgs>
}, ExtArgs["result"]["packMod"]>

export type PackModSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  packVersionId?: boolean
  modFileId?: boolean
  optional?: boolean
  loadOrder?: boolean
  packVersion?: boolean | Prisma.PackVersionDefaultArgs<ExtArgs>
  modFile?: boolean | Prisma.ModFileDefaultArgs<ExtArgs>
}, ExtArgs["result"]["packMod"]>

export type PackModSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  packVersionId?: boolean
  modFileId?: boolean
  optional?: boolean
  loadOrder?: boolean
  packVersion?: boolean | Prisma.PackVersionDefaultArgs<ExtArgs>
  modFile?: boolean | Prisma.ModFileDefaultArgs<ExtArgs>
}, ExtArgs["result"]["packMod"]>

export type PackModSelectScalar = {
  id?: boolean
  packVersionId?: boolean
  modFileId?: boolean
  optional?: boolean
  loadOrder?: boolean
}

export type PackModOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "packVersionId" | "modFileId" | "optional" | "loadOrder", ExtArgs["result"]["packMod"]>
export type PackModInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  packVersion?: boolean | Prisma.PackVersionDefaultArgs<ExtArgs>
  modFile?: boolean | Prisma.ModFileDefaultArgs<ExtArgs>
}
export type PackModIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  packVersion?: boolean | Prisma.PackVersionDefaultArgs<ExtArgs>
  modFile?: boolean | Prisma.ModFileDefaultArgs<ExtArgs>
}
export type PackModIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  packVersion?: boolean | Prisma.PackVersionDefaultArgs<ExtArgs>
  modFile?: boolean | Prisma.ModFileDefaultArgs<ExtArgs>
}

export type $PackModPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "PackMod"
  objects: {
    packVersion: Prisma.$PackVersionPayload<ExtArgs>
    modFile: Prisma.$ModFilePayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    packVersionId: string
    modFileId: string
    optional: boolean
    loadOrder: number
  }, ExtArgs["result"]["packMod"]>
  composites: {}
}

export type PackModGetPayload<S extends boolean | null | undefined | PackModDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$PackModPayload, S>

export type PackModCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<PackModFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: PackModCountAggregateInputType | true
  }

export interface PackModDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['PackMod'], meta: { name: 'PackMod' } }
  /**
   * Find zero or one PackMod that matches the filter.
   * @param {PackModFindUniqueArgs} args - Arguments to find a PackMod
   * @example
   * // Get one PackMod
   * const packMod = await prisma.packMod.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends PackModFindUniqueArgs>(args: Prisma.SelectSubset<T, PackModFindUniqueArgs<ExtArgs>>): Prisma.Prisma__PackModClient<runtime.Types.Result.GetResult<Prisma.$PackModPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one PackMod that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {PackModFindUniqueOrThrowArgs} args - Arguments to find a PackMod
   * @example
   * // Get one PackMod
   * const packMod = await prisma.packMod.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends PackModFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, PackModFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__PackModClient<runtime.Types.Result.GetResult<Prisma.$PackModPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PackMod that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PackModFindFirstArgs} args - Arguments to find a PackMod
   * @example
   * // Get one PackMod
   * const packMod = await prisma.packMod.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends PackModFindFirstArgs>(args?: Prisma.SelectSubset<T, PackModFindFirstArgs<ExtArgs>>): Prisma.Prisma__PackModClient<runtime.Types.Result.GetResult<Prisma.$PackModPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PackMod that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PackModFindFirstOrThrowArgs} args - Arguments to find a PackMod
   * @example
   * // Get one PackMod
   * const packMod = await prisma.packMod.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends PackModFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, PackModFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__PackModClient<runtime.Types.Result.GetResult<Prisma.$PackModPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more PackMods that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PackModFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all PackMods
   * const packMods = await prisma.packMod.findMany()
   * 
   * // Get first 10 PackMods
   * const packMods = await prisma.packMod.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const packModWithIdOnly = await prisma.packMod.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends PackModFindManyArgs>(args?: Prisma.SelectSubset<T, PackModFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PackModPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a PackMod.
   * @param {PackModCreateArgs} args - Arguments to create a PackMod.
   * @example
   * // Create one PackMod
   * const PackMod = await prisma.packMod.create({
   *   data: {
   *     // ... data to create a PackMod
   *   }
   * })
   * 
   */
  create<T extends PackModCreateArgs>(args: Prisma.SelectSubset<T, PackModCreateArgs<ExtArgs>>): Prisma.Prisma__PackModClient<runtime.Types.Result.GetResult<Prisma.$PackModPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many PackMods.
   * @param {PackModCreateManyArgs} args - Arguments to create many PackMods.
   * @example
   * // Create many PackMods
   * const packMod = await prisma.packMod.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends PackModCreateManyArgs>(args?: Prisma.SelectSubset<T, PackModCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many PackMods and returns the data saved in the database.
   * @param {PackModCreateManyAndReturnArgs} args - Arguments to create many PackMods.
   * @example
   * // Create many PackMods
   * const packMod = await prisma.packMod.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many PackMods and only return the `id`
   * const packModWithIdOnly = await prisma.packMod.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends PackModCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, PackModCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PackModPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a PackMod.
   * @param {PackModDeleteArgs} args - Arguments to delete one PackMod.
   * @example
   * // Delete one PackMod
   * const PackMod = await prisma.packMod.delete({
   *   where: {
   *     // ... filter to delete one PackMod
   *   }
   * })
   * 
   */
  delete<T extends PackModDeleteArgs>(args: Prisma.SelectSubset<T, PackModDeleteArgs<ExtArgs>>): Prisma.Prisma__PackModClient<runtime.Types.Result.GetResult<Prisma.$PackModPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one PackMod.
   * @param {PackModUpdateArgs} args - Arguments to update one PackMod.
   * @example
   * // Update one PackMod
   * const packMod = await prisma.packMod.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends PackModUpdateArgs>(args: Prisma.SelectSubset<T, PackModUpdateArgs<ExtArgs>>): Prisma.Prisma__PackModClient<runtime.Types.Result.GetResult<Prisma.$PackModPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more PackMods.
   * @param {PackModDeleteManyArgs} args - Arguments to filter PackMods to delete.
   * @example
   * // Delete a few PackMods
   * const { count } = await prisma.packMod.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends PackModDeleteManyArgs>(args?: Prisma.SelectSubset<T, PackModDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PackMods.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PackModUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many PackMods
   * const packMod = await prisma.packMod.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends PackModUpdateManyArgs>(args: Prisma.SelectSubset<T, PackModUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PackMods and returns the data updated in the database.
   * @param {PackModUpdateManyAndReturnArgs} args - Arguments to update many PackMods.
   * @example
   * // Update many PackMods
   * const packMod = await prisma.packMod.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more PackMods and only return the `id`
   * const packModWithIdOnly = await prisma.packMod.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends PackModUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, PackModUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PackModPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one PackMod.
   * @param {PackModUpsertArgs} args - Arguments to update or create a PackMod.
   * @example
   * // Update or create a PackMod
   * const packMod = await prisma.packMod.upsert({
   *   create: {
   *     // ... data to create a PackMod
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the PackMod we want to update
   *   }
   * })
   */
  upsert<T extends PackModUpsertArgs>(args: Prisma.SelectSubset<T, PackModUpsertArgs<ExtArgs>>): Prisma.Prisma__PackModClient<runtime.Types.Result.GetResult<Prisma.$PackModPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of PackMods.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PackModCountArgs} args - Arguments to filter PackMods to count.
   * @example
   * // Count the number of PackMods
   * const count = await prisma.packMod.count({
   *   where: {
   *     // ... the filter for the PackMods we want to count
   *   }
   * })
  **/
  count<T extends PackModCountArgs>(
    args?: Prisma.Subset<T, PackModCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], PackModCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a PackMod.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PackModAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends PackModAggregateArgs>(args: Prisma.Subset<T, PackModAggregateArgs>): Prisma.PrismaPromise<GetPackModAggregateType<T>>

  /**
   * Group by PackMod.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PackModGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends PackModGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: PackModGroupByArgs['orderBy'] }
      : { orderBy?: PackModGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, PackModGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetPackModGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the PackMod model
 */
readonly fields: PackModFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for PackMod.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__PackModClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  packVersion<T extends Prisma.PackVersionDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.PackVersionDefaultArgs<ExtArgs>>): Prisma.Prisma__PackVersionClient<runtime.Types.Result.GetResult<Prisma.$PackVersionPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  modFile<T extends Prisma.ModFileDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ModFileDefaultArgs<ExtArgs>>): Prisma.Prisma__ModFileClient<runtime.Types.Result.GetResult<Prisma.$ModFilePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the PackMod model
 */
export interface PackModFieldRefs {
  readonly id: Prisma.FieldRef<"PackMod", 'String'>
  readonly packVersionId: Prisma.FieldRef<"PackMod", 'String'>
  readonly modFileId: Prisma.FieldRef<"PackMod", 'String'>
  readonly optional: Prisma.FieldRef<"PackMod", 'Boolean'>
  readonly loadOrder: Prisma.FieldRef<"PackMod", 'Int'>
}
    

// Custom InputTypes
/**
 * PackMod findUnique
 */
export type PackModFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PackMod
   */
  select?: Prisma.PackModSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PackMod
   */
  omit?: Prisma.PackModOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PackModInclude<ExtArgs> | null
  /**
   * Filter, which PackMod to fetch.
   */
  where: Prisma.PackModWhereUniqueInput
}

/**
 * PackMod findUniqueOrThrow
 */
export type PackModFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PackMod
   */
  select?: Prisma.PackModSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PackMod
   */
  omit?: Prisma.PackModOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PackModInclude<ExtArgs> | null
  /**
   * Filter, which PackMod to fetch.
   */
  where: Prisma.PackModWhereUniqueInput
}

/**
 * PackMod findFirst
 */
export type PackModFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PackMod
   */
  select?: Prisma.PackModSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PackMod
   */
  omit?: Prisma.PackModOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PackModInclude<ExtArgs> | null
  /**
   * Filter, which PackMod to fetch.
   */
  where?: Prisma.PackModWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PackMods to fetch.
   */
  orderBy?: Prisma.PackModOrderByWithRelationInput | Prisma.PackModOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PackMods.
   */
  cursor?: Prisma.PackModWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PackMods from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PackMods.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PackMods.
   */
  distinct?: Prisma.PackModScalarFieldEnum | Prisma.PackModScalarFieldEnum[]
}

/**
 * PackMod findFirstOrThrow
 */
export type PackModFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PackMod
   */
  select?: Prisma.PackModSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PackMod
   */
  omit?: Prisma.PackModOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PackModInclude<ExtArgs> | null
  /**
   * Filter, which PackMod to fetch.
   */
  where?: Prisma.PackModWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PackMods to fetch.
   */
  orderBy?: Prisma.PackModOrderByWithRelationInput | Prisma.PackModOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PackMods.
   */
  cursor?: Prisma.PackModWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PackMods from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PackMods.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PackMods.
   */
  distinct?: Prisma.PackModScalarFieldEnum | Prisma.PackModScalarFieldEnum[]
}

/**
 * PackMod findMany
 */
export type PackModFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PackMod
   */
  select?: Prisma.PackModSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PackMod
   */
  omit?: Prisma.PackModOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PackModInclude<ExtArgs> | null
  /**
   * Filter, which PackMods to fetch.
   */
  where?: Prisma.PackModWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PackMods to fetch.
   */
  orderBy?: Prisma.PackModOrderByWithRelationInput | Prisma.PackModOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing PackMods.
   */
  cursor?: Prisma.PackModWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PackMods from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PackMods.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PackMods.
   */
  distinct?: Prisma.PackModScalarFieldEnum | Prisma.PackModScalarFieldEnum[]
}

/**
 * PackMod create
 */
export type PackModCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PackMod
   */
  select?: Prisma.PackModSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PackMod
   */
  omit?: Prisma.PackModOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PackModInclude<ExtArgs> | null
  /**
   * The data needed to create a PackMod.
   */
  data: Prisma.XOR<Prisma.PackModCreateInput, Prisma.PackModUncheckedCreateInput>
}

/**
 * PackMod createMany
 */
export type PackModCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many PackMods.
   */
  data: Prisma.PackModCreateManyInput | Prisma.PackModCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * PackMod createManyAndReturn
 */
export type PackModCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PackMod
   */
  select?: Prisma.PackModSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the PackMod
   */
  omit?: Prisma.PackModOmit<ExtArgs> | null
  /**
   * The data used to create many PackMods.
   */
  data: Prisma.PackModCreateManyInput | Prisma.PackModCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PackModIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * PackMod update
 */
export type PackModUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PackMod
   */
  select?: Prisma.PackModSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PackMod
   */
  omit?: Prisma.PackModOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PackModInclude<ExtArgs> | null
  /**
   * The data needed to update a PackMod.
   */
  data: Prisma.XOR<Prisma.PackModUpdateInput, Prisma.PackModUncheckedUpdateInput>
  /**
   * Choose, which PackMod to update.
   */
  where: Prisma.PackModWhereUniqueInput
}

/**
 * PackMod updateMany
 */
export type PackModUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update PackMods.
   */
  data: Prisma.XOR<Prisma.PackModUpdateManyMutationInput, Prisma.PackModUncheckedUpdateManyInput>
  /**
   * Filter which PackMods to update
   */
  where?: Prisma.PackModWhereInput
  /**
   * Limit how many PackMods to update.
   */
  limit?: number
}

/**
 * PackMod updateManyAndReturn
 */
export type PackModUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PackMod
   */
  select?: Prisma.PackModSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the PackMod
   */
  omit?: Prisma.PackModOmit<ExtArgs> | null
  /**
   * The data used to update PackMods.
   */
  data: Prisma.XOR<Prisma.PackModUpdateManyMutationInput, Prisma.PackModUncheckedUpdateManyInput>
  /**
   * Filter which PackMods to update
   */
  where?: Prisma.PackModWhereInput
  /**
   * Limit how many PackMods to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PackModIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * PackMod upsert
 */
export type PackModUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PackMod
   */
  select?: Prisma.PackModSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PackMod
   */
  omit?: Prisma.PackModOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PackModInclude<ExtArgs> | null
  /**
   * The filter to search for the PackMod to update in case it exists.
   */
  where: Prisma.PackModWhereUniqueInput
  /**
   * In case the PackMod found by the `where` argument doesn't exist, create a new PackMod with this data.
   */
  create: Prisma.XOR<Prisma.PackModCreateInput, Prisma.PackModUncheckedCreateInput>
  /**
   * In case the PackMod was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.PackModUpdateInput, Prisma.PackModUncheckedUpdateInput>
}

/**
 * PackMod delete
 */
export type PackModDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PackMod
   */
  select?: Prisma.PackModSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PackMod
   */
  omit?: Prisma.PackModOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PackModInclude<ExtArgs> | null
  /**
   * Filter which PackMod to delete.
   */
  where: Prisma.PackModWhereUniqueInput
}

/**
 * PackMod deleteMany
 */
export type PackModDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PackMods to delete
   */
  where?: Prisma.PackModWhereInput
  /**
   * Limit how many PackMods to delete.
   */
  limit?: number
}

/**
 * PackMod without action
 */
export type PackModDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PackMod
   */
  select?: Prisma.PackModSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PackMod
   */
  omit?: Prisma.PackModOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PackModInclude<ExtArgs> | null
}
