
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ShaderFile` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model ShaderFile
 * 
 */
export type ShaderFileModel = runtime.Types.Result.DefaultSelection<Prisma.$ShaderFilePayload>

export type AggregateShaderFile = {
  _count: ShaderFileCountAggregateOutputType | null
  _min: ShaderFileMinAggregateOutputType | null
  _max: ShaderFileMaxAggregateOutputType | null
}

export type ShaderFileMinAggregateOutputType = {
  id: string | null
  fileId: string | null
  shaderId: string | null
  version: string | null
  minecraftVersionId: string | null
  loaderId: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type ShaderFileMaxAggregateOutputType = {
  id: string | null
  fileId: string | null
  shaderId: string | null
  version: string | null
  minecraftVersionId: string | null
  loaderId: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type ShaderFileCountAggregateOutputType = {
  id: number
  fileId: number
  shaderId: number
  version: number
  minecraftVersionId: number
  loaderId: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type ShaderFileMinAggregateInputType = {
  id?: true
  fileId?: true
  shaderId?: true
  version?: true
  minecraftVersionId?: true
  loaderId?: true
  createdAt?: true
  updatedAt?: true
}

export type ShaderFileMaxAggregateInputType = {
  id?: true
  fileId?: true
  shaderId?: true
  version?: true
  minecraftVersionId?: true
  loaderId?: true
  createdAt?: true
  updatedAt?: true
}

export type ShaderFileCountAggregateInputType = {
  id?: true
  fileId?: true
  shaderId?: true
  version?: true
  minecraftVersionId?: true
  loaderId?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type ShaderFileAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ShaderFile to aggregate.
   */
  where?: Prisma.ShaderFileWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ShaderFiles to fetch.
   */
  orderBy?: Prisma.ShaderFileOrderByWithRelationInput | Prisma.ShaderFileOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ShaderFileWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ShaderFiles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ShaderFiles.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ShaderFiles
  **/
  _count?: true | ShaderFileCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ShaderFileMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ShaderFileMaxAggregateInputType
}

export type GetShaderFileAggregateType<T extends ShaderFileAggregateArgs> = {
      [P in keyof T & keyof AggregateShaderFile]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateShaderFile[P]>
    : Prisma.GetScalarType<T[P], AggregateShaderFile[P]>
}




export type ShaderFileGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ShaderFileWhereInput
  orderBy?: Prisma.ShaderFileOrderByWithAggregationInput | Prisma.ShaderFileOrderByWithAggregationInput[]
  by: Prisma.ShaderFileScalarFieldEnum[] | Prisma.ShaderFileScalarFieldEnum
  having?: Prisma.ShaderFileScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ShaderFileCountAggregateInputType | true
  _min?: ShaderFileMinAggregateInputType
  _max?: ShaderFileMaxAggregateInputType
}

export type ShaderFileGroupByOutputType = {
  id: string
  fileId: string | null
  shaderId: string | null
  version: string
  minecraftVersionId: string
  loaderId: string
  createdAt: Date
  updatedAt: Date
  _count: ShaderFileCountAggregateOutputType | null
  _min: ShaderFileMinAggregateOutputType | null
  _max: ShaderFileMaxAggregateOutputType | null
}

export type GetShaderFileGroupByPayload<T extends ShaderFileGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ShaderFileGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ShaderFileGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ShaderFileGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ShaderFileGroupByOutputType[P]>
      }
    >
  >



export type ShaderFileWhereInput = {
  AND?: Prisma.ShaderFileWhereInput | Prisma.ShaderFileWhereInput[]
  OR?: Prisma.ShaderFileWhereInput[]
  NOT?: Prisma.ShaderFileWhereInput | Prisma.ShaderFileWhereInput[]
  id?: Prisma.StringFilter<"ShaderFile"> | string
  fileId?: Prisma.StringNullableFilter<"ShaderFile"> | string | null
  shaderId?: Prisma.StringNullableFilter<"ShaderFile"> | string | null
  version?: Prisma.StringFilter<"ShaderFile"> | string
  minecraftVersionId?: Prisma.StringFilter<"ShaderFile"> | string
  loaderId?: Prisma.StringFilter<"ShaderFile"> | string
  createdAt?: Prisma.DateTimeFilter<"ShaderFile"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"ShaderFile"> | Date | string
  file?: Prisma.XOR<Prisma.FileNullableScalarRelationFilter, Prisma.FileWhereInput> | null
  shader?: Prisma.XOR<Prisma.ShaderNullableScalarRelationFilter, Prisma.ShaderWhereInput> | null
  minecraftVersion?: Prisma.XOR<Prisma.MinecraftVersionScalarRelationFilter, Prisma.MinecraftVersionWhereInput>
  loader?: Prisma.XOR<Prisma.MinecraftLoaderScalarRelationFilter, Prisma.MinecraftLoaderWhereInput>
  packShaders?: Prisma.PackShaderListRelationFilter
}

export type ShaderFileOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  fileId?: Prisma.SortOrderInput | Prisma.SortOrder
  shaderId?: Prisma.SortOrderInput | Prisma.SortOrder
  version?: Prisma.SortOrder
  minecraftVersionId?: Prisma.SortOrder
  loaderId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  file?: Prisma.FileOrderByWithRelationInput
  shader?: Prisma.ShaderOrderByWithRelationInput
  minecraftVersion?: Prisma.MinecraftVersionOrderByWithRelationInput
  loader?: Prisma.MinecraftLoaderOrderByWithRelationInput
  packShaders?: Prisma.PackShaderOrderByRelationAggregateInput
}

export type ShaderFileWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  fileId?: string
  AND?: Prisma.ShaderFileWhereInput | Prisma.ShaderFileWhereInput[]
  OR?: Prisma.ShaderFileWhereInput[]
  NOT?: Prisma.ShaderFileWhereInput | Prisma.ShaderFileWhereInput[]
  shaderId?: Prisma.StringNullableFilter<"ShaderFile"> | string | null
  version?: Prisma.StringFilter<"ShaderFile"> | string
  minecraftVersionId?: Prisma.StringFilter<"ShaderFile"> | string
  loaderId?: Prisma.StringFilter<"ShaderFile"> | string
  createdAt?: Prisma.DateTimeFilter<"ShaderFile"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"ShaderFile"> | Date | string
  file?: Prisma.XOR<Prisma.FileNullableScalarRelationFilter, Prisma.FileWhereInput> | null
  shader?: Prisma.XOR<Prisma.ShaderNullableScalarRelationFilter, Prisma.ShaderWhereInput> | null
  minecraftVersion?: Prisma.XOR<Prisma.MinecraftVersionScalarRelationFilter, Prisma.MinecraftVersionWhereInput>
  loader?: Prisma.XOR<Prisma.MinecraftLoaderScalarRelationFilter, Prisma.MinecraftLoaderWhereInput>
  packShaders?: Prisma.PackShaderListRelationFilter
}, "id" | "fileId">

export type ShaderFileOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  fileId?: Prisma.SortOrderInput | Prisma.SortOrder
  shaderId?: Prisma.SortOrderInput | Prisma.SortOrder
  version?: Prisma.SortOrder
  minecraftVersionId?: Prisma.SortOrder
  loaderId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.ShaderFileCountOrderByAggregateInput
  _max?: Prisma.ShaderFileMaxOrderByAggregateInput
  _min?: Prisma.ShaderFileMinOrderByAggregateInput
}

export type ShaderFileScalarWhereWithAggregatesInput = {
  AND?: Prisma.ShaderFileScalarWhereWithAggregatesInput | Prisma.ShaderFileScalarWhereWithAggregatesInput[]
  OR?: Prisma.ShaderFileScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ShaderFileScalarWhereWithAggregatesInput | Prisma.ShaderFileScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"ShaderFile"> | string
  fileId?: Prisma.StringNullableWithAggregatesFilter<"ShaderFile"> | string | null
  shaderId?: Prisma.StringNullableWithAggregatesFilter<"ShaderFile"> | string | null
  version?: Prisma.StringWithAggregatesFilter<"ShaderFile"> | string
  minecraftVersionId?: Prisma.StringWithAggregatesFilter<"ShaderFile"> | string
  loaderId?: Prisma.StringWithAggregatesFilter<"ShaderFile"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"ShaderFile"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"ShaderFile"> | Date | string
}

export type ShaderFileCreateInput = {
  id?: string
  version: string
  createdAt?: Date | string
  updatedAt?: Date | string
  file?: Prisma.FileCreateNestedOneWithoutShaderFileInput
  shader?: Prisma.ShaderCreateNestedOneWithoutShaderFilesInput
  minecraftVersion: Prisma.MinecraftVersionCreateNestedOneWithoutShaderFilesInput
  loader: Prisma.MinecraftLoaderCreateNestedOneWithoutShaderFilesInput
  packShaders?: Prisma.PackShaderCreateNestedManyWithoutShaderFileInput
}

export type ShaderFileUncheckedCreateInput = {
  id?: string
  fileId?: string | null
  shaderId?: string | null
  version: string
  minecraftVersionId: string
  loaderId: string
  createdAt?: Date | string
  updatedAt?: Date | string
  packShaders?: Prisma.PackShaderUncheckedCreateNestedManyWithoutShaderFileInput
}

export type ShaderFileUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  version?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  file?: Prisma.FileUpdateOneWithoutShaderFileNestedInput
  shader?: Prisma.ShaderUpdateOneWithoutShaderFilesNestedInput
  minecraftVersion?: Prisma.MinecraftVersionUpdateOneRequiredWithoutShaderFilesNestedInput
  loader?: Prisma.MinecraftLoaderUpdateOneRequiredWithoutShaderFilesNestedInput
  packShaders?: Prisma.PackShaderUpdateManyWithoutShaderFileNestedInput
}

export type ShaderFileUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fileId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  shaderId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  version?: Prisma.StringFieldUpdateOperationsInput | string
  minecraftVersionId?: Prisma.StringFieldUpdateOperationsInput | string
  loaderId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  packShaders?: Prisma.PackShaderUncheckedUpdateManyWithoutShaderFileNestedInput
}

export type ShaderFileCreateManyInput = {
  id?: string
  fileId?: string | null
  shaderId?: string | null
  version: string
  minecraftVersionId: string
  loaderId: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ShaderFileUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  version?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ShaderFileUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fileId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  shaderId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  version?: Prisma.StringFieldUpdateOperationsInput | string
  minecraftVersionId?: Prisma.StringFieldUpdateOperationsInput | string
  loaderId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ShaderFileNullableScalarRelationFilter = {
  is?: Prisma.ShaderFileWhereInput | null
  isNot?: Prisma.ShaderFileWhereInput | null
}

export type ShaderFileListRelationFilter = {
  every?: Prisma.ShaderFileWhereInput
  some?: Prisma.ShaderFileWhereInput
  none?: Prisma.ShaderFileWhereInput
}

export type ShaderFileOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type ShaderFileCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  fileId?: Prisma.SortOrder
  shaderId?: Prisma.SortOrder
  version?: Prisma.SortOrder
  minecraftVersionId?: Prisma.SortOrder
  loaderId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ShaderFileMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  fileId?: Prisma.SortOrder
  shaderId?: Prisma.SortOrder
  version?: Prisma.SortOrder
  minecraftVersionId?: Prisma.SortOrder
  loaderId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ShaderFileMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  fileId?: Prisma.SortOrder
  shaderId?: Prisma.SortOrder
  version?: Prisma.SortOrder
  minecraftVersionId?: Prisma.SortOrder
  loaderId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ShaderFileScalarRelationFilter = {
  is?: Prisma.ShaderFileWhereInput
  isNot?: Prisma.ShaderFileWhereInput
}

export type ShaderFileCreateNestedOneWithoutFileInput = {
  create?: Prisma.XOR<Prisma.ShaderFileCreateWithoutFileInput, Prisma.ShaderFileUncheckedCreateWithoutFileInput>
  connectOrCreate?: Prisma.ShaderFileCreateOrConnectWithoutFileInput
  connect?: Prisma.ShaderFileWhereUniqueInput
}

export type ShaderFileUncheckedCreateNestedOneWithoutFileInput = {
  create?: Prisma.XOR<Prisma.ShaderFileCreateWithoutFileInput, Prisma.ShaderFileUncheckedCreateWithoutFileInput>
  connectOrCreate?: Prisma.ShaderFileCreateOrConnectWithoutFileInput
  connect?: Prisma.ShaderFileWhereUniqueInput
}

export type ShaderFileUpdateOneWithoutFileNestedInput = {
  create?: Prisma.XOR<Prisma.ShaderFileCreateWithoutFileInput, Prisma.ShaderFileUncheckedCreateWithoutFileInput>
  connectOrCreate?: Prisma.ShaderFileCreateOrConnectWithoutFileInput
  upsert?: Prisma.ShaderFileUpsertWithoutFileInput
  disconnect?: Prisma.ShaderFileWhereInput | boolean
  delete?: Prisma.ShaderFileWhereInput | boolean
  connect?: Prisma.ShaderFileWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ShaderFileUpdateToOneWithWhereWithoutFileInput, Prisma.ShaderFileUpdateWithoutFileInput>, Prisma.ShaderFileUncheckedUpdateWithoutFileInput>
}

export type ShaderFileUncheckedUpdateOneWithoutFileNestedInput = {
  create?: Prisma.XOR<Prisma.ShaderFileCreateWithoutFileInput, Prisma.ShaderFileUncheckedCreateWithoutFileInput>
  connectOrCreate?: Prisma.ShaderFileCreateOrConnectWithoutFileInput
  upsert?: Prisma.ShaderFileUpsertWithoutFileInput
  disconnect?: Prisma.ShaderFileWhereInput | boolean
  delete?: Prisma.ShaderFileWhereInput | boolean
  connect?: Prisma.ShaderFileWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ShaderFileUpdateToOneWithWhereWithoutFileInput, Prisma.ShaderFileUpdateWithoutFileInput>, Prisma.ShaderFileUncheckedUpdateWithoutFileInput>
}

export type ShaderFileCreateNestedManyWithoutMinecraftVersionInput = {
  create?: Prisma.XOR<Prisma.ShaderFileCreateWithoutMinecraftVersionInput, Prisma.ShaderFileUncheckedCreateWithoutMinecraftVersionInput> | Prisma.ShaderFileCreateWithoutMinecraftVersionInput[] | Prisma.ShaderFileUncheckedCreateWithoutMinecraftVersionInput[]
  connectOrCreate?: Prisma.ShaderFileCreateOrConnectWithoutMinecraftVersionInput | Prisma.ShaderFileCreateOrConnectWithoutMinecraftVersionInput[]
  createMany?: Prisma.ShaderFileCreateManyMinecraftVersionInputEnvelope
  connect?: Prisma.ShaderFileWhereUniqueInput | Prisma.ShaderFileWhereUniqueInput[]
}

export type ShaderFileUncheckedCreateNestedManyWithoutMinecraftVersionInput = {
  create?: Prisma.XOR<Prisma.ShaderFileCreateWithoutMinecraftVersionInput, Prisma.ShaderFileUncheckedCreateWithoutMinecraftVersionInput> | Prisma.ShaderFileCreateWithoutMinecraftVersionInput[] | Prisma.ShaderFileUncheckedCreateWithoutMinecraftVersionInput[]
  connectOrCreate?: Prisma.ShaderFileCreateOrConnectWithoutMinecraftVersionInput | Prisma.ShaderFileCreateOrConnectWithoutMinecraftVersionInput[]
  createMany?: Prisma.ShaderFileCreateManyMinecraftVersionInputEnvelope
  connect?: Prisma.ShaderFileWhereUniqueInput | Prisma.ShaderFileWhereUniqueInput[]
}

export type ShaderFileUpdateManyWithoutMinecraftVersionNestedInput = {
  create?: Prisma.XOR<Prisma.ShaderFileCreateWithoutMinecraftVersionInput, Prisma.ShaderFileUncheckedCreateWithoutMinecraftVersionInput> | Prisma.ShaderFileCreateWithoutMinecraftVersionInput[] | Prisma.ShaderFileUncheckedCreateWithoutMinecraftVersionInput[]
  connectOrCreate?: Prisma.ShaderFileCreateOrConnectWithoutMinecraftVersionInput | Prisma.ShaderFileCreateOrConnectWithoutMinecraftVersionInput[]
  upsert?: Prisma.ShaderFileUpsertWithWhereUniqueWithoutMinecraftVersionInput | Prisma.ShaderFileUpsertWithWhereUniqueWithoutMinecraftVersionInput[]
  createMany?: Prisma.ShaderFileCreateManyMinecraftVersionInputEnvelope
  set?: Prisma.ShaderFileWhereUniqueInput | Prisma.ShaderFileWhereUniqueInput[]
  disconnect?: Prisma.ShaderFileWhereUniqueInput | Prisma.ShaderFileWhereUniqueInput[]
  delete?: Prisma.ShaderFileWhereUniqueInput | Prisma.ShaderFileWhereUniqueInput[]
  connect?: Prisma.ShaderFileWhereUniqueInput | Prisma.ShaderFileWhereUniqueInput[]
  update?: Prisma.ShaderFileUpdateWithWhereUniqueWithoutMinecraftVersionInput | Prisma.ShaderFileUpdateWithWhereUniqueWithoutMinecraftVersionInput[]
  updateMany?: Prisma.ShaderFileUpdateManyWithWhereWithoutMinecraftVersionInput | Prisma.ShaderFileUpdateManyWithWhereWithoutMinecraftVersionInput[]
  deleteMany?: Prisma.ShaderFileScalarWhereInput | Prisma.ShaderFileScalarWhereInput[]
}

export type ShaderFileUncheckedUpdateManyWithoutMinecraftVersionNestedInput = {
  create?: Prisma.XOR<Prisma.ShaderFileCreateWithoutMinecraftVersionInput, Prisma.ShaderFileUncheckedCreateWithoutMinecraftVersionInput> | Prisma.ShaderFileCreateWithoutMinecraftVersionInput[] | Prisma.ShaderFileUncheckedCreateWithoutMinecraftVersionInput[]
  connectOrCreate?: Prisma.ShaderFileCreateOrConnectWithoutMinecraftVersionInput | Prisma.ShaderFileCreateOrConnectWithoutMinecraftVersionInput[]
  upsert?: Prisma.ShaderFileUpsertWithWhereUniqueWithoutMinecraftVersionInput | Prisma.ShaderFileUpsertWithWhereUniqueWithoutMinecraftVersionInput[]
  createMany?: Prisma.ShaderFileCreateManyMinecraftVersionInputEnvelope
  set?: Prisma.ShaderFileWhereUniqueInput | Prisma.ShaderFileWhereUniqueInput[]
  disconnect?: Prisma.ShaderFileWhereUniqueInput | Prisma.ShaderFileWhereUniqueInput[]
  delete?: Prisma.ShaderFileWhereUniqueInput | Prisma.ShaderFileWhereUniqueInput[]
  connect?: Prisma.ShaderFileWhereUniqueInput | Prisma.ShaderFileWhereUniqueInput[]
  update?: Prisma.ShaderFileUpdateWithWhereUniqueWithoutMinecraftVersionInput | Prisma.ShaderFileUpdateWithWhereUniqueWithoutMinecraftVersionInput[]
  updateMany?: Prisma.ShaderFileUpdateManyWithWhereWithoutMinecraftVersionInput | Prisma.ShaderFileUpdateManyWithWhereWithoutMinecraftVersionInput[]
  deleteMany?: Prisma.ShaderFileScalarWhereInput | Prisma.ShaderFileScalarWhereInput[]
}

export type ShaderFileCreateNestedManyWithoutLoaderInput = {
  create?: Prisma.XOR<Prisma.ShaderFileCreateWithoutLoaderInput, Prisma.ShaderFileUncheckedCreateWithoutLoaderInput> | Prisma.ShaderFileCreateWithoutLoaderInput[] | Prisma.ShaderFileUncheckedCreateWithoutLoaderInput[]
  connectOrCreate?: Prisma.ShaderFileCreateOrConnectWithoutLoaderInput | Prisma.ShaderFileCreateOrConnectWithoutLoaderInput[]
  createMany?: Prisma.ShaderFileCreateManyLoaderInputEnvelope
  connect?: Prisma.ShaderFileWhereUniqueInput | Prisma.ShaderFileWhereUniqueInput[]
}

export type ShaderFileUncheckedCreateNestedManyWithoutLoaderInput = {
  create?: Prisma.XOR<Prisma.ShaderFileCreateWithoutLoaderInput, Prisma.ShaderFileUncheckedCreateWithoutLoaderInput> | Prisma.ShaderFileCreateWithoutLoaderInput[] | Prisma.ShaderFileUncheckedCreateWithoutLoaderInput[]
  connectOrCreate?: Prisma.ShaderFileCreateOrConnectWithoutLoaderInput | Prisma.ShaderFileCreateOrConnectWithoutLoaderInput[]
  createMany?: Prisma.ShaderFileCreateManyLoaderInputEnvelope
  connect?: Prisma.ShaderFileWhereUniqueInput | Prisma.ShaderFileWhereUniqueInput[]
}

export type ShaderFileUpdateManyWithoutLoaderNestedInput = {
  create?: Prisma.XOR<Prisma.ShaderFileCreateWithoutLoaderInput, Prisma.ShaderFileUncheckedCreateWithoutLoaderInput> | Prisma.ShaderFileCreateWithoutLoaderInput[] | Prisma.ShaderFileUncheckedCreateWithoutLoaderInput[]
  connectOrCreate?: Prisma.ShaderFileCreateOrConnectWithoutLoaderInput | Prisma.ShaderFileCreateOrConnectWithoutLoaderInput[]
  upsert?: Prisma.ShaderFileUpsertWithWhereUniqueWithoutLoaderInput | Prisma.ShaderFileUpsertWithWhereUniqueWithoutLoaderInput[]
  createMany?: Prisma.ShaderFileCreateManyLoaderInputEnvelope
  set?: Prisma.ShaderFileWhereUniqueInput | Prisma.ShaderFileWhereUniqueInput[]
  disconnect?: Prisma.ShaderFileWhereUniqueInput | Prisma.ShaderFileWhereUniqueInput[]
  delete?: Prisma.ShaderFileWhereUniqueInput | Prisma.ShaderFileWhereUniqueInput[]
  connect?: Prisma.ShaderFileWhereUniqueInput | Prisma.ShaderFileWhereUniqueInput[]
  update?: Prisma.ShaderFileUpdateWithWhereUniqueWithoutLoaderInput | Prisma.ShaderFileUpdateWithWhereUniqueWithoutLoaderInput[]
  updateMany?: Prisma.ShaderFileUpdateManyWithWhereWithoutLoaderInput | Prisma.ShaderFileUpdateManyWithWhereWithoutLoaderInput[]
  deleteMany?: Prisma.ShaderFileScalarWhereInput | Prisma.ShaderFileScalarWhereInput[]
}

export type ShaderFileUncheckedUpdateManyWithoutLoaderNestedInput = {
  create?: Prisma.XOR<Prisma.ShaderFileCreateWithoutLoaderInput, Prisma.ShaderFileUncheckedCreateWithoutLoaderInput> | Prisma.ShaderFileCreateWithoutLoaderInput[] | Prisma.ShaderFileUncheckedCreateWithoutLoaderInput[]
  connectOrCreate?: Prisma.ShaderFileCreateOrConnectWithoutLoaderInput | Prisma.ShaderFileCreateOrConnectWithoutLoaderInput[]
  upsert?: Prisma.ShaderFileUpsertWithWhereUniqueWithoutLoaderInput | Prisma.ShaderFileUpsertWithWhereUniqueWithoutLoaderInput[]
  createMany?: Prisma.ShaderFileCreateManyLoaderInputEnvelope
  set?: Prisma.ShaderFileWhereUniqueInput | Prisma.ShaderFileWhereUniqueInput[]
  disconnect?: Prisma.ShaderFileWhereUniqueInput | Prisma.ShaderFileWhereUniqueInput[]
  delete?: Prisma.ShaderFileWhereUniqueInput | Prisma.ShaderFileWhereUniqueInput[]
  connect?: Prisma.ShaderFileWhereUniqueInput | Prisma.ShaderFileWhereUniqueInput[]
  update?: Prisma.ShaderFileUpdateWithWhereUniqueWithoutLoaderInput | Prisma.ShaderFileUpdateWithWhereUniqueWithoutLoaderInput[]
  updateMany?: Prisma.ShaderFileUpdateManyWithWhereWithoutLoaderInput | Prisma.ShaderFileUpdateManyWithWhereWithoutLoaderInput[]
  deleteMany?: Prisma.ShaderFileScalarWhereInput | Prisma.ShaderFileScalarWhereInput[]
}

export type ShaderFileCreateNestedManyWithoutShaderInput = {
  create?: Prisma.XOR<Prisma.ShaderFileCreateWithoutShaderInput, Prisma.ShaderFileUncheckedCreateWithoutShaderInput> | Prisma.ShaderFileCreateWithoutShaderInput[] | Prisma.ShaderFileUncheckedCreateWithoutShaderInput[]
  connectOrCreate?: Prisma.ShaderFileCreateOrConnectWithoutShaderInput | Prisma.ShaderFileCreateOrConnectWithoutShaderInput[]
  createMany?: Prisma.ShaderFileCreateManyShaderInputEnvelope
  connect?: Prisma.ShaderFileWhereUniqueInput | Prisma.ShaderFileWhereUniqueInput[]
}

export type ShaderFileUncheckedCreateNestedManyWithoutShaderInput = {
  create?: Prisma.XOR<Prisma.ShaderFileCreateWithoutShaderInput, Prisma.ShaderFileUncheckedCreateWithoutShaderInput> | Prisma.ShaderFileCreateWithoutShaderInput[] | Prisma.ShaderFileUncheckedCreateWithoutShaderInput[]
  connectOrCreate?: Prisma.ShaderFileCreateOrConnectWithoutShaderInput | Prisma.ShaderFileCreateOrConnectWithoutShaderInput[]
  createMany?: Prisma.ShaderFileCreateManyShaderInputEnvelope
  connect?: Prisma.ShaderFileWhereUniqueInput | Prisma.ShaderFileWhereUniqueInput[]
}

export type ShaderFileUpdateManyWithoutShaderNestedInput = {
  create?: Prisma.XOR<Prisma.ShaderFileCreateWithoutShaderInput, Prisma.ShaderFileUncheckedCreateWithoutShaderInput> | Prisma.ShaderFileCreateWithoutShaderInput[] | Prisma.ShaderFileUncheckedCreateWithoutShaderInput[]
  connectOrCreate?: Prisma.ShaderFileCreateOrConnectWithoutShaderInput | Prisma.ShaderFileCreateOrConnectWithoutShaderInput[]
  upsert?: Prisma.ShaderFileUpsertWithWhereUniqueWithoutShaderInput | Prisma.ShaderFileUpsertWithWhereUniqueWithoutShaderInput[]
  createMany?: Prisma.ShaderFileCreateManyShaderInputEnvelope
  set?: Prisma.ShaderFileWhereUniqueInput | Prisma.ShaderFileWhereUniqueInput[]
  disconnect?: Prisma.ShaderFileWhereUniqueInput | Prisma.ShaderFileWhereUniqueInput[]
  delete?: Prisma.ShaderFileWhereUniqueInput | Prisma.ShaderFileWhereUniqueInput[]
  connect?: Prisma.ShaderFileWhereUniqueInput | Prisma.ShaderFileWhereUniqueInput[]
  update?: Prisma.ShaderFileUpdateWithWhereUniqueWithoutShaderInput | Prisma.ShaderFileUpdateWithWhereUniqueWithoutShaderInput[]
  updateMany?: Prisma.ShaderFileUpdateManyWithWhereWithoutShaderInput | Prisma.ShaderFileUpdateManyWithWhereWithoutShaderInput[]
  deleteMany?: Prisma.ShaderFileScalarWhereInput | Prisma.ShaderFileScalarWhereInput[]
}

export type ShaderFileUncheckedUpdateManyWithoutShaderNestedInput = {
  create?: Prisma.XOR<Prisma.ShaderFileCreateWithoutShaderInput, Prisma.ShaderFileUncheckedCreateWithoutShaderInput> | Prisma.ShaderFileCreateWithoutShaderInput[] | Prisma.ShaderFileUncheckedCreateWithoutShaderInput[]
  connectOrCreate?: Prisma.ShaderFileCreateOrConnectWithoutShaderInput | Prisma.ShaderFileCreateOrConnectWithoutShaderInput[]
  upsert?: Prisma.ShaderFileUpsertWithWhereUniqueWithoutShaderInput | Prisma.ShaderFileUpsertWithWhereUniqueWithoutShaderInput[]
  createMany?: Prisma.ShaderFileCreateManyShaderInputEnvelope
  set?: Prisma.ShaderFileWhereUniqueInput | Prisma.ShaderFileWhereUniqueInput[]
  disconnect?: Prisma.ShaderFileWhereUniqueInput | Prisma.ShaderFileWhereUniqueInput[]
  delete?: Prisma.ShaderFileWhereUniqueInput | Prisma.ShaderFileWhereUniqueInput[]
  connect?: Prisma.ShaderFileWhereUniqueInput | Prisma.ShaderFileWhereUniqueInput[]
  update?: Prisma.ShaderFileUpdateWithWhereUniqueWithoutShaderInput | Prisma.ShaderFileUpdateWithWhereUniqueWithoutShaderInput[]
  updateMany?: Prisma.ShaderFileUpdateManyWithWhereWithoutShaderInput | Prisma.ShaderFileUpdateManyWithWhereWithoutShaderInput[]
  deleteMany?: Prisma.ShaderFileScalarWhereInput | Prisma.ShaderFileScalarWhereInput[]
}

export type ShaderFileCreateNestedOneWithoutPackShadersInput = {
  create?: Prisma.XOR<Prisma.ShaderFileCreateWithoutPackShadersInput, Prisma.ShaderFileUncheckedCreateWithoutPackShadersInput>
  connectOrCreate?: Prisma.ShaderFileCreateOrConnectWithoutPackShadersInput
  connect?: Prisma.ShaderFileWhereUniqueInput
}

export type ShaderFileUpdateOneRequiredWithoutPackShadersNestedInput = {
  create?: Prisma.XOR<Prisma.ShaderFileCreateWithoutPackShadersInput, Prisma.ShaderFileUncheckedCreateWithoutPackShadersInput>
  connectOrCreate?: Prisma.ShaderFileCreateOrConnectWithoutPackShadersInput
  upsert?: Prisma.ShaderFileUpsertWithoutPackShadersInput
  connect?: Prisma.ShaderFileWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ShaderFileUpdateToOneWithWhereWithoutPackShadersInput, Prisma.ShaderFileUpdateWithoutPackShadersInput>, Prisma.ShaderFileUncheckedUpdateWithoutPackShadersInput>
}

export type ShaderFileCreateWithoutFileInput = {
  id?: string
  version: string
  createdAt?: Date | string
  updatedAt?: Date | string
  shader?: Prisma.ShaderCreateNestedOneWithoutShaderFilesInput
  minecraftVersion: Prisma.MinecraftVersionCreateNestedOneWithoutShaderFilesInput
  loader: Prisma.MinecraftLoaderCreateNestedOneWithoutShaderFilesInput
  packShaders?: Prisma.PackShaderCreateNestedManyWithoutShaderFileInput
}

export type ShaderFileUncheckedCreateWithoutFileInput = {
  id?: string
  shaderId?: string | null
  version: string
  minecraftVersionId: string
  loaderId: string
  createdAt?: Date | string
  updatedAt?: Date | string
  packShaders?: Prisma.PackShaderUncheckedCreateNestedManyWithoutShaderFileInput
}

export type ShaderFileCreateOrConnectWithoutFileInput = {
  where: Prisma.ShaderFileWhereUniqueInput
  create: Prisma.XOR<Prisma.ShaderFileCreateWithoutFileInput, Prisma.ShaderFileUncheckedCreateWithoutFileInput>
}

export type ShaderFileUpsertWithoutFileInput = {
  update: Prisma.XOR<Prisma.ShaderFileUpdateWithoutFileInput, Prisma.ShaderFileUncheckedUpdateWithoutFileInput>
  create: Prisma.XOR<Prisma.ShaderFileCreateWithoutFileInput, Prisma.ShaderFileUncheckedCreateWithoutFileInput>
  where?: Prisma.ShaderFileWhereInput
}

export type ShaderFileUpdateToOneWithWhereWithoutFileInput = {
  where?: Prisma.ShaderFileWhereInput
  data: Prisma.XOR<Prisma.ShaderFileUpdateWithoutFileInput, Prisma.ShaderFileUncheckedUpdateWithoutFileInput>
}

export type ShaderFileUpdateWithoutFileInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  version?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  shader?: Prisma.ShaderUpdateOneWithoutShaderFilesNestedInput
  minecraftVersion?: Prisma.MinecraftVersionUpdateOneRequiredWithoutShaderFilesNestedInput
  loader?: Prisma.MinecraftLoaderUpdateOneRequiredWithoutShaderFilesNestedInput
  packShaders?: Prisma.PackShaderUpdateManyWithoutShaderFileNestedInput
}

export type ShaderFileUncheckedUpdateWithoutFileInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  shaderId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  version?: Prisma.StringFieldUpdateOperationsInput | string
  minecraftVersionId?: Prisma.StringFieldUpdateOperationsInput | string
  loaderId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  packShaders?: Prisma.PackShaderUncheckedUpdateManyWithoutShaderFileNestedInput
}

export type ShaderFileCreateWithoutMinecraftVersionInput = {
  id?: string
  version: string
  createdAt?: Date | string
  updatedAt?: Date | string
  file?: Prisma.FileCreateNestedOneWithoutShaderFileInput
  shader?: Prisma.ShaderCreateNestedOneWithoutShaderFilesInput
  loader: Prisma.MinecraftLoaderCreateNestedOneWithoutShaderFilesInput
  packShaders?: Prisma.PackShaderCreateNestedManyWithoutShaderFileInput
}

export type ShaderFileUncheckedCreateWithoutMinecraftVersionInput = {
  id?: string
  fileId?: string | null
  shaderId?: string | null
  version: string
  loaderId: string
  createdAt?: Date | string
  updatedAt?: Date | string
  packShaders?: Prisma.PackShaderUncheckedCreateNestedManyWithoutShaderFileInput
}

export type ShaderFileCreateOrConnectWithoutMinecraftVersionInput = {
  where: Prisma.ShaderFileWhereUniqueInput
  create: Prisma.XOR<Prisma.ShaderFileCreateWithoutMinecraftVersionInput, Prisma.ShaderFileUncheckedCreateWithoutMinecraftVersionInput>
}

export type ShaderFileCreateManyMinecraftVersionInputEnvelope = {
  data: Prisma.ShaderFileCreateManyMinecraftVersionInput | Prisma.ShaderFileCreateManyMinecraftVersionInput[]
  skipDuplicates?: boolean
}

export type ShaderFileUpsertWithWhereUniqueWithoutMinecraftVersionInput = {
  where: Prisma.ShaderFileWhereUniqueInput
  update: Prisma.XOR<Prisma.ShaderFileUpdateWithoutMinecraftVersionInput, Prisma.ShaderFileUncheckedUpdateWithoutMinecraftVersionInput>
  create: Prisma.XOR<Prisma.ShaderFileCreateWithoutMinecraftVersionInput, Prisma.ShaderFileUncheckedCreateWithoutMinecraftVersionInput>
}

export type ShaderFileUpdateWithWhereUniqueWithoutMinecraftVersionInput = {
  where: Prisma.ShaderFileWhereUniqueInput
  data: Prisma.XOR<Prisma.ShaderFileUpdateWithoutMinecraftVersionInput, Prisma.ShaderFileUncheckedUpdateWithoutMinecraftVersionInput>
}

export type ShaderFileUpdateManyWithWhereWithoutMinecraftVersionInput = {
  where: Prisma.ShaderFileScalarWhereInput
  data: Prisma.XOR<Prisma.ShaderFileUpdateManyMutationInput, Prisma.ShaderFileUncheckedUpdateManyWithoutMinecraftVersionInput>
}

export type ShaderFileScalarWhereInput = {
  AND?: Prisma.ShaderFileScalarWhereInput | Prisma.ShaderFileScalarWhereInput[]
  OR?: Prisma.ShaderFileScalarWhereInput[]
  NOT?: Prisma.ShaderFileScalarWhereInput | Prisma.ShaderFileScalarWhereInput[]
  id?: Prisma.StringFilter<"ShaderFile"> | string
  fileId?: Prisma.StringNullableFilter<"ShaderFile"> | string | null
  shaderId?: Prisma.StringNullableFilter<"ShaderFile"> | string | null
  version?: Prisma.StringFilter<"ShaderFile"> | string
  minecraftVersionId?: Prisma.StringFilter<"ShaderFile"> | string
  loaderId?: Prisma.StringFilter<"ShaderFile"> | string
  createdAt?: Prisma.DateTimeFilter<"ShaderFile"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"ShaderFile"> | Date | string
}

export type ShaderFileCreateWithoutLoaderInput = {
  id?: string
  version: string
  createdAt?: Date | string
  updatedAt?: Date | string
  file?: Prisma.FileCreateNestedOneWithoutShaderFileInput
  shader?: Prisma.ShaderCreateNestedOneWithoutShaderFilesInput
  minecraftVersion: Prisma.MinecraftVersionCreateNestedOneWithoutShaderFilesInput
  packShaders?: Prisma.PackShaderCreateNestedManyWithoutShaderFileInput
}

export type ShaderFileUncheckedCreateWithoutLoaderInput = {
  id?: string
  fileId?: string | null
  shaderId?: string | null
  version: string
  minecraftVersionId: string
  createdAt?: Date | string
  updatedAt?: Date | string
  packShaders?: Prisma.PackShaderUncheckedCreateNestedManyWithoutShaderFileInput
}

export type ShaderFileCreateOrConnectWithoutLoaderInput = {
  where: Prisma.ShaderFileWhereUniqueInput
  create: Prisma.XOR<Prisma.ShaderFileCreateWithoutLoaderInput, Prisma.ShaderFileUncheckedCreateWithoutLoaderInput>
}

export type ShaderFileCreateManyLoaderInputEnvelope = {
  data: Prisma.ShaderFileCreateManyLoaderInput | Prisma.ShaderFileCreateManyLoaderInput[]
  skipDuplicates?: boolean
}

export type ShaderFileUpsertWithWhereUniqueWithoutLoaderInput = {
  where: Prisma.ShaderFileWhereUniqueInput
  update: Prisma.XOR<Prisma.ShaderFileUpdateWithoutLoaderInput, Prisma.ShaderFileUncheckedUpdateWithoutLoaderInput>
  create: Prisma.XOR<Prisma.ShaderFileCreateWithoutLoaderInput, Prisma.ShaderFileUncheckedCreateWithoutLoaderInput>
}

export type ShaderFileUpdateWithWhereUniqueWithoutLoaderInput = {
  where: Prisma.ShaderFileWhereUniqueInput
  data: Prisma.XOR<Prisma.ShaderFileUpdateWithoutLoaderInput, Prisma.ShaderFileUncheckedUpdateWithoutLoaderInput>
}

export type ShaderFileUpdateManyWithWhereWithoutLoaderInput = {
  where: Prisma.ShaderFileScalarWhereInput
  data: Prisma.XOR<Prisma.ShaderFileUpdateManyMutationInput, Prisma.ShaderFileUncheckedUpdateManyWithoutLoaderInput>
}

export type ShaderFileCreateWithoutShaderInput = {
  id?: string
  version: string
  createdAt?: Date | string
  updatedAt?: Date | string
  file?: Prisma.FileCreateNestedOneWithoutShaderFileInput
  minecraftVersion: Prisma.MinecraftVersionCreateNestedOneWithoutShaderFilesInput
  loader: Prisma.MinecraftLoaderCreateNestedOneWithoutShaderFilesInput
  packShaders?: Prisma.PackShaderCreateNestedManyWithoutShaderFileInput
}

export type ShaderFileUncheckedCreateWithoutShaderInput = {
  id?: string
  fileId?: string | null
  version: string
  minecraftVersionId: string
  loaderId: string
  createdAt?: Date | string
  updatedAt?: Date | string
  packShaders?: Prisma.PackShaderUncheckedCreateNestedManyWithoutShaderFileInput
}

export type ShaderFileCreateOrConnectWithoutShaderInput = {
  where: Prisma.ShaderFileWhereUniqueInput
  create: Prisma.XOR<Prisma.ShaderFileCreateWithoutShaderInput, Prisma.ShaderFileUncheckedCreateWithoutShaderInput>
}

export type ShaderFileCreateManyShaderInputEnvelope = {
  data: Prisma.ShaderFileCreateManyShaderInput | Prisma.ShaderFileCreateManyShaderInput[]
  skipDuplicates?: boolean
}

export type ShaderFileUpsertWithWhereUniqueWithoutShaderInput = {
  where: Prisma.ShaderFileWhereUniqueInput
  update: Prisma.XOR<Prisma.ShaderFileUpdateWithoutShaderInput, Prisma.ShaderFileUncheckedUpdateWithoutShaderInput>
  create: Prisma.XOR<Prisma.ShaderFileCreateWithoutShaderInput, Prisma.ShaderFileUncheckedCreateWithoutShaderInput>
}

export type ShaderFileUpdateWithWhereUniqueWithoutShaderInput = {
  where: Prisma.ShaderFileWhereUniqueInput
  data: Prisma.XOR<Prisma.ShaderFileUpdateWithoutShaderInput, Prisma.ShaderFileUncheckedUpdateWithoutShaderInput>
}

export type ShaderFileUpdateManyWithWhereWithoutShaderInput = {
  where: Prisma.ShaderFileScalarWhereInput
  data: Prisma.XOR<Prisma.ShaderFileUpdateManyMutationInput, Prisma.ShaderFileUncheckedUpdateManyWithoutShaderInput>
}

export type ShaderFileCreateWithoutPackShadersInput = {
  id?: string
  version: string
  createdAt?: Date | string
  updatedAt?: Date | string
  file?: Prisma.FileCreateNestedOneWithoutShaderFileInput
  shader?: Prisma.ShaderCreateNestedOneWithoutShaderFilesInput
  minecraftVersion: Prisma.MinecraftVersionCreateNestedOneWithoutShaderFilesInput
  loader: Prisma.MinecraftLoaderCreateNestedOneWithoutShaderFilesInput
}

export type ShaderFileUncheckedCreateWithoutPackShadersInput = {
  id?: string
  fileId?: string | null
  shaderId?: string | null
  version: string
  minecraftVersionId: string
  loaderId: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ShaderFileCreateOrConnectWithoutPackShadersInput = {
  where: Prisma.ShaderFileWhereUniqueInput
  create: Prisma.XOR<Prisma.ShaderFileCreateWithoutPackShadersInput, Prisma.ShaderFileUncheckedCreateWithoutPackShadersInput>
}

export type ShaderFileUpsertWithoutPackShadersInput = {
  update: Prisma.XOR<Prisma.ShaderFileUpdateWithoutPackShadersInput, Prisma.ShaderFileUncheckedUpdateWithoutPackShadersInput>
  create: Prisma.XOR<Prisma.ShaderFileCreateWithoutPackShadersInput, Prisma.ShaderFileUncheckedCreateWithoutPackShadersInput>
  where?: Prisma.ShaderFileWhereInput
}

export type ShaderFileUpdateToOneWithWhereWithoutPackShadersInput = {
  where?: Prisma.ShaderFileWhereInput
  data: Prisma.XOR<Prisma.ShaderFileUpdateWithoutPackShadersInput, Prisma.ShaderFileUncheckedUpdateWithoutPackShadersInput>
}

export type ShaderFileUpdateWithoutPackShadersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  version?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  file?: Prisma.FileUpdateOneWithoutShaderFileNestedInput
  shader?: Prisma.ShaderUpdateOneWithoutShaderFilesNestedInput
  minecraftVersion?: Prisma.MinecraftVersionUpdateOneRequiredWithoutShaderFilesNestedInput
  loader?: Prisma.MinecraftLoaderUpdateOneRequiredWithoutShaderFilesNestedInput
}

export type ShaderFileUncheckedUpdateWithoutPackShadersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fileId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  shaderId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  version?: Prisma.StringFieldUpdateOperationsInput | string
  minecraftVersionId?: Prisma.StringFieldUpdateOperationsInput | string
  loaderId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ShaderFileCreateManyMinecraftVersionInput = {
  id?: string
  fileId?: string | null
  shaderId?: string | null
  version: string
  loaderId: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ShaderFileUpdateWithoutMinecraftVersionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  version?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  file?: Prisma.FileUpdateOneWithoutShaderFileNestedInput
  shader?: Prisma.ShaderUpdateOneWithoutShaderFilesNestedInput
  loader?: Prisma.MinecraftLoaderUpdateOneRequiredWithoutShaderFilesNestedInput
  packShaders?: Prisma.PackShaderUpdateManyWithoutShaderFileNestedInput
}

export type ShaderFileUncheckedUpdateWithoutMinecraftVersionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fileId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  shaderId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  version?: Prisma.StringFieldUpdateOperationsInput | string
  loaderId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  packShaders?: Prisma.PackShaderUncheckedUpdateManyWithoutShaderFileNestedInput
}

export type ShaderFileUncheckedUpdateManyWithoutMinecraftVersionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fileId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  shaderId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  version?: Prisma.StringFieldUpdateOperationsInput | string
  loaderId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ShaderFileCreateManyLoaderInput = {
  id?: string
  fileId?: string | null
  shaderId?: string | null
  version: string
  minecraftVersionId: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ShaderFileUpdateWithoutLoaderInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  version?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  file?: Prisma.FileUpdateOneWithoutShaderFileNestedInput
  shader?: Prisma.ShaderUpdateOneWithoutShaderFilesNestedInput
  minecraftVersion?: Prisma.MinecraftVersionUpdateOneRequiredWithoutShaderFilesNestedInput
  packShaders?: Prisma.PackShaderUpdateManyWithoutShaderFileNestedInput
}

export type ShaderFileUncheckedUpdateWithoutLoaderInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fileId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  shaderId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  version?: Prisma.StringFieldUpdateOperationsInput | string
  minecraftVersionId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  packShaders?: Prisma.PackShaderUncheckedUpdateManyWithoutShaderFileNestedInput
}

export type ShaderFileUncheckedUpdateManyWithoutLoaderInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fileId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  shaderId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  version?: Prisma.StringFieldUpdateOperationsInput | string
  minecraftVersionId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ShaderFileCreateManyShaderInput = {
  id?: string
  fileId?: string | null
  version: string
  minecraftVersionId: string
  loaderId: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ShaderFileUpdateWithoutShaderInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  version?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  file?: Prisma.FileUpdateOneWithoutShaderFileNestedInput
  minecraftVersion?: Prisma.MinecraftVersionUpdateOneRequiredWithoutShaderFilesNestedInput
  loader?: Prisma.MinecraftLoaderUpdateOneRequiredWithoutShaderFilesNestedInput
  packShaders?: Prisma.PackShaderUpdateManyWithoutShaderFileNestedInput
}

export type ShaderFileUncheckedUpdateWithoutShaderInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fileId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  version?: Prisma.StringFieldUpdateOperationsInput | string
  minecraftVersionId?: Prisma.StringFieldUpdateOperationsInput | string
  loaderId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  packShaders?: Prisma.PackShaderUncheckedUpdateManyWithoutShaderFileNestedInput
}

export type ShaderFileUncheckedUpdateManyWithoutShaderInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fileId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  version?: Prisma.StringFieldUpdateOperationsInput | string
  minecraftVersionId?: Prisma.StringFieldUpdateOperationsInput | string
  loaderId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type ShaderFileCountOutputType
 */

export type ShaderFileCountOutputType = {
  packShaders: number
}

export type ShaderFileCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  packShaders?: boolean | ShaderFileCountOutputTypeCountPackShadersArgs
}

/**
 * ShaderFileCountOutputType without action
 */
export type ShaderFileCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ShaderFileCountOutputType
   */
  select?: Prisma.ShaderFileCountOutputTypeSelect<ExtArgs> | null
}

/**
 * ShaderFileCountOutputType without action
 */
export type ShaderFileCountOutputTypeCountPackShadersArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PackShaderWhereInput
}


export type ShaderFileSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  fileId?: boolean
  shaderId?: boolean
  version?: boolean
  minecraftVersionId?: boolean
  loaderId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  file?: boolean | Prisma.ShaderFile$fileArgs<ExtArgs>
  shader?: boolean | Prisma.ShaderFile$shaderArgs<ExtArgs>
  minecraftVersion?: boolean | Prisma.MinecraftVersionDefaultArgs<ExtArgs>
  loader?: boolean | Prisma.MinecraftLoaderDefaultArgs<ExtArgs>
  packShaders?: boolean | Prisma.ShaderFile$packShadersArgs<ExtArgs>
  _count?: boolean | Prisma.ShaderFileCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["shaderFile"]>

export type ShaderFileSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  fileId?: boolean
  shaderId?: boolean
  version?: boolean
  minecraftVersionId?: boolean
  loaderId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  file?: boolean | Prisma.ShaderFile$fileArgs<ExtArgs>
  shader?: boolean | Prisma.ShaderFile$shaderArgs<ExtArgs>
  minecraftVersion?: boolean | Prisma.MinecraftVersionDefaultArgs<ExtArgs>
  loader?: boolean | Prisma.MinecraftLoaderDefaultArgs<ExtArgs>
}, ExtArgs["result"]["shaderFile"]>

export type ShaderFileSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  fileId?: boolean
  shaderId?: boolean
  version?: boolean
  minecraftVersionId?: boolean
  loaderId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  file?: boolean | Prisma.ShaderFile$fileArgs<ExtArgs>
  shader?: boolean | Prisma.ShaderFile$shaderArgs<ExtArgs>
  minecraftVersion?: boolean | Prisma.MinecraftVersionDefaultArgs<ExtArgs>
  loader?: boolean | Prisma.MinecraftLoaderDefaultArgs<ExtArgs>
}, ExtArgs["result"]["shaderFile"]>

export type ShaderFileSelectScalar = {
  id?: boolean
  fileId?: boolean
  shaderId?: boolean
  version?: boolean
  minecraftVersionId?: boolean
  loaderId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type ShaderFileOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "fileId" | "shaderId" | "version" | "minecraftVersionId" | "loaderId" | "createdAt" | "updatedAt", ExtArgs["result"]["shaderFile"]>
export type ShaderFileInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  file?: boolean | Prisma.ShaderFile$fileArgs<ExtArgs>
  shader?: boolean | Prisma.ShaderFile$shaderArgs<ExtArgs>
  minecraftVersion?: boolean | Prisma.MinecraftVersionDefaultArgs<ExtArgs>
  loader?: boolean | Prisma.MinecraftLoaderDefaultArgs<ExtArgs>
  packShaders?: boolean | Prisma.ShaderFile$packShadersArgs<ExtArgs>
  _count?: boolean | Prisma.ShaderFileCountOutputTypeDefaultArgs<ExtArgs>
}
export type ShaderFileIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  file?: boolean | Prisma.ShaderFile$fileArgs<ExtArgs>
  shader?: boolean | Prisma.ShaderFile$shaderArgs<ExtArgs>
  minecraftVersion?: boolean | Prisma.MinecraftVersionDefaultArgs<ExtArgs>
  loader?: boolean | Prisma.MinecraftLoaderDefaultArgs<ExtArgs>
}
export type ShaderFileIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  file?: boolean | Prisma.ShaderFile$fileArgs<ExtArgs>
  shader?: boolean | Prisma.ShaderFile$shaderArgs<ExtArgs>
  minecraftVersion?: boolean | Prisma.MinecraftVersionDefaultArgs<ExtArgs>
  loader?: boolean | Prisma.MinecraftLoaderDefaultArgs<ExtArgs>
}

export type $ShaderFilePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ShaderFile"
  objects: {
    file: Prisma.$FilePayload<ExtArgs> | null
    shader: Prisma.$ShaderPayload<ExtArgs> | null
    minecraftVersion: Prisma.$MinecraftVersionPayload<ExtArgs>
    loader: Prisma.$MinecraftLoaderPayload<ExtArgs>
    packShaders: Prisma.$PackShaderPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    fileId: string | null
    shaderId: string | null
    version: string
    minecraftVersionId: string
    loaderId: string
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["shaderFile"]>
  composites: {}
}

export type ShaderFileGetPayload<S extends boolean | null | undefined | ShaderFileDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ShaderFilePayload, S>

export type ShaderFileCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ShaderFileFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ShaderFileCountAggregateInputType | true
  }

export interface ShaderFileDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ShaderFile'], meta: { name: 'ShaderFile' } }
  /**
   * Find zero or one ShaderFile that matches the filter.
   * @param {ShaderFileFindUniqueArgs} args - Arguments to find a ShaderFile
   * @example
   * // Get one ShaderFile
   * const shaderFile = await prisma.shaderFile.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ShaderFileFindUniqueArgs>(args: Prisma.SelectSubset<T, ShaderFileFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ShaderFileClient<runtime.Types.Result.GetResult<Prisma.$ShaderFilePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ShaderFile that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ShaderFileFindUniqueOrThrowArgs} args - Arguments to find a ShaderFile
   * @example
   * // Get one ShaderFile
   * const shaderFile = await prisma.shaderFile.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ShaderFileFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ShaderFileFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ShaderFileClient<runtime.Types.Result.GetResult<Prisma.$ShaderFilePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ShaderFile that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ShaderFileFindFirstArgs} args - Arguments to find a ShaderFile
   * @example
   * // Get one ShaderFile
   * const shaderFile = await prisma.shaderFile.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ShaderFileFindFirstArgs>(args?: Prisma.SelectSubset<T, ShaderFileFindFirstArgs<ExtArgs>>): Prisma.Prisma__ShaderFileClient<runtime.Types.Result.GetResult<Prisma.$ShaderFilePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ShaderFile that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ShaderFileFindFirstOrThrowArgs} args - Arguments to find a ShaderFile
   * @example
   * // Get one ShaderFile
   * const shaderFile = await prisma.shaderFile.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ShaderFileFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ShaderFileFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ShaderFileClient<runtime.Types.Result.GetResult<Prisma.$ShaderFilePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ShaderFiles that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ShaderFileFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ShaderFiles
   * const shaderFiles = await prisma.shaderFile.findMany()
   * 
   * // Get first 10 ShaderFiles
   * const shaderFiles = await prisma.shaderFile.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const shaderFileWithIdOnly = await prisma.shaderFile.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ShaderFileFindManyArgs>(args?: Prisma.SelectSubset<T, ShaderFileFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ShaderFilePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ShaderFile.
   * @param {ShaderFileCreateArgs} args - Arguments to create a ShaderFile.
   * @example
   * // Create one ShaderFile
   * const ShaderFile = await prisma.shaderFile.create({
   *   data: {
   *     // ... data to create a ShaderFile
   *   }
   * })
   * 
   */
  create<T extends ShaderFileCreateArgs>(args: Prisma.SelectSubset<T, ShaderFileCreateArgs<ExtArgs>>): Prisma.Prisma__ShaderFileClient<runtime.Types.Result.GetResult<Prisma.$ShaderFilePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ShaderFiles.
   * @param {ShaderFileCreateManyArgs} args - Arguments to create many ShaderFiles.
   * @example
   * // Create many ShaderFiles
   * const shaderFile = await prisma.shaderFile.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ShaderFileCreateManyArgs>(args?: Prisma.SelectSubset<T, ShaderFileCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many ShaderFiles and returns the data saved in the database.
   * @param {ShaderFileCreateManyAndReturnArgs} args - Arguments to create many ShaderFiles.
   * @example
   * // Create many ShaderFiles
   * const shaderFile = await prisma.shaderFile.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many ShaderFiles and only return the `id`
   * const shaderFileWithIdOnly = await prisma.shaderFile.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ShaderFileCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ShaderFileCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ShaderFilePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a ShaderFile.
   * @param {ShaderFileDeleteArgs} args - Arguments to delete one ShaderFile.
   * @example
   * // Delete one ShaderFile
   * const ShaderFile = await prisma.shaderFile.delete({
   *   where: {
   *     // ... filter to delete one ShaderFile
   *   }
   * })
   * 
   */
  delete<T extends ShaderFileDeleteArgs>(args: Prisma.SelectSubset<T, ShaderFileDeleteArgs<ExtArgs>>): Prisma.Prisma__ShaderFileClient<runtime.Types.Result.GetResult<Prisma.$ShaderFilePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ShaderFile.
   * @param {ShaderFileUpdateArgs} args - Arguments to update one ShaderFile.
   * @example
   * // Update one ShaderFile
   * const shaderFile = await prisma.shaderFile.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ShaderFileUpdateArgs>(args: Prisma.SelectSubset<T, ShaderFileUpdateArgs<ExtArgs>>): Prisma.Prisma__ShaderFileClient<runtime.Types.Result.GetResult<Prisma.$ShaderFilePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ShaderFiles.
   * @param {ShaderFileDeleteManyArgs} args - Arguments to filter ShaderFiles to delete.
   * @example
   * // Delete a few ShaderFiles
   * const { count } = await prisma.shaderFile.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ShaderFileDeleteManyArgs>(args?: Prisma.SelectSubset<T, ShaderFileDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ShaderFiles.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ShaderFileUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ShaderFiles
   * const shaderFile = await prisma.shaderFile.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ShaderFileUpdateManyArgs>(args: Prisma.SelectSubset<T, ShaderFileUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ShaderFiles and returns the data updated in the database.
   * @param {ShaderFileUpdateManyAndReturnArgs} args - Arguments to update many ShaderFiles.
   * @example
   * // Update many ShaderFiles
   * const shaderFile = await prisma.shaderFile.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more ShaderFiles and only return the `id`
   * const shaderFileWithIdOnly = await prisma.shaderFile.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ShaderFileUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ShaderFileUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ShaderFilePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one ShaderFile.
   * @param {ShaderFileUpsertArgs} args - Arguments to update or create a ShaderFile.
   * @example
   * // Update or create a ShaderFile
   * const shaderFile = await prisma.shaderFile.upsert({
   *   create: {
   *     // ... data to create a ShaderFile
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ShaderFile we want to update
   *   }
   * })
   */
  upsert<T extends ShaderFileUpsertArgs>(args: Prisma.SelectSubset<T, ShaderFileUpsertArgs<ExtArgs>>): Prisma.Prisma__ShaderFileClient<runtime.Types.Result.GetResult<Prisma.$ShaderFilePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ShaderFiles.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ShaderFileCountArgs} args - Arguments to filter ShaderFiles to count.
   * @example
   * // Count the number of ShaderFiles
   * const count = await prisma.shaderFile.count({
   *   where: {
   *     // ... the filter for the ShaderFiles we want to count
   *   }
   * })
  **/
  count<T extends ShaderFileCountArgs>(
    args?: Prisma.Subset<T, ShaderFileCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ShaderFileCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ShaderFile.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ShaderFileAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ShaderFileAggregateArgs>(args: Prisma.Subset<T, ShaderFileAggregateArgs>): Prisma.PrismaPromise<GetShaderFileAggregateType<T>>

  /**
   * Group by ShaderFile.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ShaderFileGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ShaderFileGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ShaderFileGroupByArgs['orderBy'] }
      : { orderBy?: ShaderFileGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ShaderFileGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetShaderFileGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ShaderFile model
 */
readonly fields: ShaderFileFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ShaderFile.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ShaderFileClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  file<T extends Prisma.ShaderFile$fileArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ShaderFile$fileArgs<ExtArgs>>): Prisma.Prisma__FileClient<runtime.Types.Result.GetResult<Prisma.$FilePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  shader<T extends Prisma.ShaderFile$shaderArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ShaderFile$shaderArgs<ExtArgs>>): Prisma.Prisma__ShaderClient<runtime.Types.Result.GetResult<Prisma.$ShaderPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  minecraftVersion<T extends Prisma.MinecraftVersionDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.MinecraftVersionDefaultArgs<ExtArgs>>): Prisma.Prisma__MinecraftVersionClient<runtime.Types.Result.GetResult<Prisma.$MinecraftVersionPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  loader<T extends Prisma.MinecraftLoaderDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.MinecraftLoaderDefaultArgs<ExtArgs>>): Prisma.Prisma__MinecraftLoaderClient<runtime.Types.Result.GetResult<Prisma.$MinecraftLoaderPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  packShaders<T extends Prisma.ShaderFile$packShadersArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ShaderFile$packShadersArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PackShaderPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ShaderFile model
 */
export interface ShaderFileFieldRefs {
  readonly id: Prisma.FieldRef<"ShaderFile", 'String'>
  readonly fileId: Prisma.FieldRef<"ShaderFile", 'String'>
  readonly shaderId: Prisma.FieldRef<"ShaderFile", 'String'>
  readonly version: Prisma.FieldRef<"ShaderFile", 'String'>
  readonly minecraftVersionId: Prisma.FieldRef<"ShaderFile", 'String'>
  readonly loaderId: Prisma.FieldRef<"ShaderFile", 'String'>
  readonly createdAt: Prisma.FieldRef<"ShaderFile", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"ShaderFile", 'DateTime'>
}
    

// Custom InputTypes
/**
 * ShaderFile findUnique
 */
export type ShaderFileFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ShaderFile
   */
  select?: Prisma.ShaderFileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ShaderFile
   */
  omit?: Prisma.ShaderFileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ShaderFileInclude<ExtArgs> | null
  /**
   * Filter, which ShaderFile to fetch.
   */
  where: Prisma.ShaderFileWhereUniqueInput
}

/**
 * ShaderFile findUniqueOrThrow
 */
export type ShaderFileFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ShaderFile
   */
  select?: Prisma.ShaderFileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ShaderFile
   */
  omit?: Prisma.ShaderFileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ShaderFileInclude<ExtArgs> | null
  /**
   * Filter, which ShaderFile to fetch.
   */
  where: Prisma.ShaderFileWhereUniqueInput
}

/**
 * ShaderFile findFirst
 */
export type ShaderFileFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ShaderFile
   */
  select?: Prisma.ShaderFileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ShaderFile
   */
  omit?: Prisma.ShaderFileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ShaderFileInclude<ExtArgs> | null
  /**
   * Filter, which ShaderFile to fetch.
   */
  where?: Prisma.ShaderFileWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ShaderFiles to fetch.
   */
  orderBy?: Prisma.ShaderFileOrderByWithRelationInput | Prisma.ShaderFileOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ShaderFiles.
   */
  cursor?: Prisma.ShaderFileWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ShaderFiles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ShaderFiles.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ShaderFiles.
   */
  distinct?: Prisma.ShaderFileScalarFieldEnum | Prisma.ShaderFileScalarFieldEnum[]
}

/**
 * ShaderFile findFirstOrThrow
 */
export type ShaderFileFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ShaderFile
   */
  select?: Prisma.ShaderFileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ShaderFile
   */
  omit?: Prisma.ShaderFileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ShaderFileInclude<ExtArgs> | null
  /**
   * Filter, which ShaderFile to fetch.
   */
  where?: Prisma.ShaderFileWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ShaderFiles to fetch.
   */
  orderBy?: Prisma.ShaderFileOrderByWithRelationInput | Prisma.ShaderFileOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ShaderFiles.
   */
  cursor?: Prisma.ShaderFileWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ShaderFiles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ShaderFiles.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ShaderFiles.
   */
  distinct?: Prisma.ShaderFileScalarFieldEnum | Prisma.ShaderFileScalarFieldEnum[]
}

/**
 * ShaderFile findMany
 */
export type ShaderFileFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ShaderFile
   */
  select?: Prisma.ShaderFileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ShaderFile
   */
  omit?: Prisma.ShaderFileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ShaderFileInclude<ExtArgs> | null
  /**
   * Filter, which ShaderFiles to fetch.
   */
  where?: Prisma.ShaderFileWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ShaderFiles to fetch.
   */
  orderBy?: Prisma.ShaderFileOrderByWithRelationInput | Prisma.ShaderFileOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ShaderFiles.
   */
  cursor?: Prisma.ShaderFileWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ShaderFiles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ShaderFiles.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ShaderFiles.
   */
  distinct?: Prisma.ShaderFileScalarFieldEnum | Prisma.ShaderFileScalarFieldEnum[]
}

/**
 * ShaderFile create
 */
export type ShaderFileCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ShaderFile
   */
  select?: Prisma.ShaderFileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ShaderFile
   */
  omit?: Prisma.ShaderFileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ShaderFileInclude<ExtArgs> | null
  /**
   * The data needed to create a ShaderFile.
   */
  data: Prisma.XOR<Prisma.ShaderFileCreateInput, Prisma.ShaderFileUncheckedCreateInput>
}

/**
 * ShaderFile createMany
 */
export type ShaderFileCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ShaderFiles.
   */
  data: Prisma.ShaderFileCreateManyInput | Prisma.ShaderFileCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ShaderFile createManyAndReturn
 */
export type ShaderFileCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ShaderFile
   */
  select?: Prisma.ShaderFileSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ShaderFile
   */
  omit?: Prisma.ShaderFileOmit<ExtArgs> | null
  /**
   * The data used to create many ShaderFiles.
   */
  data: Prisma.ShaderFileCreateManyInput | Prisma.ShaderFileCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ShaderFileIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * ShaderFile update
 */
export type ShaderFileUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ShaderFile
   */
  select?: Prisma.ShaderFileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ShaderFile
   */
  omit?: Prisma.ShaderFileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ShaderFileInclude<ExtArgs> | null
  /**
   * The data needed to update a ShaderFile.
   */
  data: Prisma.XOR<Prisma.ShaderFileUpdateInput, Prisma.ShaderFileUncheckedUpdateInput>
  /**
   * Choose, which ShaderFile to update.
   */
  where: Prisma.ShaderFileWhereUniqueInput
}

/**
 * ShaderFile updateMany
 */
export type ShaderFileUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ShaderFiles.
   */
  data: Prisma.XOR<Prisma.ShaderFileUpdateManyMutationInput, Prisma.ShaderFileUncheckedUpdateManyInput>
  /**
   * Filter which ShaderFiles to update
   */
  where?: Prisma.ShaderFileWhereInput
  /**
   * Limit how many ShaderFiles to update.
   */
  limit?: number
}

/**
 * ShaderFile updateManyAndReturn
 */
export type ShaderFileUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ShaderFile
   */
  select?: Prisma.ShaderFileSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ShaderFile
   */
  omit?: Prisma.ShaderFileOmit<ExtArgs> | null
  /**
   * The data used to update ShaderFiles.
   */
  data: Prisma.XOR<Prisma.ShaderFileUpdateManyMutationInput, Prisma.ShaderFileUncheckedUpdateManyInput>
  /**
   * Filter which ShaderFiles to update
   */
  where?: Prisma.ShaderFileWhereInput
  /**
   * Limit how many ShaderFiles to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ShaderFileIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * ShaderFile upsert
 */
export type ShaderFileUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ShaderFile
   */
  select?: Prisma.ShaderFileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ShaderFile
   */
  omit?: Prisma.ShaderFileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ShaderFileInclude<ExtArgs> | null
  /**
   * The filter to search for the ShaderFile to update in case it exists.
   */
  where: Prisma.ShaderFileWhereUniqueInput
  /**
   * In case the ShaderFile found by the `where` argument doesn't exist, create a new ShaderFile with this data.
   */
  create: Prisma.XOR<Prisma.ShaderFileCreateInput, Prisma.ShaderFileUncheckedCreateInput>
  /**
   * In case the ShaderFile was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ShaderFileUpdateInput, Prisma.ShaderFileUncheckedUpdateInput>
}

/**
 * ShaderFile delete
 */
export type ShaderFileDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ShaderFile
   */
  select?: Prisma.ShaderFileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ShaderFile
   */
  omit?: Prisma.ShaderFileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ShaderFileInclude<ExtArgs> | null
  /**
   * Filter which ShaderFile to delete.
   */
  where: Prisma.ShaderFileWhereUniqueInput
}

/**
 * ShaderFile deleteMany
 */
export type ShaderFileDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ShaderFiles to delete
   */
  where?: Prisma.ShaderFileWhereInput
  /**
   * Limit how many ShaderFiles to delete.
   */
  limit?: number
}

/**
 * ShaderFile.file
 */
export type ShaderFile$fileArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the File
   */
  select?: Prisma.FileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the File
   */
  omit?: Prisma.FileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FileInclude<ExtArgs> | null
  where?: Prisma.FileWhereInput
}

/**
 * ShaderFile.shader
 */
export type ShaderFile$shaderArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Shader
   */
  select?: Prisma.ShaderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Shader
   */
  omit?: Prisma.ShaderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ShaderInclude<ExtArgs> | null
  where?: Prisma.ShaderWhereInput
}

/**
 * ShaderFile.packShaders
 */
export type ShaderFile$packShadersArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PackShader
   */
  select?: Prisma.PackShaderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PackShader
   */
  omit?: Prisma.PackShaderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PackShaderInclude<ExtArgs> | null
  where?: Prisma.PackShaderWhereInput
  orderBy?: Prisma.PackShaderOrderByWithRelationInput | Prisma.PackShaderOrderByWithRelationInput[]
  cursor?: Prisma.PackShaderWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.PackShaderScalarFieldEnum | Prisma.PackShaderScalarFieldEnum[]
}

/**
 * ShaderFile without action
 */
export type ShaderFileDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ShaderFile
   */
  select?: Prisma.ShaderFileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ShaderFile
   */
  omit?: Prisma.ShaderFileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ShaderFileInclude<ExtArgs> | null
}
